-- Bet+AI WERSJA 211 — PRODUCTION AI OPERATIONS + REPLAY LAB ALL-IN
-- V201 Scheduled Odds Snapshots
-- V202 True Closing Line
-- V203 Automatic Settlement Telemetry
-- V204 Nightly Model Rebuild
-- V205 Model Canary Mode
-- V206 Data Anomaly Monitor
-- V207 API Health Monitor
-- V208 Prediction Reproducibility
-- V209 Performance Explorer
-- V210 Operations Control Center
-- V211 Replay Lab
--
-- URUCHOM RAZ: Supabase -> SQL Editor -> Run.
-- Zakłada wcześniejsze V200. Wszystkie operacje są idempotentne.
-- Tabele są backend-only; Netlify Functions używają SERVICE ROLE.

-- ============================================================
-- V201 / V202 — PRE-MATCH ODDS TIMELINE + TRUE CLOSING FOUNDATION
-- ============================================================
-- V208/V211: nowe freeze capture'y dostają kanoniczny SHA-256 niezależny od kolejności kluczy JSONB.
alter table public.match_prediction_freeze_ledger
  add column if not exists canonical_hash_v211 text null;

create index if not exists idx_match_prediction_freeze_canonical_v211
  on public.match_prediction_freeze_ledger(canonical_hash_v211)
  where canonical_hash_v211 is not null;

create table if not exists public.match_odds_timeline (
  id bigint generated by default as identity primary key,
  fixture_id text not null,
  fixture_date timestamptz null,
  home_team text not null default '',
  away_team text not null default '',
  league text not null default '',
  market_key text not null,
  bookmaker text not null default '',
  odds numeric(10,4) not null check (odds > 1),
  model_probability numeric(7,3) null,
  fair_odds numeric(10,4) null,
  edge_pp numeric(8,3) null,
  snapshot_window text not null,
  target_minutes_before integer not null,
  actual_minutes_before numeric(10,2) null,
  source text not null default 'API-Football /odds',
  is_closing_candidate boolean not null default false,
  captured_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb,
  constraint match_odds_timeline_window_check
    check (snapshot_window in ('T24H','T6H','T1H','T15M','CLOSING','MANUAL')),
  constraint match_odds_timeline_unique_quote
    unique (fixture_id, snapshot_window, market_key, bookmaker)
);

create index if not exists idx_match_odds_timeline_fixture_time
  on public.match_odds_timeline(fixture_id, captured_at asc);

create index if not exists idx_match_odds_timeline_window
  on public.match_odds_timeline(snapshot_window, fixture_date desc);

create index if not exists idx_match_odds_timeline_closing
  on public.match_odds_timeline(fixture_id, is_closing_candidate, captured_at desc)
  where is_closing_candidate = true;

-- Existing odds history receives production metadata without replacing old data.
alter table public.match_odds_history
  add column if not exists capture_window text null;

alter table public.match_odds_history
  add column if not exists capture_source text null;

create unique index if not exists idx_match_odds_history_window_unique_v211
  on public.match_odds_history(fixture_id, market_key, bookmaker, capture_window)
  where capture_window is not null;

-- ============================================================
-- V203 / V204 / V210 — OPERATIONS RUN TELEMETRY
-- ============================================================
create table if not exists public.match_ops_runs (
  id bigint generated by default as identity primary key,
  run_type text not null,
  status text not null default 'running',
  started_at timestamptz not null default now(),
  finished_at timestamptz null,
  duration_ms integer null,
  metrics jsonb not null default '{}'::jsonb,
  error_text text null,
  created_at timestamptz not null default now(),
  constraint match_ops_runs_type_check
    check (run_type in ('odds_snapshot','settlement','model_rebuild','anomaly_scan','replay_read','performance_explorer','api_health')),
  constraint match_ops_runs_status_check
    check (status in ('running','ok','partial','error','skipped'))
);

create index if not exists idx_match_ops_runs_type_time
  on public.match_ops_runs(run_type, started_at desc);

create index if not exists idx_match_ops_runs_status_time
  on public.match_ops_runs(status, started_at desc);

-- ============================================================
-- V205 — CANARY REGISTRY
-- ============================================================
create table if not exists public.match_model_canary_state (
  registry_key text primary key,
  baseline_version text not null default 'BETAI_CHAMPION_V158_CORE',
  candidate_version text not null default 'BETAI_PREDICTION_ENGINE_4_V200',
  state text not null default 'SHADOW',
  exposure_pct integer not null default 0 check (exposure_pct between 0 and 100),
  min_shadow_samples integer not null default 120,
  shadow_samples integer not null default 0,
  metrics jsonb not null default '{}'::jsonb,
  started_at timestamptz not null default now(),
  promoted_at timestamptz null,
  rollback_at timestamptz null,
  updated_at timestamptz not null default now(),
  constraint match_model_canary_state_check
    check (state in ('SHADOW','READY','PROMOTED','ROLLBACK','PAUSED'))
);

insert into public.match_model_canary_state (
  registry_key, baseline_version, candidate_version, state, exposure_pct, min_shadow_samples
)
values (
  'football-main', 'BETAI_CHAMPION_V158_CORE', 'BETAI_PREDICTION_ENGINE_4_V200', 'SHADOW', 0, 120
)
on conflict (registry_key) do nothing;

-- ============================================================
-- V206 — DATA ANOMALY MONITOR
-- ============================================================
create table if not exists public.match_data_anomalies (
  id bigint generated by default as identity primary key,
  fingerprint text not null unique,
  fixture_id text null,
  anomaly_type text not null,
  severity text not null default 'warning',
  status text not null default 'open',
  detail jsonb not null default '{}'::jsonb,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  resolved_at timestamptz null,
  constraint match_data_anomalies_severity_check
    check (severity in ('info','warning','critical')),
  constraint match_data_anomalies_status_check
    check (status in ('open','resolved','ignored'))
);

create index if not exists idx_match_data_anomalies_open
  on public.match_data_anomalies(status, severity, last_seen_at desc);

create index if not exists idx_match_data_anomalies_fixture
  on public.match_data_anomalies(fixture_id, last_seen_at desc);

-- ============================================================
-- V207 — API HEALTH EVENTS
-- ============================================================
create table if not exists public.match_api_health_events (
  id bigint generated by default as identity primary key,
  endpoint text not null default '',
  event_type text not null,
  status_code integer null,
  budget_scope text null,
  detail jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint match_api_health_event_type_check
    check (event_type in ('RATE_LIMIT','HTTP_ERROR','TIMEOUT','BUDGET_BLOCK','QUEUE_WAIT','RECOVERED','INFO'))
);

create index if not exists idx_match_api_health_events_time
  on public.match_api_health_events(created_at desc);

create index if not exists idx_match_api_health_events_type
  on public.match_api_health_events(event_type, created_at desc);

-- ============================================================
-- RLS — backend only
-- ============================================================
alter table public.match_odds_timeline enable row level security;
alter table public.match_ops_runs enable row level security;
alter table public.match_model_canary_state enable row level security;
alter table public.match_data_anomalies enable row level security;
alter table public.match_api_health_events enable row level security;

comment on table public.match_odds_timeline is
  'V201-V202 production pre-match odds snapshots at T-24h/T-6h/T-1h/T-15m and closing candidates.';

comment on table public.match_ops_runs is
  'V203-V210 production telemetry for scheduled odds, settlement, nightly rebuild and anomaly jobs.';

comment on table public.match_model_canary_state is
  'V205 shadow/canary state for candidate prediction engines before promotion.';

comment on table public.match_data_anomalies is
  'V206 automatically detected malformed or suspicious prediction/fixture records.';

comment on table public.match_api_health_events is
  'V207 API-Football health events from the simulator rate shield.';

-- ============================================================
-- KONTROLA PO WDROŻENIU
-- ============================================================
-- select * from public.match_model_canary_state where registry_key='football-main';
-- select run_type,status,metrics,started_at from public.match_ops_runs order by started_at desc limit 20;
-- select snapshot_window,count(*) from public.match_odds_timeline group by snapshot_window order by snapshot_window;
-- select severity,status,count(*) from public.match_data_anomalies group by severity,status;
-- select event_type,count(*) from public.match_api_health_events where created_at > now()-interval '24 hours' group by event_type;
