-- BETAI WERSJA 15 — CENTRUM AI LIVE
-- Uruchom jeden raz w Supabase SQL Editor przed wdrożeniem wersji 15.
-- Tabela przechowuje realne uruchomienia skanów i rozliczeń wszystkich systemów AI.

begin;

create table if not exists public.ai_system_runs (
  id bigint generated by default as identity primary key,
  system_key text not null,
  run_type text not null,
  trigger_source text not null default 'scheduled',
  status text not null default 'success',
  started_at timestamptz not null default now(),
  finished_at timestamptz not null default now(),
  duration_ms integer not null default 0,
  checked_count integer not null default 0,
  candidate_count integer not null default 0,
  created_count integer not null default 0,
  settled_count integer not null default 0,
  pending_count integer not null default 0,
  api_calls integer not null default 0,
  api_remaining integer,
  message text,
  error_message text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),

  constraint ai_system_runs_system_key_check
    check (system_key in ('betai', 'typer', 'ograc', 'predictions')),
  constraint ai_system_runs_run_type_check
    check (run_type in ('publish', 'capture', 'settlement', 'health')),
  constraint ai_system_runs_status_check
    check (status in ('success', 'partial', 'error'))
);

create index if not exists ai_system_runs_latest_idx
  on public.ai_system_runs (finished_at desc);

create index if not exists ai_system_runs_system_type_idx
  on public.ai_system_runs (system_key, run_type, finished_at desc);

create index if not exists ai_system_runs_errors_idx
  on public.ai_system_runs (finished_at desc)
  where status in ('partial', 'error');

alter table public.ai_system_runs enable row level security;

-- Brak publicznych polityk jest celowy.
-- Zapis i odczyt wykonują funkcje Netlify przez SUPABASE_SERVICE_ROLE_KEY.

commit;

-- Kontrola po wykonaniu. Na początku wynik może być pusty.
select
  system_key,
  run_type,
  status,
  finished_at,
  created_count,
  settled_count,
  error_message
from public.ai_system_runs
order by finished_at desc
limit 20;
