-- Bet+AI WERSJA 180 — SELF LEARNING AI + MATCH INTELLIGENCE 3.0 ALL-IN
-- V167 Auto Weight Optimizer
-- V168 League-Specific Models
-- V169 Market-Specific Models
-- V170 Recency Learning
-- V171 Feature Performance Lab
-- V172 Adaptive Calibration
-- V173 Auto Promotion / Rollback
-- V174 AI Model Brain Dashboard
-- V175 Expected Lineups
-- V176 Safe Player Impact
-- V177 GK / Defence Proxy
-- V178 Fatigue & Schedule Congestion
-- V179 Safe Injury Importance
-- V180 Match Intelligence 3.0
--
-- URUCHOM RAZ w Supabase -> SQL Editor.
-- Ten pakiet zakłada, że V166 został już wdrożony, ale poniższe polecenia są
-- idempotentne i bezpieczne do ponownego uruchomienia.
-- Nie dodaje żadnych nowych requestów API-Football.

create table if not exists public.match_model_registry (
  registry_key text primary key,
  active_version text not null default 'BETAI_CHAMPION_V158_CORE',
  previous_version text null,
  status text not null default 'COLLECTING',
  promoted_at timestamptz null,
  rollback_at timestamptz null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.match_model_registry (
  registry_key, active_version, status
)
values (
  'football-main', 'BETAI_CHAMPION_V158_CORE', 'COLLECTING'
)
on conflict (registry_key) do nothing;

create table if not exists public.match_model_governance_events (
  id bigint generated by default as identity primary key,
  event_type text not null,
  from_version text null,
  to_version text not null,
  reason text not null default '',
  metrics jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint match_model_governance_event_type_check
    check (event_type in ('promote','rollback','manual','info'))
);

create index if not exists idx_match_model_governance_events_created
  on public.match_model_governance_events(created_at desc);

create index if not exists idx_match_model_governance_events_to_version
  on public.match_model_governance_events(to_version, created_at desc);

-- Opcjonalny dziennik profili uczących. Backend V180 może działać bez niego,
-- ponieważ aktualne wagi są liczone z rozliczonej historii przy odczycie performance.
-- Tabela zostaje przygotowana pod dalszą inspekcję/audyt wag bez migracji w przyszłości.
create table if not exists public.match_model_learning_profiles (
  profile_key text primary key,
  model_version text not null default 'BETAI_CHALLENGER_V180_SELF_LEARNING_MATCH_INTEL',
  profile_type text not null default 'global',
  league text null,
  market_key text null,
  sample_size integer not null default 0,
  half_life_days integer not null default 90,
  weights jsonb not null default '{}'::jsonb,
  calibration jsonb not null default '{}'::jsonb,
  metrics jsonb not null default '{}'::jsonb,
  profile_hash text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint match_model_learning_profiles_type_check
    check (profile_type in ('global','league','market','league_market'))
);

create index if not exists idx_match_model_learning_profiles_type
  on public.match_model_learning_profiles(profile_type, updated_at desc);

create index if not exists idx_match_model_learning_profiles_league_market
  on public.match_model_learning_profiles(league, market_key, updated_at desc);

-- V180 zapisuje źródła składowe w forecast.components w istniejącej tabeli
-- match_model_experiments. Te indeksy przyspieszają późniejsze uczenie per liga/model.
create index if not exists idx_match_model_experiments_v180_learning
  on public.match_model_experiments(model_version, model_role, status, settled_at desc);

create index if not exists idx_match_model_experiments_v180_league_learning
  on public.match_model_experiments(league, model_version, status, settled_at desc);

alter table public.match_model_registry enable row level security;
alter table public.match_model_governance_events enable row level security;
alter table public.match_model_learning_profiles enable row level security;

comment on table public.match_model_registry is
  'Bet+AI V173: trwały rejestr aktywnego modelu oraz poprzedniej stabilnej wersji do auto-rollbacku.';

comment on table public.match_model_governance_events is
  'Bet+AI V173: historia automatycznych promocji i rollbacków modeli.';

comment on table public.match_model_learning_profiles is
  'Bet+AI V167-V172: miejsce na audyt profili wag/kalibracji self-learning. Rdzeń V180 może przeliczać profile bezpośrednio z historii.';

-- Brak publicznych policies jest celowy.
-- Netlify Functions korzystają z SUPABASE_SERVICE_ROLE_KEY.

-- KONTROLA PO WDROŻENIU:
-- select * from public.match_model_registry where registry_key = 'football-main';
--
-- select model_role, model_version, status, count(*)
-- from public.match_model_experiments
-- group by model_role, model_version, status
-- order by model_role, model_version, status;
--
-- select event_type, from_version, to_version, reason, created_at
-- from public.match_model_governance_events
-- order by created_at desc
-- limit 20;
--
-- ZASADY V173:
-- 1) V180 zbiera sparowane wyniki przeciw Championowi V158.
-- 2) Auto-promocja najwcześniej po 120 parach.
-- 3) Wymagana poprawa Brier >= 0.004 i brak istotnej regresji rynku.
-- 4) Po promocji działa rolling watchdog do 50 ostatnich par.
-- 5) Pogorszenie Brier >= 0.025 lub regresja >= 2 rynków uruchamia rollback.
