-- WERSJA 1867.5 — opcjonalna tabela diagnostyczna. Można uruchomić wielokrotnie.
create table if not exists public.ai_pick_runs (
  id bigint generated by default as identity primary key,
  source text,
  status text,
  picks_created integer not null default 0,
  error_message text,
  details jsonb,
  created_at timestamptz not null default now(),
  finished_at timestamptz not null default now()
);
create index if not exists ai_pick_runs_finished_at_idx on public.ai_pick_runs (finished_at desc);
alter table public.ai_pick_runs enable row level security;
-- Brak publicznej polityki INSERT/UPDATE. Funkcje zapisują przez Service Role.
