-- Bet+AI v158 — Model Validation & Risk Lab
-- v153 Audit Trail / v154 Error Analysis / v155 Ensemble / v156 Sharp Disagreement /
-- v157 Portfolio Risk / v158 Model Control Center
-- Uruchom RAZ w Supabase -> SQL Editor.
--
-- Ta migracja NIE zwiększa liczby requestów API-Football.
-- Audit zapisuje wyłącznie dane/model/kursy, które aplikacja już posiada przed meczem.

create table if not exists public.match_prediction_audit (
  id bigint generated by default as identity primary key,
  fixture_id text not null,
  fixture_date timestamptz null,
  home_team text not null default '',
  away_team text not null default '',
  league text not null default '',
  country text not null default '',
  model_version text not null default 'BETAI_FORECAST_V158',
  audit_hash text not null,
  data_quality integer not null default 0 check (data_quality >= 0 and data_quality <= 100),
  decision text not null default '',
  market_key text not null default '',
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),

  constraint match_prediction_audit_fixture_hash_unique
    unique (fixture_id, audit_hash)
);

create index if not exists idx_match_prediction_audit_fixture_time
  on public.match_prediction_audit(fixture_id, created_at desc);

create index if not exists idx_match_prediction_audit_model_time
  on public.match_prediction_audit(model_version, created_at desc);

create index if not exists idx_match_prediction_audit_league_market
  on public.match_prediction_audit(league, market_key, created_at desc);

alter table public.match_prediction_audit enable row level security;

comment on table public.match_prediction_audit is
  'Bet+AI v153 Prediction Audit Trail: niezmienny ślad danych wejściowych, wag, ensemble, kalibracji i decyzji pre-match.';

comment on column public.match_prediction_audit.audit_hash is
  'SHA-256 skrócony hash konkretnego zestawu danych/modelu. Zapobiega dublowaniu identycznego audytu.';

comment on column public.match_prediction_audit.payload is
  'Snapshot modelInputs, sourceWeights, ensembleValidation, reliability, Professional Lab, value top3 i czynników użytych przed kickoffem.';

-- Brak publicznych policies jest celowy.
-- Netlify Functions używają SUPABASE_SERVICE_ROLE_KEY.

-- Opcjonalny podgląd ostatnich audytów:
-- select fixture_id, home_team, away_team, league, model_version,
--        decision, market_key, data_quality, left(audit_hash,12) as hash, created_at
-- from public.match_prediction_audit
-- order by created_at desc
-- limit 100;
