-- Bet+AI V368 — FM AI System Tracker
-- Paper tracking: 10 PLN flat stake per actionable FM AI pick (VALUE / STRONG_VALUE).
-- A pick is frozen on first publication and never rewritten after kickoff.

create table if not exists public.fm_ai_system_picks_v368 (
  id bigint generated by default as identity primary key,
  fixture_id text not null unique,
  fixture_date timestamptz not null,
  day_key date not null,
  home_team text not null default '',
  away_team text not null default '',
  league text not null default '',
  country text not null default '',
  market_key text not null,
  market_label text not null default '',
  decision text not null,
  odds numeric(10,4) not null,
  ai_probability numeric(7,3),
  fair_odds numeric(10,4),
  edge_pp numeric(9,3),
  expected_value_pct numeric(9,3),
  reliability_score numeric(7,3),
  daily_score numeric(7,3),
  stake_pln numeric(12,2) not null default 10.00,
  status text not null default 'pending' check (status in ('pending','win','loss','void')),
  actual_home_goals integer,
  actual_away_goals integer,
  profit_pln numeric(12,2) not null default 0.00,
  model_version text not null default 'V368',
  published_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  settled_at timestamptz,
  settlement_source text,
  display_snapshot jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_fm_ai_system_picks_v368_fixture_date
  on public.fm_ai_system_picks_v368(fixture_date desc);
create index if not exists idx_fm_ai_system_picks_v368_status
  on public.fm_ai_system_picks_v368(status, fixture_date);
create index if not exists idx_fm_ai_system_picks_v368_league
  on public.fm_ai_system_picks_v368(league);
create index if not exists idx_fm_ai_system_picks_v368_market
  on public.fm_ai_system_picks_v368(market_key);
create index if not exists idx_fm_ai_system_picks_v368_day_key
  on public.fm_ai_system_picks_v368(day_key desc);

alter table public.fm_ai_system_picks_v368 enable row level security;

comment on table public.fm_ai_system_picks_v368 is
  'Frozen pre-match FM AI paper picks. 10 PLN flat stake. Service-role only. Used to measure real forward performance without cherry-picking.';
