-- Bet+AI WERSJA 300 — PRODUCTION PLATFORM 2.0 ALL-IN
-- V281 Web Push / Notifications 2.0
-- V282–V284 Push routing, delivery audit, notification preferences
-- V285 Historical Match Explorer
-- V286 Prediction Timeline Viewer
-- V287 Model Comparison Studio
-- V288 Data Coverage Dashboard
-- V289 Safe Backfill Engine
-- V290 Data Retention & Cleanup
-- V291 Error Recovery / Retry Queue
-- V292 Admin Control Center
-- V293 Feature Flags
-- V294 A/B Testing
-- V295 User Analytics
-- V296 Responsible Decision Layer
-- V297 Export Center
-- V298 Backup & Restore
-- V299 System Health Score
-- V300 Master Operations Dashboard + SYSTEM SAFE MODE
--
-- URUCHOM RAZ: Supabase -> SQL Editor -> Run.
-- Zakłada wcześniejsze V280. Migracja jest idempotentna i nie usuwa historii prognoz.

-- ============================================================
-- V292 / V293 / V300 — SYSTEM SETTINGS + FEATURE FLAGS + SAFE MODE
-- ============================================================
create table if not exists public.match_system_settings_v300 (
  settings_key text primary key,
  safe_mode boolean not null default false,
  safe_mode_reason text not null default '',
  read_only_mode boolean not null default false,
  auto_jobs_enabled boolean not null default true,
  backfill_enabled boolean not null default false,
  analytics_enabled boolean not null default true,
  push_enabled boolean not null default true,
  config jsonb not null default '{}'::jsonb,
  updated_by uuid null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.match_system_settings_v300 (
  settings_key, safe_mode, read_only_mode, auto_jobs_enabled, backfill_enabled, analytics_enabled, push_enabled
) values (
  'football-main', false, false, true, false, true, true
) on conflict (settings_key) do nothing;

create table if not exists public.match_feature_flags_v300 (
  flag_key text primary key,
  enabled boolean not null default true,
  rollout_pct integer not null default 100 check (rollout_pct between 0 and 100),
  admin_only boolean not null default false,
  description text not null default '',
  config jsonb not null default '{}'::jsonb,
  updated_by uuid null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.match_feature_flags_v300(flag_key,enabled,rollout_pct,admin_only,description) values
  ('historical_explorer',true,100,false,'V285 historical prediction explorer'),
  ('timeline_viewer',true,100,false,'V286 prediction timeline'),
  ('model_comparison',true,100,false,'V287 model comparison studio'),
  ('data_coverage',true,100,false,'V288 coverage dashboard'),
  ('web_push',true,100,false,'V281-V284 web push'),
  ('admin_control_center',true,100,true,'V292 admin controls'),
  ('ab_testing',true,100,false,'V294 A/B framework'),
  ('user_analytics',true,100,false,'V295 privacy-light product analytics'),
  ('export_center',true,100,false,'V297 export center'),
  ('system_health',true,100,false,'V299-V300 system health dashboard')
on conflict (flag_key) do nothing;

-- V292 runtime controls for jobs / markets / leagues / modules.
create table if not exists public.match_runtime_controls_v300 (
  control_type text not null,
  control_key text not null,
  enabled boolean not null default true,
  config jsonb not null default '{}'::jsonb,
  updated_by uuid null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (control_type, control_key),
  constraint match_runtime_controls_v300_type_check check (control_type in ('job','market','league','module'))
);

insert into public.match_runtime_controls_v300(control_type,control_key,enabled) values
  ('job','settlement',true),('job','odds_snapshot',true),('job','model_rebuild',true),('job','anomaly_scan',true),
  ('job','prematch_scan',true),('job','referee_rebuild',true),('job','daily_digest',true),('job','push_dispatch',true),
  ('job','backfill',true),('job','cleanup',true),('job','retry_worker',true),('job','health_snapshot',true),
  ('market','oneXTwo',true),('market','over15',true),('market','over25',true),('market','over35',true),('market','btts',true)
on conflict (control_type,control_key) do nothing;


-- ============================================================
-- V281–V284 — WEB PUSH
-- Subscription belongs to authenticated Supabase user.
-- Full subscription JSON is stored server-side only.
-- ============================================================
create table if not exists public.match_push_subscriptions_v300 (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  endpoint text not null unique,
  subscription jsonb not null,
  user_agent text null,
  active boolean not null default true,
  last_success_at timestamptz null,
  last_error_at timestamptz null,
  last_error text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_match_push_subscriptions_v300_user
  on public.match_push_subscriptions_v300(user_id, active, updated_at desc);

create table if not exists public.match_push_delivery_v300 (
  id bigint generated by default as identity primary key,
  alert_id bigint not null,
  subscription_id bigint not null,
  status text not null default 'pending',
  attempts integer not null default 0,
  last_status_code integer null,
  last_error text null,
  sent_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint match_push_delivery_v300_unique unique (alert_id, subscription_id),
  constraint match_push_delivery_v300_status_check check (status in ('pending','sent','retry','dead'))
);

create index if not exists idx_match_push_delivery_v300_status
  on public.match_push_delivery_v300(status, updated_at asc);


create table if not exists public.match_system_alerts_v300 (
  id bigint generated by default as identity primary key,
  alert_key text not null unique,
  alert_type text not null,
  severity text not null default 'warning',
  title text not null default '',
  message text not null default '',
  detail jsonb not null default '{}'::jsonb,
  resolved_at timestamptz null,
  created_at timestamptz not null default now(),
  constraint match_system_alerts_v300_severity_check check (severity in ('info','warning','critical'))
);

create index if not exists idx_match_system_alerts_v300_open
  on public.match_system_alerts_v300(resolved_at, created_at desc);

-- ============================================================
-- V289 — SAFE BACKFILL QUEUE
-- API backfill is disabled by default and requires both DB setting + ENV opt-in.
-- ============================================================
create table if not exists public.match_backfill_queue_v300 (
  id bigint generated by default as identity primary key,
  fixture_id text not null,
  backfill_type text not null,
  priority integer not null default 50,
  status text not null default 'pending',
  attempts integer not null default 0,
  payload jsonb not null default '{}'::jsonb,
  last_error text null,
  next_attempt_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint match_backfill_queue_v300_unique unique (fixture_id, backfill_type),
  constraint match_backfill_queue_v300_status_check check (status in ('pending','processing','done','retry','dead'))
);

create index if not exists idx_match_backfill_queue_v300_work
  on public.match_backfill_queue_v300(status, priority desc, next_attempt_at asc, created_at asc);

-- ============================================================
-- V291 — ERROR RECOVERY / RETRY QUEUE
-- ============================================================
create table if not exists public.match_retry_queue_v300 (
  id bigint generated by default as identity primary key,
  job_key text not null,
  target_function text not null,
  payload jsonb not null default '{}'::jsonb,
  status text not null default 'pending',
  attempts integer not null default 0,
  max_attempts integer not null default 4,
  next_attempt_at timestamptz not null default now(),
  last_error text null,
  source_run_id bigint null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint match_retry_queue_v300_job_unique unique (job_key),
  constraint match_retry_queue_v300_status_check check (status in ('pending','running','retry','done','dead'))
);

create index if not exists idx_match_retry_queue_v300_work
  on public.match_retry_queue_v300(status, next_attempt_at asc);

-- ============================================================
-- V294 — A/B TESTING
-- ============================================================
create table if not exists public.match_ab_experiments_v300 (
  experiment_key text primary key,
  enabled boolean not null default false,
  variants jsonb not null default '["control","variant"]'::jsonb,
  allocation jsonb not null default '{"control":50,"variant":50}'::jsonb,
  description text not null default '',
  config jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.match_ab_experiments_v300(experiment_key,enabled,variants,allocation,description)
values ('prediction_explanation_layout',false,'["control","compact"]'::jsonb,'{"control":50,"compact":50}'::jsonb,'V294 explanation layout test')
on conflict (experiment_key) do nothing;

create table if not exists public.match_ab_assignments_v300 (
  experiment_key text not null,
  subject_key text not null,
  user_id uuid null,
  variant text not null,
  assigned_at timestamptz not null default now(),
  primary key (experiment_key, subject_key)
);

-- ============================================================
-- V295 — PRIVACY-LIGHT PRODUCT ANALYTICS
-- No raw IP is stored. Server may keep only coarse event context.
-- ============================================================
create table if not exists public.match_user_events_v300 (
  id bigint generated by default as identity primary key,
  user_id uuid null,
  session_key text null,
  event_name text not null,
  fixture_id text null,
  league text null,
  feature_key text null,
  variant text null,
  detail jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_match_user_events_v300_time
  on public.match_user_events_v300(created_at desc);
create index if not exists idx_match_user_events_v300_event
  on public.match_user_events_v300(event_name, created_at desc);
create index if not exists idx_match_user_events_v300_fixture
  on public.match_user_events_v300(fixture_id, created_at desc);

-- ============================================================
-- V298 — CONFIG BACKUP / RESTORE
-- Stores configuration only; never copies user passwords or auth secrets.
-- ============================================================
create table if not exists public.match_config_backups_v300 (
  id bigint generated by default as identity primary key,
  label text not null default 'Bet+AI config backup',
  created_by uuid null,
  snapshot jsonb not null,
  snapshot_hash text null,
  restored_at timestamptz null,
  restored_by uuid null,
  created_at timestamptz not null default now()
);

create index if not exists idx_match_config_backups_v300_time
  on public.match_config_backups_v300(created_at desc);

-- ============================================================
-- V299 / V300 — SYSTEM HEALTH SNAPSHOTS
-- ============================================================
create table if not exists public.match_system_health_v300 (
  id bigint generated by default as identity primary key,
  health_key text not null default 'football-main',
  score integer not null default 0 check (score between 0 and 100),
  status text not null default 'PENDING',
  components jsonb not null default '{}'::jsonb,
  counters jsonb not null default '{}'::jsonb,
  alerts jsonb not null default '[]'::jsonb,
  measured_at timestamptz not null default now()
);

create index if not exists idx_match_system_health_v300_latest
  on public.match_system_health_v300(health_key, measured_at desc);

-- ============================================================
-- V290 — CLEANUP AUDIT
-- ============================================================
create table if not exists public.match_cleanup_runs_v300 (
  id bigint generated by default as identity primary key,
  status text not null default 'ok',
  deleted jsonb not null default '{}'::jsonb,
  note text not null default '',
  created_at timestamptz not null default now(),
  constraint match_cleanup_runs_v300_status_check check (status in ('ok','partial','error','skipped'))
);

-- ============================================================
-- V203/V210 telemetry — add V300 job types.
-- ============================================================
alter table public.match_ops_runs drop constraint if exists match_ops_runs_type_check;
alter table public.match_ops_runs add constraint match_ops_runs_type_check
  check (run_type in (
    'odds_snapshot','settlement','model_rebuild','anomaly_scan','replay_read','performance_explorer','api_health',
    'prematch_scan','referee_rebuild','daily_digest',
    'push_dispatch','backfill','cleanup','retry_worker','health_snapshot','config_backup','config_restore'
  ));

-- ============================================================
-- RLS — backend-only tables. Service Role is used by Netlify Functions.
-- No anonymous policies are intentionally created.
-- ============================================================
alter table public.match_system_settings_v300 enable row level security;
alter table public.match_feature_flags_v300 enable row level security;
alter table public.match_runtime_controls_v300 enable row level security;
alter table public.match_push_subscriptions_v300 enable row level security;
alter table public.match_push_delivery_v300 enable row level security;
alter table public.match_system_alerts_v300 enable row level security;
alter table public.match_backfill_queue_v300 enable row level security;
alter table public.match_retry_queue_v300 enable row level security;
alter table public.match_ab_experiments_v300 enable row level security;
alter table public.match_ab_assignments_v300 enable row level security;
alter table public.match_user_events_v300 enable row level security;
alter table public.match_config_backups_v300 enable row level security;
alter table public.match_system_health_v300 enable row level security;
alter table public.match_cleanup_runs_v300 enable row level security;

comment on table public.match_system_settings_v300 is
  'V292/V300 global Production Platform controls, including SYSTEM SAFE MODE.';
comment on table public.match_runtime_controls_v300 is
  'V292 per-job, per-market and per-league runtime switches used by Admin Control Center.';
comment on table public.match_push_subscriptions_v300 is
  'V281-V284 authenticated Web Push subscriptions; VAPID private key remains only in Netlify ENV.';
comment on table public.match_system_alerts_v300 is
  'V281-V284 system/API health alerts eligible for admin Web Push.';
comment on table public.match_user_events_v300 is
  'V295 privacy-light product events without raw IP storage.';
comment on table public.match_config_backups_v300 is
  'V298 configuration-only backups; no passwords or Supabase auth secrets.';
comment on table public.match_system_health_v300 is
  'V299/V300 immutable system-health snapshots used by Master Operations Dashboard.';

-- ============================================================
-- KONTROLA PO WDROŻENIU
-- ============================================================
-- select * from public.match_system_settings_v300 where settings_key='football-main';
-- select flag_key,enabled,rollout_pct,admin_only from public.match_feature_flags_v300 order by flag_key;
-- select status,count(*) from public.match_retry_queue_v300 group by status;
-- select status,count(*) from public.match_backfill_queue_v300 group by status;
-- select score,status,measured_at from public.match_system_health_v300 order by measured_at desc limit 10;
-- select count(*) from public.match_push_subscriptions_v300 where active=true;
--
-- SYSTEM SAFE MODE:
-- Admin Control Center ustawia safe_mode=true/read_only_mode=true/auto_jobs_enabled=false.
-- Match-specific scheduled jobs V137/V201/V204/V206/V261+/V289+ sprawdzają ten stan przed pracą.
