-- Bet+AI WERSJA 260 — MATCH CONTEXT + MARKET + SCENARIO + MEMORY + AI COMMAND CENTER ALL-IN
-- V212–V220 Match Context Engine 4.0
-- V221–V230 Market Intelligence 3.0
-- V231–V238 What-If / Scenario Lab
-- V239–V245 AI Match Report (structured-data only)
-- V246–V252 Similar Match Memory
-- V253–V260 AI Command Center
--
-- URUCHOM RAZ w Supabase -> SQL Editor -> Run.
-- Zakłada wcześniejsze V211. Migracja jest idempotentna i nie usuwa danych.
-- V260 nie wymaga dodatkowych requestów API-Football dla Context/Memory/Command Center.

-- ============================================================
-- V212–V220 — TEAM CONTEXT REGISTRY
-- Przechowuje wyłącznie ostatni PRE-MATCH kontekst śledzonej drużyny.
-- Służy do realnego porównania poprzedniego XI / GK / trenera.
-- ============================================================
create table if not exists public.match_team_context_registry_v260 (
  team_id text primary key,
  team_name text not null default '',
  league text not null default '',
  season_key text null,
  current_coach text null,
  previous_coach text null,
  coach_changed_at timestamptz null,
  last_lineup jsonb not null default '[]'::jsonb,
  last_goalkeeper text null,
  last_fixture_id text null,
  last_fixture_date timestamptz null,
  tracked_matches integer not null default 0,
  first_seen_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_match_team_context_v260_updated
  on public.match_team_context_registry_v260(updated_at desc);

create index if not exists idx_match_team_context_v260_league
  on public.match_team_context_registry_v260(league, updated_at desc);

create table if not exists public.match_context_events_v260 (
  id bigint generated by default as identity primary key,
  fixture_id text not null,
  team_id text not null,
  side text not null default '',
  event_type text not null,
  severity text not null default 'info',
  detail jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint match_context_events_v260_side_check
    check (side in ('home','away','match','')),
  constraint match_context_events_v260_severity_check
    check (severity in ('info','warning','critical'))
);

create index if not exists idx_match_context_events_v260_fixture
  on public.match_context_events_v260(fixture_id, created_at desc);

create index if not exists idx_match_context_events_v260_team
  on public.match_context_events_v260(team_id, created_at desc);

create index if not exists idx_match_context_events_v260_type
  on public.match_context_events_v260(event_type, severity, created_at desc);

create table if not exists public.match_context_snapshots_v220 (
  fixture_id text primary key,
  fixture_date timestamptz null,
  home_team text not null default '',
  away_team text not null default '',
  league text not null default '',
  context jsonb not null default '{}'::jsonb,
  base_xg jsonb not null default '{}'::jsonb,
  adjusted_xg jsonb not null default '{}'::jsonb,
  shock_level text not null default 'NONE',
  captured_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_match_context_snapshots_v220_date
  on public.match_context_snapshots_v220(fixture_date desc);

create index if not exists idx_match_context_snapshots_v220_shock
  on public.match_context_snapshots_v220(shock_level, fixture_date desc);

-- ============================================================
-- V246–V252 — SIMILAR MATCH MEMORY CACHE
-- Wynik podobieństwa jest zawsze liczony tylko z WCZEŚNIEJ rozliczonych meczów.
-- Cache ma TTL i nie jest źródłem treningowym.
-- ============================================================
create table if not exists public.match_similarity_cache_v252 (
  fingerprint text primary key,
  fixture_id text not null,
  model_version text not null default 'BETAI_FORECAST_V260',
  signature jsonb not null default '{}'::jsonb,
  result jsonb not null default '{}'::jsonb,
  expires_at timestamptz not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_match_similarity_cache_v252_fixture
  on public.match_similarity_cache_v252(fixture_id, updated_at desc);

create index if not exists idx_match_similarity_cache_v252_expiry
  on public.match_similarity_cache_v252(expires_at);

-- ============================================================
-- V253–V260 — AI COMMAND CENTER DAILY SNAPSHOT
-- Dashboard może być odtworzony bez ponownego liczenia całego dnia.
-- ============================================================
create table if not exists public.match_command_center_daily_v260 (
  summary_date date primary key,
  summary jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_match_command_center_v260_updated
  on public.match_command_center_daily_v260(updated_at desc);

-- ============================================================
-- INDEXES POD MEMORY / CONTEXT / COMMAND CENTER
-- ============================================================
create index if not exists idx_match_prediction_snapshots_v260_memory
  on public.match_prediction_snapshots(fixture_date desc, league, data_quality)
  where actual_home_goals is not null and actual_away_goals is not null;

create index if not exists idx_match_prediction_snapshots_v260_today
  on public.match_prediction_snapshots(fixture_date desc, model_version);

create index if not exists idx_match_simulator_snapshots_v260_today
  on public.match_simulator_snapshots(fixture_date desc, eligible, quality_score);

-- ============================================================
-- RLS — backend only.
-- Netlify Functions używają SUPABASE_SERVICE_ROLE_KEY.
-- Brak publicznych policies jest celowy.
-- ============================================================
alter table public.match_team_context_registry_v260 enable row level security;
alter table public.match_context_events_v260 enable row level security;
alter table public.match_context_snapshots_v220 enable row level security;
alter table public.match_similarity_cache_v252 enable row level security;
alter table public.match_command_center_daily_v260 enable row level security;

comment on table public.match_team_context_registry_v260 is
  'V212-V220: previous tracked PRE-MATCH XI/GK/coach context for real continuity and change detection.';

comment on table public.match_context_events_v260 is
  'V212-V220: manager/GK/lineup-rotation context change audit events.';

comment on table public.match_context_snapshots_v220 is
  'V220: frozen context-adjusted xG inputs attached to the selected pre-match forecast.';

comment on table public.match_similarity_cache_v252 is
  'V246-V252: TTL cache for Similar Match Memory; source history must be settled and earlier than current kickoff.';

comment on table public.match_command_center_daily_v260 is
  'V253-V260: daily Bet+AI command-center production summary.';

-- ============================================================
-- KONTROLA PO WDROŻENIU
-- ============================================================
-- select count(*) from public.match_team_context_registry_v260;
-- select event_type,severity,count(*) from public.match_context_events_v260 group by event_type,severity;
-- select shock_level,count(*) from public.match_context_snapshots_v220 group by shock_level;
-- select count(*) from public.match_similarity_cache_v252 where expires_at > now();
-- select summary_date, summary->>'health' as health, updated_at
-- from public.match_command_center_daily_v260
-- order by summary_date desc limit 7;
--
-- WAŻNE:
-- 1) Pierwszy śledzony mecz drużyny ma XI/GK/manager status TRACKING.
-- 2) Od następnego zapisanego PRE-MATCH meczu można realnie policzyć continuity/change.
-- 3) V217 nie wymyśla danych o rożnych/wolnych. Bez wiarygodnego źródła pokazuje NO_RELIABLE_DATA
--    i ma dokładnie 0 wpływu na xG.
-- 4) Scenario Lab jest testem wrażliwości, a nie twierdzeniem, że zawodnik faktycznie nie zagra.
-- 5) Similar Match Memory nigdy nie używa bieżącego ani przyszłego fixture.
