-- Bet+AI WERSJA 280 — LIVE PRE-MATCH INTELLIGENCE + ALERTS / USER WORKFLOW ALL-IN
-- V261 Lineup Confirmation Engine
-- V262 Last-Minute Change Detector
-- V263 Pre-Match Re-Score
-- V264 Probability Delta
-- V265 Weather Context
-- V266 Referee Context
-- V267 Travel & Rest Intelligence
-- V268 Confidence Change Alert
-- V269 Decision Change Log
-- V270 Live Pre-Match Control Center
-- V271 Watchlist
-- V272 Alert Rules
-- V273 Change Alerts
-- V274 Saved Analysis
-- V275 Before vs After Lineups
-- V276 Decision History
-- V277 Daily Digest
-- V278 Alert Inbox
-- V279 User Workflow Dashboard
-- V280 ALL-IN Control Center
--
-- URUCHOM RAZ: Supabase -> SQL Editor -> Run.
-- Zakłada wcześniejsze V260. Migracja jest idempotentna i nie usuwa danych użytkownika.

-- ============================================================
-- V267 — rozszerzenie rejestru drużyn o bezpieczną bazę lokalizacji
-- ============================================================
alter table public.match_team_context_registry_v260
  add column if not exists home_base_city text null;
alter table public.match_team_context_registry_v260
  add column if not exists home_base_lat double precision null;
alter table public.match_team_context_registry_v260
  add column if not exists home_base_lon double precision null;
alter table public.match_team_context_registry_v260
  add column if not exists home_base_geocoded_at timestamptz null;

create table if not exists public.match_geo_cache_v280 (
  location_key text primary key,
  query_text text not null,
  latitude double precision null,
  longitude double precision null,
  country text null,
  region text null,
  source text not null default 'Open-Meteo Geocoding',
  status text not null default 'ok',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint match_geo_cache_v280_status_check check (status in ('ok','not_found','error'))
);

-- ============================================================
-- V261–V270 — bieżący stan LIVE PRE-MATCH
-- ============================================================
create table if not exists public.match_prematch_state_v280 (
  fixture_id text primary key,
  fixture_date timestamptz null,
  home_team text not null default '',
  away_team text not null default '',
  league text not null default '',
  status text not null default 'TRACKING',
  official_lineups boolean not null default false,
  official_sides integer not null default 0,
  lineup_payload jsonb not null default '{}'::jsonb,
  injuries_payload jsonb not null default '{}'::jsonb,
  weather_payload jsonb not null default '{}'::jsonb,
  referee_payload jsonb not null default '{}'::jsonb,
  travel_payload jsonb not null default '{}'::jsonb,
  market_payload jsonb not null default '{}'::jsonb,
  rescore jsonb not null default '{}'::jsonb,
  probability_delta jsonb not null default '{}'::jsonb,
  confidence_delta jsonb not null default '{}'::jsonb,
  decision_before text null,
  decision_after text null,
  review_required boolean not null default false,
  flags jsonb not null default '[]'::jsonb,
  last_window text null,
  last_checked_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint match_prematch_state_v280_status_check check (status in ('TRACKING','READY','REVIEW','BLOCKED','STARTED','FINISHED')),
  constraint match_prematch_state_v280_official_sides_check check (official_sides between 0 and 2)
);

create index if not exists idx_match_prematch_state_v280_date
  on public.match_prematch_state_v280(fixture_date asc);
create index if not exists idx_match_prematch_state_v280_review
  on public.match_prematch_state_v280(review_required, fixture_date asc);
create index if not exists idx_match_prematch_state_v280_updated
  on public.match_prematch_state_v280(updated_at desc);

create table if not exists public.match_prematch_events_v280 (
  id bigint generated by default as identity primary key,
  event_key text not null unique,
  fixture_id text not null,
  event_type text not null,
  severity text not null default 'info',
  source_window text null,
  detail jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint match_prematch_events_v280_severity_check check (severity in ('info','warning','critical'))
);

create index if not exists idx_match_prematch_events_v280_fixture
  on public.match_prematch_events_v280(fixture_id, created_at desc);
create index if not exists idx_match_prematch_events_v280_type
  on public.match_prematch_events_v280(event_type, severity, created_at desc);

create table if not exists public.match_decision_history_v280 (
  id bigint generated by default as identity primary key,
  fixture_id text not null,
  captured_at timestamptz not null default now(),
  source_window text null,
  decision text not null default 'WATCH',
  confidence integer null,
  market_key text null,
  probability numeric(7,3) null,
  xg jsonb not null default '{}'::jsonb,
  reason text not null default '',
  state_snapshot jsonb not null default '{}'::jsonb,
  constraint match_decision_history_v280_decision_check check (decision in ('BET','WATCH','NO_BET'))
);

create index if not exists idx_match_decision_history_v280_fixture
  on public.match_decision_history_v280(fixture_id, captured_at desc);

-- ============================================================
-- V266 — sędzia: próbki i profil historyczny
-- ============================================================
create table if not exists public.match_referee_samples_v280 (
  fixture_id text primary key,
  referee_key text not null,
  referee_name text not null,
  fixture_date timestamptz null,
  league text not null default '',
  yellow_cards integer not null default 0,
  red_cards integer not null default 0,
  fouls integer not null default 0,
  penalties integer not null default 0,
  total_goals integer not null default 0,
  captured_at timestamptz not null default now()
);

create index if not exists idx_match_referee_samples_v280_ref
  on public.match_referee_samples_v280(referee_key, fixture_date desc);

create table if not exists public.match_referee_profiles_v280 (
  referee_key text primary key,
  referee_name text not null,
  sample_size integer not null default 0,
  avg_yellow double precision not null default 0,
  avg_red double precision not null default 0,
  avg_fouls double precision not null default 0,
  avg_penalties double precision not null default 0,
  avg_goals double precision not null default 0,
  last_fixture_date timestamptz null,
  updated_at timestamptz not null default now()
);

-- ============================================================
-- V271–V280 — USER WORKFLOW / WATCHLIST / ALERTS
-- Backend weryfikuje token Supabase Auth przed odczytem/zapisem.
-- ============================================================
create table if not exists public.match_user_watchlist_v280 (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  fixture_id text not null,
  fixture_date timestamptz null,
  home_team text not null default '',
  away_team text not null default '',
  league text not null default '',
  enabled boolean not null default true,
  rules jsonb not null default '{"lineup_confirmed":true,"major_change":true,"decision_change":true,"confidence_drop":true,"probability_delta_pp":4,"market_move_pp":2}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint match_user_watchlist_v280_unique unique (user_id, fixture_id)
);

create index if not exists idx_match_user_watchlist_v280_user
  on public.match_user_watchlist_v280(user_id, enabled, fixture_date asc);
create index if not exists idx_match_user_watchlist_v280_fixture
  on public.match_user_watchlist_v280(fixture_id, enabled);

create table if not exists public.match_user_alerts_v280 (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  fixture_id text not null,
  alert_key text not null,
  alert_type text not null,
  severity text not null default 'info',
  title text not null default '',
  message text not null default '',
  detail jsonb not null default '{}'::jsonb,
  read_at timestamptz null,
  created_at timestamptz not null default now(),
  constraint match_user_alerts_v280_unique unique (user_id, alert_key),
  constraint match_user_alerts_v280_severity_check check (severity in ('info','warning','critical'))
);

create index if not exists idx_match_user_alerts_v280_user
  on public.match_user_alerts_v280(user_id, read_at, created_at desc);
create index if not exists idx_match_user_alerts_v280_fixture
  on public.match_user_alerts_v280(fixture_id, created_at desc);

create table if not exists public.match_saved_analysis_v280 (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  fixture_id text not null,
  label text not null default 'Pre-match analysis',
  snapshot jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_match_saved_analysis_v280_user
  on public.match_saved_analysis_v280(user_id, created_at desc);
create index if not exists idx_match_saved_analysis_v280_fixture
  on public.match_saved_analysis_v280(user_id, fixture_id, created_at desc);

create table if not exists public.match_user_daily_digest_v280 (
  user_id uuid not null,
  digest_date date not null,
  summary jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (user_id, digest_date)
);

-- ============================================================
-- V203/V210 telemetry — rozszerzenie listy typów runów
-- ============================================================
alter table public.match_ops_runs drop constraint if exists match_ops_runs_type_check;
alter table public.match_ops_runs add constraint match_ops_runs_type_check
  check (run_type in (
    'odds_snapshot','settlement','model_rebuild','anomaly_scan','replay_read','performance_explorer','api_health',
    'prematch_scan','referee_rebuild','daily_digest'
  ));

-- ============================================================
-- RLS — tabele backend-only, brak anonimowych policies jest celowy.
-- ============================================================
alter table public.match_geo_cache_v280 enable row level security;
alter table public.match_prematch_state_v280 enable row level security;
alter table public.match_prematch_events_v280 enable row level security;
alter table public.match_decision_history_v280 enable row level security;
alter table public.match_referee_samples_v280 enable row level security;
alter table public.match_referee_profiles_v280 enable row level security;
alter table public.match_user_watchlist_v280 enable row level security;
alter table public.match_user_alerts_v280 enable row level security;
alter table public.match_saved_analysis_v280 enable row level security;
alter table public.match_user_daily_digest_v280 enable row level security;

comment on table public.match_prematch_state_v280 is
  'V261-V270: live pre-match state built only from pre-kickoff information, including confirmed XI, deltas, weather/referee/travel and re-score.';
comment on table public.match_decision_history_v280 is
  'V269/V276: chronological BET/WATCH/NO_BET changes before kickoff.';
comment on table public.match_user_watchlist_v280 is
  'V271-V273: authenticated user watchlist and alert rules.';
comment on table public.match_saved_analysis_v280 is
  'V274/V275: user-saved immutable snapshots of before/after pre-match analysis.';

-- KONTROLA PO WDROŻENIU:
-- select count(*) from public.match_prematch_state_v280;
-- select event_type,severity,count(*) from public.match_prematch_events_v280 group by event_type,severity;
-- select referee_name,sample_size,avg_yellow,avg_fouls,avg_goals from public.match_referee_profiles_v280 order by sample_size desc limit 20;
-- select count(*) from public.match_user_watchlist_v280 where enabled=true;
-- select count(*) from public.match_user_alerts_v280 where read_at is null;
