-- Bet+AI WERSJA 200 — MODEL RELIABILITY + DATA INTEGRITY + DATA SCIENCE ALL-IN
-- V181 Anti Data Leakage Guard
-- V182 Prediction Freeze Ledger
-- V183 Fixture / Settlement Integrity
-- V184 Season Boundary Engine
-- V185 Odds History & CLV 2.0
-- V186 Overfitting Guard
-- V187 Probability Stability
-- V188 Abstention Engine
-- V189 Decision Quality Lab
-- V190 Reliability Control Center
-- V191 Log Loss
-- V192 Isotonic Calibration
-- V193 Platt Calibration
-- V194 Bayesian League Priors
-- V195 Hierarchical Shrinkage
-- V196 Season Decay
-- V197 Ensemble Stacking
-- V198 Out-of-Sample Walk-Forward
-- V199 Bootstrap Confidence
-- V200 Automatic Model Selection
--
-- URUCHOM RAZ: Supabase -> SQL Editor -> Run.
-- Zakłada wdrożone V166/V180. Wszystkie polecenia poniżej są idempotentne.
-- Nie dodaje requestów API-Football do generowania prognozy.

-- ============================================================
-- V182 — APPEND-ONLY PREDICTION FREEZE LEDGER
-- ============================================================
create table if not exists public.match_prediction_freeze_ledger (
  id bigint generated by default as identity primary key,
  fixture_id text not null,
  fixture_date timestamptz null,
  home_team text not null default '',
  away_team text not null default '',
  league text not null default '',
  country text not null default '',
  season_key text null,
  captured_at timestamptz not null default now(),
  generated_at timestamptz null,
  input_cutoff_at timestamptz not null default now(),
  model_version text not null,
  active_model text not null default 'champion',
  data_quality integer not null default 0 check (data_quality between 0 and 100),
  freeze_hash text not null unique,
  selected_for_backtest boolean not null default false,
  selection_reason text not null default '',
  forecast jsonb not null default '{}'::jsonb,
  integrity jsonb not null default '{}'::jsonb
);

create index if not exists idx_match_prediction_freeze_fixture_time
  on public.match_prediction_freeze_ledger(fixture_id, captured_at desc);
create index if not exists idx_match_prediction_freeze_selected
  on public.match_prediction_freeze_ledger(selected_for_backtest, fixture_date desc);
create index if not exists idx_match_prediction_freeze_model
  on public.match_prediction_freeze_ledger(model_version, captured_at desc);
create index if not exists idx_match_prediction_freeze_season
  on public.match_prediction_freeze_ledger(season_key, league, captured_at desc);

-- Freeze Ledger jest niezmienny po INSERT. Service role nadal może dodawać kolejne wpisy,
-- ale żaden istniejący snapshot nie może zostać przepisany ani usunięty.
create or replace function public.betai_prevent_freeze_mutation_v182()
returns trigger
language plpgsql
as $$
begin
  raise exception 'Bet+AI Prediction Freeze Ledger is append-only';
end;
$$;

drop trigger if exists trg_betai_freeze_no_update_v182 on public.match_prediction_freeze_ledger;
create trigger trg_betai_freeze_no_update_v182
before update on public.match_prediction_freeze_ledger
for each row execute function public.betai_prevent_freeze_mutation_v182();

drop trigger if exists trg_betai_freeze_no_delete_v182 on public.match_prediction_freeze_ledger;
create trigger trg_betai_freeze_no_delete_v182
before delete on public.match_prediction_freeze_ledger
for each row execute function public.betai_prevent_freeze_mutation_v182();

-- ============================================================
-- V181 / V183 / V184 — FIXTURE & DATA INTEGRITY
-- ============================================================
create table if not exists public.match_fixture_integrity (
  fixture_id text primary key,
  canonical_fixture_date timestamptz null,
  home_team text not null default '',
  away_team text not null default '',
  league text not null default '',
  country text not null default '',
  duplicate_key text null,
  season_key text null,
  integrity_status text not null default 'clear',
  leakage_status text not null default 'clear',
  freeze_count integer not null default 0,
  settlement_count integer not null default 0,
  metadata jsonb not null default '{}'::jsonb,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint match_fixture_integrity_status_check check (integrity_status in ('clear','review','blocked')),
  constraint match_fixture_leakage_status_check check (leakage_status in ('clear','blocked','review'))
);

create index if not exists idx_match_fixture_integrity_duplicate
  on public.match_fixture_integrity(duplicate_key);
create index if not exists idx_match_fixture_integrity_season_league
  on public.match_fixture_integrity(season_key, league);
create index if not exists idx_match_fixture_integrity_status
  on public.match_fixture_integrity(integrity_status, leakage_status, updated_at desc);

create table if not exists public.match_integrity_events (
  id bigint generated by default as identity primary key,
  fixture_id text not null,
  event_type text not null,
  severity text not null default 'info',
  detail jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint match_integrity_event_severity_check check (severity in ('info','warning','critical'))
);

create index if not exists idx_match_integrity_events_fixture
  on public.match_integrity_events(fixture_id, created_at desc);
create index if not exists idx_match_integrity_events_type
  on public.match_integrity_events(event_type, severity, created_at desc);

-- ============================================================
-- V191–V200 — DATA SCIENCE PROFILE REGISTRY
-- ============================================================
create table if not exists public.match_data_science_profiles (
  profile_key text primary key,
  model_version text not null default 'BETAI_PREDICTION_ENGINE_4_V200',
  profile_type text not null default 'market',
  league text null,
  market_key text null,
  season_key text null,
  method text not null default 'RAW',
  sample_size integer not null default 0,
  log_loss double precision null,
  brier double precision null,
  parameters jsonb not null default '{}'::jsonb,
  validation jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint match_data_science_profile_type_check check (profile_type in ('global','market','league','league_market','season')),
  constraint match_data_science_method_check check (method in ('RAW','PLATT','ISOTONIC','TEMPERATURE','STACK'))
);

create index if not exists idx_match_data_science_profiles_market
  on public.match_data_science_profiles(market_key, updated_at desc);
create index if not exists idx_match_data_science_profiles_league_market
  on public.match_data_science_profiles(league, market_key, updated_at desc);
create index if not exists idx_match_data_science_profiles_season
  on public.match_data_science_profiles(season_key, updated_at desc);

-- ============================================================
-- V185 — CLV 2.0 / ODDS HISTORY INDEXES
-- Existing V146 table is reused. "Closing" means last captured PRE-KICKOFF quote.
-- It is considered qualified CLV only when the capture is near kickoff.
-- ============================================================
create index if not exists idx_match_odds_history_v200_fixture_market_time
  on public.match_odds_history(fixture_id, market_key, bookmaker, captured_at desc);
create index if not exists idx_match_odds_history_v200_closing
  on public.match_odds_history(fixture_id, is_closing, captured_at desc)
  where is_closing = true;

-- Faster reliability/data-science reads from existing history.
create index if not exists idx_match_prediction_snapshots_v200_settled
  on public.match_prediction_snapshots(settled_at desc, league, model_version)
  where actual_home_goals is not null and actual_away_goals is not null;

create index if not exists idx_match_model_experiments_v200_oos
  on public.match_model_experiments(model_role, model_version, settled_at desc, league)
  where status = 'settled';

-- ============================================================
-- RLS: tables are backend-only. No public policies on purpose.
-- Netlify Functions use SUPABASE_SERVICE_ROLE_KEY.
-- ============================================================
alter table public.match_prediction_freeze_ledger enable row level security;
alter table public.match_fixture_integrity enable row level security;
alter table public.match_integrity_events enable row level security;
alter table public.match_data_science_profiles enable row level security;

comment on table public.match_prediction_freeze_ledger is
  'V182 append-only cryptographic ledger of every valid pre-match forecast capture.';
comment on table public.match_fixture_integrity is
  'V181/V183/V184 canonical fixture identity, season boundary and leakage/settlement integrity state.';
comment on table public.match_integrity_events is
  'V181-V190 audit events: leakage blocks, duplicates, reschedules and settlement integrity.';
comment on table public.match_data_science_profiles is
  'V191-V200 OOS-validated calibration/model-selection profiles (RAW/Platt/Isotonic/Temperature).';

-- ============================================================
-- KONTROLA PO WDROŻENIU
-- ============================================================
-- select count(*) as frozen_predictions from public.match_prediction_freeze_ledger;
--
-- select integrity_status, leakage_status, count(*)
-- from public.match_fixture_integrity
-- group by integrity_status, leakage_status;
--
-- select event_type, severity, count(*)
-- from public.match_integrity_events
-- group by event_type, severity
-- order by count(*) desc;
--
-- select profile_key, method, sample_size, log_loss, validation, updated_at
-- from public.match_data_science_profiles
-- order by updated_at desc
-- limit 30;
--
-- ZASADY V200:
-- 1) Prognoza po kickoffie jest blokowana przed zapisem do historii/backtestu.
-- 2) Każdy prawidłowy pre-match capture ma SHA-256 freeze_hash i nie można go edytować/usunąć.
-- 3) Platt/Isotonic/Temperature są aktywowane tylko po wymaganej próbce i poprawie log loss OOS >= 0.003.
-- 4) League profiles używają hierarchical shrinkage; małe próbki są ciągnięte do profilu globalnego.
-- 5) Historia ma exponential recency + season decay: current 1.00 / previous 0.55 / two seasons 0.25 / older 0.12.
-- 6) Wagi źródeł są ograniczone shrinkage/caps (Overfitting Guard).
-- 7) Abstention Engine może zwrócić NO PREDICTION zamiast wymuszać typ.
-- 8) Closing odds są tylko proxy ostatniego zapisanego kursu pre-kickoff; qualified CLV wymaga zapisu blisko kickoffu.
