-- Bet+AI v146 — ALL-IN Intelligence Upgrade
-- Calibration 2.0 / Odds History + CLV / Dynamic Weights / Daily Shortlist /
-- Explainable AI / Event Engine 2.0
--
-- Uruchom RAZ w Supabase -> SQL Editor.
-- Ta migracja NIE zwiększa liczby requestów API-Football.
-- Historia kursów zapisuje kursy, które aplikacja i tak już pobrała.

create table if not exists public.match_odds_history (
  id bigint generated by default as identity primary key,
  fixture_id text not null,
  fixture_date timestamptz null,
  market_key text not null,
  bookmaker text not null default '',
  odds numeric(10,4) not null check (odds > 1),
  model_probability numeric(7,3) null,
  fair_odds numeric(10,4) null,
  edge_pp numeric(8,3) null,
  expected_value_pct numeric(9,3) null,
  captured_at timestamptz not null default now(),
  is_closing boolean not null default false
);

create index if not exists idx_match_odds_history_fixture_market_time
  on public.match_odds_history(fixture_id, market_key, captured_at);

create index if not exists idx_match_odds_history_fixture_book_time
  on public.match_odds_history(fixture_id, bookmaker, captured_at);

create index if not exists idx_match_odds_history_closing
  on public.match_odds_history(fixture_id, is_closing)
  where is_closing = true;

alter table public.match_odds_history enable row level security;

comment on table public.match_odds_history is
  'Pre-match odds snapshots already seen by Bet+AI. Used for line movement and CLV without extra API requests.';

comment on column public.match_odds_history.is_closing is
  'Last stored quote before kickoff for a market/bookmaker when marked by settlement logic.';

-- Service role only. Do not create anon/authenticated policies.

-- Optional inspection:
-- select fixture_id, market_key, bookmaker, odds, captured_at, is_closing
-- from public.match_odds_history
-- order by captured_at desc
-- limit 100;
