-- Bet+AI v158 — Model Validation & Risk Lab
-- V153 Prediction Audit Trail / V154 Error Analysis / V155 Ensemble /
-- V156 Sharp Disagreement / V157 Portfolio Risk / V158 Model Control Center
-- Uruchom RAZ w Supabase -> SQL Editor.
--
-- Ta migracja NIE zwiększa liczby requestów API-Football.
-- Zapisuje i analizuje wyłącznie dane, które Bet+AI już pobrał przed meczem
-- oraz wyniki rozliczone później przez istniejący settlement engine.

create table if not exists public.match_prediction_audit (
  id bigint generated by default as identity primary key,
  fixture_id text not null,
  fixture_date timestamptz null,
  home_team text not null default '',
  away_team text not null default '',
  league text not null default '',
  country text not null default '',
  model_version text not null default 'BETAI_FORECAST_V158',
  audit_version text not null default 'BETAI_AUDIT_TRAIL_V1',
  signature text not null,
  data_quality integer not null default 0 check (data_quality >= 0 and data_quality <= 100),
  snapshot jsonb not null default '{}'::jsonb,
  sources jsonb not null default '{}'::jsonb,
  decision jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),

  constraint match_prediction_audit_fixture_signature_unique
    unique (fixture_id, signature)
);

create index if not exists idx_match_prediction_audit_fixture_date
  on public.match_prediction_audit(fixture_date desc);

create index if not exists idx_match_prediction_audit_model
  on public.match_prediction_audit(model_version, created_at desc);

create index if not exists idx_match_prediction_audit_fixture
  on public.match_prediction_audit(fixture_id, created_at desc);

alter table public.match_prediction_audit enable row level security;

comment on table public.match_prediction_audit is
  'V153 immutable-style audit snapshots: model version, inputs, sources, odds and final decision captured pre-match.';


create table if not exists public.match_prediction_error_analysis (
  id bigint generated by default as identity primary key,
  fixture_id text not null,
  fixture_date timestamptz null,
  home_team text not null default '',
  away_team text not null default '',
  league text not null default '',
  model_version text not null default 'BETAI_FORECAST_V158',
  market_key text not null,
  market_label text not null default '',
  predicted_probability numeric(7,3) null,
  decision text not null default 'BET',
  classification text not null default 'MARKET_MISREAD',
  severity text not null default 'low',
  summary text not null default '',
  factors jsonb not null default '[]'::jsonb,
  actual_home_goals integer null,
  actual_away_goals integer null,
  clv_pct numeric(9,3) null,
  created_at timestamptz not null default now(),

  constraint match_prediction_error_unique
    unique (fixture_id, market_key, model_version),

  constraint match_prediction_error_severity_check
    check (severity in ('low','medium','high'))
);

create index if not exists idx_match_prediction_error_analysis_created
  on public.match_prediction_error_analysis(created_at desc);

create index if not exists idx_match_prediction_error_analysis_classification
  on public.match_prediction_error_analysis(classification, created_at desc);

create index if not exists idx_match_prediction_error_analysis_league
  on public.match_prediction_error_analysis(league, created_at desc);

alter table public.match_prediction_error_analysis enable row level security;

comment on table public.match_prediction_error_analysis is
  'V154 automatic post-match analysis of losing validated BET signals: disagreement, drift, CLV, uncertainty, data quality and market misread.';

-- Brak publicznych policy jest celowy.
-- Netlify Functions używają SUPABASE_SERVICE_ROLE_KEY.

-- Kontrola po uruchomieniu:
-- select count(*) from public.match_prediction_audit;
-- select classification, count(*)
-- from public.match_prediction_error_analysis
-- group by classification
-- order by count(*) desc;
