'use strict'
const fs=require('fs'),path=require('path')
const root=__dirname
const read=p=>fs.readFileSync(path.join(root,p),'utf8')
const assert=(cond,msg)=>{if(!cond)throw new Error(msg)}
const sql=read('SUPABASE_RUN_ONCE_WERSJA_300_PRODUCTION_PLATFORM_2_ALL_IN.sql')
const toml=read('netlify.toml')
const pkg=JSON.parse(read('package.json'))
const view=read('src/ProductionPlatformV300.jsx')
const main=read('src/MatchSimulatorPreparationView.jsx')
const api=read('netlify/functions/match-platform-v300.js')
const safe=read('netlify/functions/_lib/system-safe-mode-v300.js')
const requiredTables=['match_system_settings_v300','match_feature_flags_v300','match_runtime_controls_v300','match_push_subscriptions_v300','match_push_delivery_v300','match_system_alerts_v300','match_backfill_queue_v300','match_retry_queue_v300','match_ab_experiments_v300','match_user_events_v300','match_config_backups_v300','match_system_health_v300','match_cleanup_runs_v300']
for(const t of requiredTables)assert(sql.includes(t),`SQL missing ${t}`)
for(const f of ['dispatch-match-push-v300','match-backfill-v300','match-cleanup-v300','match-retry-worker-v300','match-health-snapshot-v300'])assert(toml.includes(`[functions."${f}"]`),`Schedule missing ${f}`)
assert(pkg.dependencies?.['web-push']==='3.6.7','web-push pin missing')
assert(view.includes('Master Operations Dashboard'),'V300 dashboard missing')
assert(view.includes('SYSTEM SAFE MODE'),'Safe Mode UI missing')
assert(view.includes('HISTORICAL MATCH EXPLORER'),'Explorer missing')
assert(view.includes('MODEL COMPARISON STUDIO'),'Model Studio missing')
assert(view.includes("action:'set_runtime_control'"),'Runtime admin controls missing')
assert(main.includes('ProductionPlatformV300'),'V300 not integrated in MatchSimulatorPreparationView')
assert(api.includes("action==='set_runtime_control'"),'Runtime control API missing')
assert(api.includes("format==='pdf'"),'PDF export missing')
assert(api.includes('match_config_backups_v300'),'Backup API missing')
assert(safe.includes('shouldSkipAutoJobV300'),'Safe-mode job guard missing')
assert(fs.existsSync(path.join(root,'public/betai-sw-v300.js')),'Service worker missing')
assert(fs.existsSync(path.join(root,'GENERATE_VAPID_KEYS_V300.js')),'VAPID generator missing')
console.log('TEST_V300_OK')
console.log(JSON.stringify({tables:requiredTables.length,webPush:pkg.dependencies['web-push'],runtimeControls:true,safeMode:true,export:['csv','json','pdf']},null,2))
