import React, { useCallback, useEffect, useRef, useState } from 'react'
import MatchSimulatorIntroView from './MatchSimulatorIntroView'
import MatchSimulatorView from './MatchSimulatorView'
import MatchSimulatorDailyMatchesView from './MatchSimulatorDailyMatchesView'
import MatchSimulatorPreparationView from './MatchSimulatorPreparationView'

// V345: intro is intentionally disabled. Set to true to restore it.
const SHOW_FM_AI_INTRO_V345 = false



// V335 — presentation-only EN translator for the whole AI Simulation flow.
// It translates remaining legacy Polish labels/commentary without touching model logic,
// API payloads, market keys, forecasts or simulation state.
const SIMULATOR_EN_REPLACEMENTS_V335 = [
  [/TOP 5 ANALIZ DNIA/g, 'TOP 5 DAILY ANALYSES'],
  [/Value Scanner wybiera maksymalnie 5 najmocniejszych kandydatów z topowych lig \+ Ekstraklasy\. RAW jest korygowane historyczną kalibracją; pełna analiza pozostaje końcową weryfikacją\./g, 'Value Scanner selects up to 5 strongest candidates from the approved top leagues. RAW probabilities are adjusted by historical calibration; full analysis remains the final verification.'],
  [/SKANOWANIE LIVE/g, 'LIVE SCANNING'], [/SKAN GOTOWY/g, 'SCAN COMPLETE'],
  [/Sprawdzam realne statystyki meczów…/g, 'Checking real match statistics…'], [/^sprawdzonych$/g, 'checked'],
  [/17 WYBRANYCH LIG/g, '17 APPROVED LEAGUES'], [/TYLKO 17 WYBRANYCH ROZGRYWEK/g, 'ONLY 17 APPROVED COMPETITIONS'],
  [/znaleziono/g, 'found'], [/meczów widocznych/g, 'matches visible'], [/gotowych po pre-checku/g, 'ready after pre-check'], [/sprawdzam jakość/g, 'checking quality'],
  [/Brak kolejnych meczów z topowych lig na dzisiaj\./g, 'No more approved top-league fixtures today.'],
  [/Brak kolejnych nierozpoczętych meczów na dzisiaj\./g, 'No more upcoming fixtures today.'],
  [/brak meczów spełniających próg realnych statystyk/g, 'no matches meet the real-statistics threshold'],
  [/Budget Guard nie ukrywa już późniejszych spotkań/g, 'Budget Guard no longer hides later fixtures'],
  [/NAJLEPSZY RYNEK AI/g, 'BEST AI MARKET'], [/NAJMOCNIEJSZY KIERUNEK AI/g, 'STRONGEST AI DIRECTION'],
  [/KURSY 1X2/g, '1X2 ODDS'], [/BRAK KURSÓW/g, 'NO ODDS'], [/Brak kursów/g, 'No odds'], [/Realny kurs/g, 'Real odds'], [/Brak kursu rynkowego/g, 'No market odds'], [/FAIR modelu/g, 'model FAIR'], [/(?<!\p{L})KURS(?!\p{L})/gu, 'ODDS'], [/Dostępne wkrótce/g, 'Available soon'], [/Pobieram kursy…/g, 'Loading odds…'],
  [/RYNEK GOLOWY/g, 'GOALS MARKET'], [/RYNEK BTTS/g, 'BTTS MARKET'], [/RYNEK 1X2/g, '1X2 MARKET'], [/RYNEK/g, 'MARKET'],
  [/Powyżej 1\.5 gola/g, 'Over 1.5 goals'], [/Poniżej 1\.5 gola/g, 'Under 1.5 goals'], [/Powyżej 2\.5 gola/g, 'Over 2.5 goals'], [/Poniżej 2\.5 gola/g, 'Under 2.5 goals'], [/Powyżej 3\.5 gola/g, 'Over 3.5 goals'], [/Poniżej 3\.5 gola/g, 'Under 3.5 goals'],
  [/Obie drużyny strzelą/g, 'Both teams to score'], [/Nie obie strzelą/g, 'Both teams not to score'],
  [/Remis w meczu/g, 'Match draw'], [/Typ: mecz zakończy się remisem/g, 'Pick: match to finish level'], [/Typ: wygrana gospodarzy/g, 'Pick: home win'], [/Typ: wygrana gości/g, 'Pick: away win'],
  [/Typ: minimum 2 gole w meczu/g, 'Pick: at least 2 goals'], [/Typ: minimum 3 gole w meczu/g, 'Pick: at least 3 goals'], [/Typ: minimum 4 gole w meczu/g, 'Pick: at least 4 goals'],
  [/Typ: maksymalnie 1 gol w meczu/g, 'Pick: maximum 1 goal'], [/Typ: maksymalnie 2 gole w meczu/g, 'Pick: maximum 2 goals'], [/Typ: maksymalnie 3 gole w meczu/g, 'Pick: maximum 3 goals'],
  [/Typ: obie drużyny zdobędą gola/g, 'Pick: both teams score'], [/Typ: przynajmniej jedna drużyna bez gola/g, 'Pick: at least one team does not score'],
  [/Wygra ([^\n•]+)/g, '$1 to win'],
  [/\bDOM\b/g, 'HOME'], [/\bREMIS\b/g, 'DRAW'], [/GOŚCIE/g, 'AWAY'], [/GOSPODARZE/g, 'HOME'],
  [/NAJBLIŻSZY MECZ/g, 'NEXT MATCH'], [/Start za/g, 'Starts in'],

  [/Przygotowanie meczu/g, 'Match preparation'], [/Pobieramy prawdziwe dane przed uruchomieniem silnika meczu\./g, 'We load real pre-match data before starting the match engine.'],
  [/Analizuję dane meczu…/g, 'Analysing match data…'], [/Uruchom symulację/g, 'Start simulation'], [/Wróć do meczów/g, 'Back to matches'], [/Spróbuj ponownie/g, 'Try again'],
  [/Kompletność danych/g, 'Data completeness'], [/Symulacja predykcyjna — wynik nie jest rzeczywistym wynikiem przyszłego meczu\./g, 'Predictive simulation — this is not the actual future match result.'],
  [/Forma drużyn/g, 'Team form'], [/Składy XI/g, 'Starting XI'], [/Statystyki drużyn/g, 'Team statistics'], [/Sprawdzone/g, 'Checked'], [/Brak danych/g, 'Unavailable'],
  [/Nie udało się zbudować XI/g, 'Could not build XI'], [/Realne kursy dostępne/g, 'Real odds available'], [/Brak realnych kursów/g, 'No real odds'], [/Brak historii H2H/g, 'No H2H history'], [/Brak zgłoszonych absencji/g, 'No reported absences'],
  [/Część źródeł chwilowo nie odpowiedziała\. Model użyje wyłącznie dostępnych danych\./g, 'Some sources did not respond. The model will use available data only.'],
  [/Przeszukuję źródła i prognozy ekspertów…/g, 'Searching public sources and expert predictions…'], [/Konsensus zewnętrzny/g, 'External consensus'], [/źródeł znalezionych/g, 'sources found'],
  [/Identyfikacja meczu/g, 'Identifying fixture'], [/Pobieranie formy/g, 'Loading form'], [/Sprawdzanie H2H/g, 'Checking H2H'], [/Sprawdzanie absencji/g, 'Checking absences'], [/Pobieranie składów/g, 'Loading lineups'], [/Budowanie modelu AI/g, 'Building AI model'],
  [/Wymagane min\. 5 \+ 5 realnych meczów/g, 'Required: at least 5 + 5 real matches'], [/Brak tabeli • opcjonalne \(np\. puchar\)/g, 'No standings • optional (e.g. cup)'], [/Wymagane: sezonowe lub min\. 5 ostatnich meczów obu drużyn/g, 'Required: season data or at least 5 recent matches for both teams'],
  [/ostatnie składy/g, 'recent lineups'], [/ostatnich/g, 'recent'], [/sezon/g, 'season'], [/bukmacherów/g, 'bookmakers'], [/opcjonalne/g, 'optional'],
  [/Za mała próbka historyczna/g, 'Historical sample too small'], [/Historyczny Brier Score jest zbyt słaby/g, 'Historical Brier Score is too weak'], [/Historyczna pewność jest dobrze skalibrowana/g, 'Historical confidence is well calibrated'], [/Próbka wystarczająca, kalibracja w normie/g, 'Sample is sufficient and calibration is acceptable'],
  [/Brak dodatkowej prognozy API — większa część ciężaru spoczywa na modelu statystycznym\./g, 'No additional API prediction — more weight is carried by the statistical model.'],
  [/Historyczna kalibracja wybranego rynku jest słaba — rekomendacja jest blokowana\./g, 'Historical calibration for the selected market is weak — recommendation is blocked.'],
  [/Kalibracja rynku ma dopiero ([0-9]+) prób\./g, 'Market calibration has only $1 samples.'], [/Brak dużych czerwonych flag w dostępnych danych przedmeczowych\./g, 'No major red flags in the available pre-match data.'],
  [/Model nie znalazł jednego dominującego czynnika — prognoza jest wynikiem połączenia kilku umiarkowanych sygnałów\./g, 'The model found no single dominant factor — the forecast combines several moderate signals.'],
  [/Brak kompletnego rynku kursowego — model pokazuje prawdopodobieństwa, ale nie wymusza rekomendacji\./g, 'No complete odds market — the model shows probabilities but does not force a recommendation.'],
  [/Brak pełnego rynku do wiarygodnego usunięcia marży bukmachera/g, 'No complete market to remove bookmaker margin reliably'], [/Za niska jakość danych/g, 'Data quality too low'], [/Za mała próbka backtestu — brak rekomendacji/g, 'Backtest sample too small — no recommendation'],
  [/Model jest słabo skalibrowany dla tego rynku/g, 'Model is poorly calibrated for this market'], [/Modele zbyt mocno się nie zgadzają — brak rekomendacji/g, 'Models disagree too strongly — no recommendation'], [/Zewnętrzne źródła są zbyt rozbieżne — brak rekomendacji/g, 'External sources disagree too strongly — no recommendation'], [/Łączna wiarygodność modelu jest za niska/g, 'Overall model reliability is too low'],
  [/Duża przewaga po usunięciu marży i dobra jakość modelu/g, 'Large edge after removing margin and good model quality'], [/Przewaga przekracza wymagany próg/g, 'Edge exceeds the required threshold'], [/Dodatnia przewaga, ale poniżej bezpiecznego progu/g, 'Positive edge but below the safe threshold'], [/Brak dodatniej przewagi nad ceną rynkową/g, 'No positive edge over the market price'],
  [/Wiarygodność tej analizy/g, 'Reliability of this analysis'], [/Finalna decyzja modelu/g, 'Final model decision'], [/Prognoza przedmeczowa \+ Value Engine/g, 'Pre-match forecast + Value Engine'], [/Dlaczego Bet\+AI tak ocenia ten mecz\?/g, 'Why does Bet+AI rate this match this way?'],
  [/CO WSPIERA PROGNOZĘ/g, 'WHAT SUPPORTS THE FORECAST'], [/RYZYKA \/ OGRANICZENIA/g, 'RISKS / LIMITATIONS'], [/CO MOŻE ZMIENIĆ PROGNOZĘ/g, 'WHAT COULD CHANGE THE FORECAST'],
  [/MECZ ZAKWALIFIKOWANY/g, 'MATCH QUALIFIED'], [/MECZ ODRZUCONY — ZA MAŁO DANYCH/g, 'MATCH REJECTED — INSUFFICIENT DATA'],
  [/Rzeczywista skuteczność modelu/g, 'Real model performance'], [/KALIBRACJA PEWNOŚCI/g, 'CONFIDENCE CALIBRATION'], [/niżej = lepiej/g, 'lower is better'], [/rozliczonych meczów/g, 'settled matches'], [/value betów/g, 'value bets'], [/30 DNI/g, '30 DAYS'],
  [/ZBIERANIE DANYCH/g, 'COLLECTING DATA'], [/LICZĘ/g, 'CALCULATING'], [/AKTYWNY/g, 'ACTIVE'], [/ZAPISUJĘ/g, 'SAVING'], [/OCZEKUJE/g, 'WAITING'],
  [/NAJCZĘSTSZE PRZYCZYNY PRZEGRANYCH PROGNOZ/g, 'MOST COMMON CAUSES OF LOSING FORECASTS'], [/Brak aktywnych alarmów jakości modelu\./g, 'No active model-quality alerts.'],

  [/STATYSTYKI MECZU/g, 'MATCH STATISTICS'], [/XG \(OCZEKIWANE BRAMKI\)/g, 'XG (EXPECTED GOALS)'], [/KLUCZOWE STATYSTYKI/g, 'KEY STATISTICS'], [/OSTATNIE WYDARZENIA/g, 'RECENT EVENTS'],
  [/Strzały celne/g, 'Shots on target'], [/Strzały/g, 'Shots'], [/Posiadanie piłki/g, 'Possession'], [/Rzuty rożne/g, 'Corners'], [/Kartki/g, 'Cards'], [/Podania/g, 'Passes'], [/Celność podań/g, 'Pass accuracy'], [/Pojedynki wygrane/g, 'Duels won'], [/Spalone/g, 'Offsides'],
  [/Pełne statystyki/g, 'Full statistics'], [/bieżące xG/g, 'live xG'], [/Model przedmeczowy/g, 'Pre-match model'], [/Szczegóły xG/g, 'xG details'], [/Zobacz analizę/g, 'View analysis'], [/Pełny raport/g, 'Full report'], [/Pełny przebieg/g, 'Full timeline'],
  [/WIDOK MECZU/g, 'MATCH VIEW'], [/ANALIZA/g, 'ANALYSIS'], [/STREFY BOISKOWE/g, 'PITCH ZONES'], [/SIATKA PODAŃ/g, 'PASS NETWORK'], [/NOWY SCENARIUSZ/g, 'NEW SCENARIO'],
  [/NA ŻYWO/g, 'LIVE'], [/KONIEC/g, 'FULL TIME'], [/PAUZA/g, 'PAUSED'], [/1\. POŁOWA/g, '1ST HALF'], [/2\. POŁOWA/g, '2ND HALF'],
  [/Pełny mecz: 2 minuty przy prędkości x1/g, 'Full match: 2 minutes at x1 speed'], [/Brak pełnych oficjalnych XI z pozycjami/g, 'No complete official XI with positions'], [/Boisko nie pokazuje fikcyjnych zawodników\./g, 'The pitch does not show fictional players.'],
  [/Oczekiwanie na oficjalny skład/g, 'Waiting for official lineup'], [/Oficjalny/g, 'Official'], [/oficjalny/g, 'official'], [/przewidywany/g, 'predicted'], [/Brak składu do symulacji/g, 'No lineup available for simulation'], [/Brak pozycji boiskowych w API/g, 'No pitch positions in API data'],
  [/Bet\+AI nie generuje przypadkowych nazwisk ani ustawienia\./g, 'Bet+AI does not generate random player names or formations.'], [/Bet\+AI nie tworzy fikcyjnych nazwisk\. Skład pojawi się automatycznie, gdy API-Football opublikuje startową XI\./g, 'Bet+AI does not invent player names. The lineup will appear automatically when API-Football publishes the starting XI.'],
  [/XI przewidywana z ostatnich realnych składów\./g, 'Predicted XI based on recent real lineups.'], [/zawodników/g, 'players'], [/predykcja z/g, 'prediction from'], [/składów/g, 'lineups'], [/Trener/g, 'Coach'], [/Dane API/g, 'API data'],
  [/Pobieram realne dane meczu…/g, 'Loading real match data…'], [/XI oficjalne\/przewidywane/g, 'official/predicted XI'], [/formacje/g, 'formations'], [/forma/g, 'form'], [/tabela/g, 'standings'],
  [/Symulacja rozpoczyna się od 00:00\./g, 'Simulation starts at 00:00.'], [/Powtórz ten sam seed/g, 'Replay the same seed'],
  [/Mecz gotowy\. Skład przewidywany z ostatnich realnych XI; formacja i zawodnicy pochodzą z danych API\./g, 'Match ready. The lineup is predicted from recent real XIs; formation and players come from API data.'], [/Mecz gotowy\. Silnik wykorzystuje oficjalne składy i formacje z API\./g, 'Match ready. The engine uses official API lineups and formations.'], [/Mecz nie spełnia warunków jakości danych\./g, 'The match does not meet data-quality requirements.'],
  [/Kliknij, aby aktywować prawdziwe audio stadionu/g, 'Click to enable real stadium audio'], [/Wycisz dźwięki meczu/g, 'Mute match audio'], [/Włącz dźwięki meczu/g, 'Enable match audio'], [/Aktywuj prawdziwe audio stadionu/g, 'Enable real stadium audio'], [/AKTYWUJ AUDIO/g, 'ENABLE AUDIO'], [/DŹWIĘK MECZU/g, 'MATCH AUDIO'], [/1 klik • wymóg przeglądarki/g, '1 click • browser requirement'], [/Przyśpiewki • reakcje • gwizdek • gol/g, 'Chants • reactions • whistle • goal'], [/Głośność dźwięków meczu/g, 'Match audio volume'],
  [/Raport końcowy symulacji/g, 'Final simulation report'], [/STRZAŁY/g, 'SHOTS'], [/ROŻNE/g, 'CORNERS'], [/KARTKI/g, 'CARDS'], [/ZMIANY/g, 'SUBSTITUTIONS'], [/^\s*czerwone\s*$/g, 'red cards'],
  [/V320 generuje posiadania, ruch, podania i sytuacje z zamrożonego profilu Bet\+AI\. LIVE AI Coach aktualizuje prawdopodobieństwa wyłącznie z przebiegu tej symulacji; bez kursu live nie potwierdza VALUE\./g, 'V320 generates possessions, movement, passes and chances from the frozen Bet+AI profile. LIVE AI Coach updates probabilities only from this simulation; without live odds it does not confirm VALUE.'],
  [/▶ Początek symulacji/g, '▶ Simulation kick-off'], [/▶ Start drugiej połowy/g, '▶ Start of the second half'], [/🎯 Strzał/g, '🎯 Shot'], [/🚩 Rzut rożny dla/g, '🚩 Corner for'], [/📣 Groźny faul/g, '📣 Dangerous foul'],
  [/ spokojnie buduje akcję od tyłu/g, ' builds patiently from the back'], [/ wyprowadza piłkę spod pressingu/g, ' carries the ball out of pressure'], [/ prowadzi piłkę przez środek/g, ' carries the ball through midfield'], [/ zagrywa piłkę między liniami/g, ' plays the ball between the lines'], [/ rusza w stronę pola karnego/g, ' drives toward the penalty area'], [/ cofa piłkę i cierpliwie szuka miejsca/g, ' recycles possession and patiently looks for space'], [/ szuka ostatniego podania pod bramką/g, ' looks for the final pass near goal'], [/ przejmuje piłkę — szybka zmiana kierunku akcji/g, ' wins the ball — quick transition'], [/ prowadzi piłkę pod pole karne/g, ' carries the ball toward the box'], [/ składa się do strzału…/g, ' prepares to shoot…'], [/ uderza na bramkę!/g, ' shoots at goal!'], [/ wrzuca piłkę z narożnika/g, ' delivers the corner'], [/ ustawia piłkę do rzutu wolnego/g, ' sets up the free kick'], [/ świętuje bramkę — za chwilę wznowienie od środka/g, ' celebrates the goal — restart from the centre shortly'], [/ wznawia grę od środka/g, ' restarts from the centre'], [/ — zespół musi przebudować ustawienie/g, ' — the team must reorganise'],
  [/wyższy pressing i szybsze przejście do ataku/g, 'higher press and faster attacking transitions'], [/bardziej ofensywne ustawienie na końcówkę/g, 'more attacking setup for the closing stages'],
  [/Piłka/g, 'Ball'], [/Drużyna/g, 'Team'],
  [/ symulacji modelu/g, ' model simulations'], [/ prób\b/g, ' samples'], [/ próba/g, ' sample'], [/ źr\./g, ' src.'],
]


// V336 — complete EN pass for all remaining preparation + V320 match-engine UI.
// Presentation only: no model/API/simulation calculations are modified.
const SIMULATOR_EN_REPLACEMENTS_V336_EXTRA = [
  [/Szybkie podsumowanie analizy/g, 'Quick analysis summary'],
  [/Najważniejsza decyzja, kierunki i ryzyko — bez czytania całego raportu\./g, 'Key decision, directions and risk — at a glance.'],
  [/FINALNA DECYZJA MODELU/g, 'FINAL MODEL DECISION'],
  [/Sygnał przeszedł konserwatywne filtry modelu\./g, 'The signal passed the model’s conservative filters.'],
  [/Kierunek wart obserwacji, ale model nie daje jeszcze pełnego BET\./g, 'Worth monitoring, but the model does not yet confirm a full BET.'],
  [/Kierunki poniżej pozostają informacyjne — model nie rekomenduje obecnie stawki\./g, 'The directions below are informational — the model does not currently recommend a stake.'],
  [/NAJMOCNIEJSZY KIERUNEK/g, 'STRONGEST DIRECTION'],
  [/RYNEK BRAMKOWY/g, 'GOALS MARKET'],
  [/RYNEK MODELU/g, 'MODEL MARKET'],
  [/xG • OCZEKIWANE GOLE/g, 'xG • EXPECTED GOALS'],
  [/WIARYGODNOŚĆ/g, 'RELIABILITY'],
  [/KALIBRACJA/g, 'CALIBRATION'],
  [/NAJLEPSZE 1X2/g, 'BEST 1X2'],
  [/WYSOKA/g, 'HIGH'], [/ŚREDNIA/g, 'MEDIUM'], [/NISKA/g, 'LOW'],
  [/PRÓG SPEŁNIONY/g, 'THRESHOLD MET'], [/ZBIERANIE PRÓB/g, 'COLLECTING SAMPLES'],
  [/NAJWAŻNIEJSZE POWODY/g, 'KEY REASONS'],
  [/Co naprawdę wpływa na ocenę tego meczu/g, 'What actually drives this match rating'],
  [/PROFIL SYMULACJI/g, 'SIMULATION PROFILE'],
  [/Zamrożony model Bet\+AI/g, 'Frozen Bet+AI model'],
  [/Pokaż pełną analizę/g, 'Show full analysis'],
  [/V322 zmienia tylko interfejs\. Prediction Engine i decyzje pozostają bez zmian\./g, 'V322 changes the interface only. Prediction Engine and decisions remain unchanged.'],
  [/POSTĘP PRZYGOTOWANIA/g, 'PREPARATION PROGRESS'],
  [/Analiza gotowa do symulacji/g, 'Analysis ready for simulation'],
  [/Oczekiwanie na dane/g, 'Waiting for data'],
  [/BŁĄD/g, 'ERROR'],
  [/DZISIAJ/g, 'TODAY'], [/STADION/g, 'STADIUM'], [/Dane stadionu oczekują/g, 'Stadium data pending'],
  [/Piłka nożna/g, 'Football'],
  [/API 429 • automatyczne ponowienie/g, 'API 429 • automatic retry'],
  [/API zajęte • używam ostatnich poprawnych danych z cache/g, 'API busy • using the latest valid cached data'],
  [/Supabase cache \/ snapshot • oszczędzam requesty API/g, 'Supabase cache / snapshot • saving API requests'],
  [/Globalny throttle API aktywny/g, 'Global API throttle active'],
  [/Najlepszy zestaw danych zapisano w Supabase\./g, 'Best available data snapshot saved in Supabase.'],
  [/Baza:/g, 'Sources:'],
  [/Wagi źródeł dla tego meczu/g, 'Source weights for this match'],
  [/model statystyczny/g, 'statistical model'],
  [/Najbardziej prawdopodobne wyniki/g, 'Most likely scorelines'],
  [/NAJBARDZIEJ PRAWDOPODOBNE WYNIKI/g, 'MOST LIKELY SCORELINES'],
  [/Ruchy rynku zapisany w Supabase/g, 'Market moves saved in Supabase'],
  [/Ruchy rynku zapisane w Supabase/g, 'Market moves saved in Supabase'],
  [/0 dodatkowych requestów API/g, '0 additional API requests'],
  [/TOP 3 kandydaci • bez wymuszania zakładu/g, 'TOP 3 candidates • no forced bet'],
  [/przed kalibracją/g, 'before calibration'],
  [/po kalibracji/g, 'after calibration'],
  [/Test rekomendacji bez stawiania pieniędzy/g, 'Recommendation test without real-money staking'],
  [/niezależnych modeli/g, 'independent models'],
  [/\bwaga\b/g, 'weight'],
  [/snapshot danych, wag i decyzji pre-match/g, 'snapshot of pre-match data, weights and decisions'],
  [/zbieranie realnych błędów modelu/g, 'collecting real model errors'],
  [/Brak aktywnych alarmów jakości modelu\./g, 'No active model-quality alerts.'],
  [/Rzeczywista skuteczność modelu/g, 'Real model performance'],
  [/ROZLICZONYCH/g, 'SETTLED'],
  [/rozliczonych/g, 'settled'],
  [/\bmeczów\b/g, 'matches'],
  [/\bmeczu\b/g, 'match'],
  [/niżej = lepiej/g, 'lower = better'],
  [/value betów/g, 'value bets'],
  [/30 DNI/g, '30 DAYS'],
  [/realnie/g, 'actual'],
  [/Wyniki są liczone wyłącznie z zamrożonych prognoz pre-match i prawdziwych rezultatów\./g, 'Results are calculated only from frozen pre-match forecasts and real outcomes.'],
  [/Pierwsze statystyki pojawią się po zakończeniu i automatycznym rozliczeniu zapisanych prognoz\./g, 'The first statistics will appear after saved forecasts are completed and automatically settled.'],
  [/Forecast po kickoffie jest zablokowany, więc wynik nie może zmienić historycznej predykcji\./g, 'Forecast changes after kick-off are blocked, so the result cannot alter the historical prediction.'],
  [/chronologicznie • bez danych z przyszłości/g, 'chronological • no future data'],
  [/prób rynku/g, 'market samples'],
  [/Część danych dodatkowych jest niedostępna, ale wymagane statystyki sportowe spełniają próg jakości\./g, 'Some additional data is unavailable, but the required sports statistics meet the quality threshold.'],
  [/MECZ ODRZUCONY PRZEZ FILTR JAKOŚCI/g, 'MATCH REJECTED BY QUALITY FILTER'],
  [/za mało danych/g, 'insufficient data'],

  // Match Engine / live simulation UI
  [/PRZERWA/g, 'HALF-TIME'],
  [/symulacji modelu/g, 'model simulations'],
  [/Momentum na żywo gospodarze kontra goście/g, 'Live momentum: home vs away'],
  [/Gospodarze/g, 'Home'], [/Goście/g, 'Away'], [/Drużyna/g, 'Team'],
  [/Oficjalny/g, 'Official'], [/oficjalny/g, 'official'], [/przewidywany/g, 'predicted'],
  [/Brak składu/g, 'No lineup'],
  [/Brak pozycji boiskowych w API/g, 'No pitch positions in API data'],
  [/Brak składu do symulacji/g, 'No lineup available for simulation'],
  [/XI przewidywana z ostatnich realnych składów\./g, 'Predicted XI based on recent real lineups.'],
  [/Bet\+AI nie generuje przypadkowych nazwisk ani ustawienia\./g, 'Bet+AI does not generate random player names or formations.'],
  [/Dane API/g, 'API data'], [/Trener/g, 'Coach'], [/zawodników/g, 'players'], [/składów/g, 'lineups'],
  [/predykcja z/g, 'prediction from'],
  [/Strzały celne/g, 'Shots on target'], [/Strzały/g, 'Shots'], [/Posiadanie piłki/g, 'Possession'], [/Rzuty rożne/g, 'Corners'], [/Kartki/g, 'Cards'],
  [/Podania/g, 'Passes'], [/Celność podań/g, 'Pass accuracy'], [/Pojedynki wygrane/g, 'Duels won'], [/Spalone/g, 'Offsides'],
  [/Pełne statystyki/g, 'Full statistics'], [/bieżące xG/g, 'live xG'], [/Model przedmeczowy/g, 'Pre-match model'], [/Szczegóły xG/g, 'xG details'],
  [/Zobacz analizę/g, 'View analysis'], [/Pełny raport/g, 'Full report'], [/Pełny przebieg/g, 'Full timeline'],
  [/WIDOK MECZU/g, 'MATCH VIEW'], [/ANALIZA/g, 'ANALYSIS'], [/STREFY BOISKOWE/g, 'PITCH ZONES'], [/SIATKA PODAŃ/g, 'PASS NETWORK'],
  [/NOWY SCENARIUSZ/g, 'NEW SCENARIO'], [/Powtórz ten sam seed/g, 'Replay the same seed'],
  [/NA ŻYWO/g, 'LIVE'], [/KONIEC/g, 'FULL TIME'], [/PAUZA/g, 'PAUSED'],
  [/Mecz gotowy\. Skład przewidywany z ostatnich realnych XI; formacja i zawodnicy pochodzą z danych API\./g, 'Match ready. The lineup is predicted from recent real XIs; formation and players come from API data.'],
  [/Mecz gotowy\. Silnik wykorzystuje oficjalne składy i formacje z API\./g, 'Match ready. The engine uses official API lineups and formations.'],
  [/Mecz nie spełnia warunków jakości danych\./g, 'The match does not meet data-quality requirements.'],
  [/Symulacja rozpoczyna się od 00:00\./g, 'Simulation starts at 00:00.'],
  [/Kliknij, aby aktywować prawdziwe audio stadionu/g, 'Click to enable real stadium audio'],
  [/Wycisz dźwięki meczu/g, 'Mute match audio'], [/Włącz dźwięki meczu/g, 'Enable match audio'], [/Aktywuj prawdziwe audio stadionu/g, 'Enable real stadium audio'],
  [/AKTYWUJ AUDIO/g, 'ENABLE AUDIO'], [/DŹWIĘK MECZU/g, 'MATCH AUDIO'], [/1 klik • wymóg przeglądarki/g, '1 click • browser requirement'],
  [/Przyśpiewki • reakcje • gwizdek • gol/g, 'Chants • reactions • whistle • goal'], [/Głośność dźwięków meczu/g, 'Match audio volume'],
  [/Raport końcowy symulacji/g, 'Final simulation report'], [/STRZAŁY/g, 'SHOTS'], [/ROŻNE/g, 'CORNERS'], [/KARTKI/g, 'CARDS'], [/ZMIANY/g, 'SUBSTITUTIONS'], [/^\s*czerwone\s*$/g, 'red cards'],
  [/V320 generuje posiadania, ruch, podania i sytuacje z zamrożonego profilu Bet\+AI\. LIVE AI Coach aktualizuje prawdopodobieństwa wyłącznie z przebiegu tej symulacji; bez kursu live nie potwierdza VALUE\./g, 'V320 generates possessions, movement, passes and chances from the frozen Bet+AI profile. LIVE AI Coach updates probabilities only from this simulation; without live odds it does not confirm VALUE.'],

  // Generated commentary / event text
  [/▶ Początek symulacji/g, '▶ Simulation kick-off'], [/▶ Start drugiej połowy/g, '▶ Start of the second half'], [/🏁 Koniec symulacji/g, '🏁 End of simulation'],
  [/🎯 Strzał/g, '🎯 Shot'], [/🚩 Rzut rożny dla/g, '🚩 Corner for'], [/📣 Groźny faul/g, '📣 Dangerous foul'],
  [/⚽ GOL Z KARNEGO/g, '⚽ PENALTY GOAL'], [/🔄 Zmiana taktyczna/g, '🔄 Tactical change'], [/🔄 Zmiana/g, '🔄 Substitution'],
  [/ za /g, ' for '],
  [/spokojnie buduje akcję od tyłu/g, 'builds patiently from the back'],
  [/wyprowadza piłkę spod pressingu/g, 'carries the ball out of pressure'],
  [/podaje do/g, 'passes to'],
  [/prowadzi piłkę przez środek/g, 'carries the ball through midfield'],
  [/zagrywa piłkę między liniami/g, 'plays the ball between the lines'],
  [/rusza w stronę pola karnego/g, 'drives toward the penalty area'],
  [/cofa piłkę i cierpliwie szuka miejsca/g, 'recycles possession and patiently looks for space'],
  [/szuka ostatniego podania pod bramką/g, 'looks for the final pass near goal'],
  [/przejmuje piłkę — szybka zmiana kierunku akcji/g, 'wins the ball — quick transition'],
  [/zagrywa do/g, 'plays to'],
  [/prowadzi piłkę pod pole karne/g, 'carries the ball toward the box'],
  [/składa się do strzału…/g, 'sets up to shoot…'], [/uderza na bramkę!/g, 'shoots at goal!'],
  [/wrzuca piłkę z narożnika/g, 'delivers the corner'], [/ustawia piłkę do rzutu wolnego/g, 'sets up the free kick'],
  [/świętuje bramkę — za chwilę wznowienie od środka/g, 'celebrates the goal — restart from the centre shortly'],
  [/wznawia grę od środka/g, 'restarts from the centre'],
  [/przecina linię podania/g, 'cuts out the passing lane'],
  [/posyła piłkę w wolną przestrzeń do/g, 'plays the ball into space for'],
  [/— zespół musi przebudować ustawienie/g, '— the team must reorganise'],
  [/wyższy pressing i szybsze przejście do ataku/g, 'higher press and faster attacking transitions'],
  [/bardziej ofensywne ustawienie na końcówkę/g, 'more attacking setup for the closing stages'],

  // Common preparation fragments left by legacy modules
  [/gola na mecz/g, 'goals per match'], [/gola — to podnosi profil bramkowy/g, 'goals — this raises the scoring profile'],
  [/źródeł, zgodność/g, 'sources, agreement'], [/Absencje:/g, 'Absences:'], [/\bgospodarze\b/g, 'home'], [/\bgoście\b/g, 'away'],
  [/model podnosi wymagany próg value/g, 'the model raises the required value threshold'],
  [/prób\./g, 'samples.'], [/\bprób\b/g, 'samples'],
  [/brak rekomendacji/g, 'no recommendation'], [/Brak rekomendacji/g, 'No recommendation'],
  [/brak wystarczającej przewagi/g, 'insufficient edge'],
  [/Brak wystarczającej przewagi/g, 'Insufficient edge'],
  [/przed kalibracją/g, 'before calibration'],
  [/kalibracja/g, 'calibration'],
  [/Kalibracja/g, 'Calibration'],
  [/\boczekuje\b/g, 'waiting'], [/OCZEKUJE/g, 'WAITING'], [/ZAPISUJĘ/g, 'SAVING'], [/AKTYWNY/g, 'ACTIVE'],  [/RAW → skalibrowane prawdopodobieństwo/g, 'RAW → calibrated probability'],
  [/MODEL STATYSTYCZNY/g, 'STATISTICAL MODEL'],
  [/NO BET — KALIBRACJA/g, 'NO BET — CALIBRATION'],
  [/Za mała próbka historyczna/g, 'Historical sample too small'],
  [/Bet\+AI pokaże rekomendację dopiero po min\. ([0-9]+) rozliczonych próbach danego rynku\./g, 'Bet+AI will show a recommendation only after at least $1 settled samples for this market.'],
  [/Przewaga \+([0-9.]+) pp jest poniżej wymaganego progu ([0-9.]+) pp\./g, 'Edge +$1 pp is below the required $2 pp threshold.'],
  [/Brak wystarczającej przewagi/g, 'Insufficient edge'],
  [/rynek no-vig/g, 'no-vig market'], [/próg/g, 'threshold'],
  [/VALUE NIEOCENIONE/g, 'VALUE NOT ASSESSED'],
  [/Brak pełnych realnych kursów/g, 'No complete real odds'],
  [/Do Value V2 potrzebna jest para\/komplet kursów z tego samego bukmachera, aby usunąć marżę\./g, 'Value V2 requires a complete odds set from the same bookmaker in order to remove the margin.'],
  [/Ruch rynku zapisany w Supabase/g, 'Market movement saved in Supabase'],
  [/TOP 3 przewagi cenowe/g, 'TOP 3 pricing edges'],
  [/RYNEK NO-VIG/g, 'NO-VIG MARKET'],
  [/BEZ UKRYWANIA CZYNNIKÓW/g, 'NO HIDDEN FACTORS'],
  [/Dlaczego Bet\+AI tak ocenia ten mecz\?/g, 'Why does Bet+AI rate this match this way?'],
  [/CO WSPIERA PROGNOZĘ/g, 'WHAT SUPPORTS THE FORECAST'], [/RYZYKA \/ OGRANICZENIA/g, 'RISKS / LIMITATIONS'],
  [/Finalna decyzja modelu/g, 'Final model decision'],
  [/RYNEK/g, 'MARKET'],
  [/Brak pełnego rynku kursowego/g, 'No complete odds market'],
  [/Modele składowe rozjeżdżają się/g, 'Component models disagree'],
  [/modele składowe rozjeżdżają się/g, 'component models disagree'],
  [/przed kalibracją/g, 'before calibration'],
  [/aktywny model/g, 'active model'],
  [/Rynek jest tylko warstwą wyceny\./g, 'The market is only a pricing layer.'],
  [/Challenger zbiera historię\./g, 'Challenger is collecting history.'],
  [/Kontrola wspólnej ekspozycji\./g, 'Shared-exposure control.'],
  [/Model Brain • automatyczne wagi i governance/g, 'Model Brain • automatic weights and governance'],
  [/\bdni\b/g, 'days'], [/prób • Brier/g, 'samples • Brier'],
  [/AKTYWNY/g, 'ACTIVE'], [/profile audit w Supabase/g, 'profile audit in Supabase'], [/zbieranie profilu/g, 'collecting profile'],
  [/XI • absencje • fatigue • matchup adjustment/g, 'XI • absences • fatigue • matchup adjustment'],
  [/BRAK XI/g, 'NO XI'], [/absencje/g, 'absences'], [/\bmecze\b/g, 'matches'],
  [/bez fikcyjnych ratingów zawodników/g, 'no fabricated player ratings'],
  [/kontrola jakości/g, 'quality control'], [/shrinkage aktywny/g, 'shrinkage active'], [/zbieranie out-of-sample historii/g, 'collecting out-of-sample history'],
  [/KALIBRACJA PEWNOŚCI/g, 'CONFIDENCE CALIBRATION'],
  [/chronologicznie • bez danych z przyszłości/g, 'chronological • no future data'],
  [/prób rynku/g, 'market samples'],
  [/^TAK$/g, 'YES'], [/^NIE$/g, 'NO'],
  [/\boczekuje\b/g, 'waiting'], [/OCZEKUJE/g, 'WAITING'], [/ZAPISUJĘ/g, 'SAVING'], [/AKTYWNY/g, 'ACTIVE'],
]


// V370 — complete English coverage for the FM AI tab.
// This is presentation-only. It does not touch API payloads, model keys, probabilities,
// scanner decisions, tracker settlement logic or Supabase data.
const SIMULATOR_EN_REPLACEMENTS_V370_FM_AI = [
  // Long/specific phrases first so shorter replacements cannot split them.
  [/Dodatni bilans i yield mówią, czy płaska stawka 10 zł faktycznie zarabia\. Trafność porównujemy z break-even wynikającym z realnych kursów\. Przy małej próbie wynik może być przypadkowy — sensowne wnioski zaczynają się dopiero po dziesiątkach i setkach rozliczonych typów\./g, 'Positive profit and yield show whether a flat 10 PLN stake is actually profitable. Hit rate is compared with the break-even rate implied by real odds. Small samples can be random — meaningful conclusions begin only after dozens or hundreds of settled picks.'],
  [/SQL został uruchomiony\? Odświeżam automatycznie, ale po utworzeniu tabeli Supabase może potrzebować chwili na odświeżenie schematu API\./g, 'Was the SQL run? I am refreshing automatically, but Supabase may need a moment to refresh the API schema after the table is created.'],
  [/Przygotowuję ranking typów/g, 'Preparing pick rankings'],
  [/WHY AI — CO WSPIERA TYP/g, 'WHY AI — WHAT SUPPORTS THE PICK'],
  [/Market consensus: ([0-9]+) bukmacherów, zgodność ([0-9]+)%\./g, 'Market consensus: $1 bookmakers, $2% agreement.'],
  // V370 hard-complete pack: exact phrases that were still able to appear in Polish
  // because older modules render legacy labels dynamically.
  [/NAJBLIŻSZY MECZ/g, 'NEXT MATCH'],
  [/BRAK KURSÓW/g, 'NO ODDS'], [/BRAK RYNKU/g, 'NO MARKET'], [/^BRAK$/g, 'NONE'],
  [/ŚR\. KURS/g, 'AVG. ODDS'],
  [/STATYSTYKI MECZU/g, 'MATCH STATISTICS'],
  [/MECZ ODRZUCONY — ZA MAŁO DANYCH/g, 'MATCH REJECTED — INSUFFICIENT DATA'],
  [/Realne kursy dostępne/g, 'Real odds available'],
  [/Część źródeł chwilowo nie odpowiedziała\. Model użyje wyłącznie dostępnych danych\./g, 'Some sources did not respond. The model will use available data only.'],
  [/źródeł znalezionych/g, 'sources found'],
  [/Historyczna pewność jest dobrze skalibrowana/g, 'Historical confidence is well calibrated'],
  [/Ostatnie realne mecze/g, 'Recent real matches'],
  [/Błąd Web Intelligence/g, 'Web Intelligence error'], [/Brak fixture ID/g, 'No fixture ID'],
  [/Powyżej 1\.5/g, 'Over 1.5'], [/Powyżej 2\.5/g, 'Over 2.5'], [/Powyżej 3\.5/g, 'Over 3.5'],
  [/Poniżej 1\.5/g, 'Under 1.5'], [/Poniżej 2\.5/g, 'Under 2.5'], [/Poniżej 3\.5/g, 'Under 3.5'],
  [/Model nie znajduje wystarczająco mocnego sygnału do rekomendacji\./g, 'The model does not find a strong enough signal for a recommendation.'],
  [/ ma wyższe xG w modelu: ([0-9.]+) – ([0-9.]+)\./g, ' has higher model xG: $1 – $2.'],
  [/Model daje równe xG: ([0-9.]+) – ([0-9.]+)\./g, 'The model gives equal xG: $1 – $2.'],
  [/Najwyższy kierunek 1X2: ([^—]+) — ([0-9.]+)%\./g, 'Strongest 1X2 direction: $1 — $2%.'],
  [/Profil bramkowy:/g, 'Goals profile:'],
  [/Dostępne kursy: ([0-9]+) źródeł bukmacherskich; Value Engine pozostaje niezależny od modelu\./g, 'Available odds: $1 bookmaker sources; Value Engine remains independent from the model.'],
  [/Brak pełnego rynku no-vig — kurs nie wpływa na samą prognozę modelu\./g, 'No complete no-vig market — odds do not affect the model forecast itself.'],
  [/Kierunki poniżej pozostają informacyjne — model nie rekomenduje obecnie stawki\./g, 'The directions below remain informational — the model currently does not recommend a stake.'],
  [/RYNEK BRAMKOWY/g, 'GOALS MARKET'],
  [/◐ UMIARKOWANA ZGODNOŚĆ/g, '◐ MODERATE AGREEMENT'],
  [/API zajęte • używam ostatnich poprawnych danych z cache/g, 'API busy • using the latest valid cached data'],
  [/Nie znaleziono wystarczającej liczby niezależnych prognoz dla tego meczu\./g, 'Not enough independent forecasts were found for this match.'],
  [/RYNEK \/ KURSY/g, 'MARKET / ODDS'],
  [/zbieranie historii/g, 'collecting history'],
  [/Rynek jest tylko warstwą wyceny\./g, 'The market is only a pricing layer.'],
  [/Źródła consensus:/g, 'Consensus sources:'], [/używane do decyzji/g, 'used for the decision'], [/bez marży/g, 'no margin'],
  [/BET: przewaga pozostaje dodatnia nawet po odjęciu ±([0-9.]+) pp niepewności\./g, 'BET: the edge remains positive even after subtracting ±$1 pp of uncertainty.'],
  [/WATCH: dodatnia przewaga istnieje, ale nie przechodzi konserwatywnego progu wejścia\./g, 'WATCH: a positive edge exists, but it does not pass the conservative entry threshold.'],
  [/WATCH: modele składowe mają średnią rozbieżność \(([0-9.]+) pp\)\./g, 'WATCH: component models show moderate disagreement ($1 pp).'],
  [/Brak wystarczającej przewagi po konserwatywnej korekcie\./g, 'Insufficient edge after the conservative adjustment.'],
  [/NAJWAŻNIEJSZE POWODY/g, 'KEY REASONS'],
  [/Co naprawdę wpływa na ocenę tego meczu/g, 'What really drives this match rating'],
  // League/country metadata shown in the left selector and cards.
  [/Najwyższa liga w Anglii/g, 'Top league in England'], [/Najwyższa liga w Niemczech/g, 'Top league in Germany'],
  [/Najwyższa liga w Portugalii/g, 'Top league in Portugal'], [/Najwyższa liga piłkarska w Polsce/g, 'Top football league in Poland'],
  [/Najwyższa liga w Hiszpanii/g, 'Top league in Spain'], [/Najwyższa liga we Włoszech/g, 'Top league in Italy'],
  [/Druga liga we Włoszech/g, 'Second division in Italy'], [/Najwyższa liga w Holandii/g, 'Top league in the Netherlands'],
  [/Najwyższa liga we Francji/g, 'Top league in France'],
  [/^Włochy$/g, 'Italy'], [/^Świat$/g, 'World'],
  // Match Operations / Intelligence / Live Pre-Match text nodes
  [/([0-9]+) MECZÓW/g, '$1 MATCHES'], [/brak freeze/g, 'no freeze'],
  [/Freeze Ledger \+ kursy T-24h \/ T-6h \/ T-1h \/ T-15m/g, 'Freeze Ledger + odds T-24h / T-6h / T-1h / T-15m'],
  [/brak danych/g, 'no data'], [/zbieranie poprzednich XI/g, 'collecting previous XIs'],
  [/rynek ([0-9.]+)/g, 'market $1'], [/czekam na kursy/g, 'waiting for odds'],
  [/Skład potwierdzony/g, 'Lineup confirmed'], [/Rotacja XI/g, 'XI rotation'],
  [/Zmiana bramkarza/g, 'Goalkeeper change'], [/Zmiana ustawienia/g, 'Formation change'],
  [/Nowa absencja startera/g, 'New starter absence'], [/Zmiana decyzji/g, 'Decision change'],
  [/Spadek confidence/g, 'Confidence drop'], [/Zmiana probability/g, 'Probability change'],
  [/Ruch rynku/g, 'Market move'], [/^Pogoda$/g, 'Weather'],
  [/Nowa zmiana przed meczem/g, 'New pre-match change'],
  [/Zaloguj się, aby używać tej funkcji\./g, 'Sign in to use this feature.'],
  [/Monitor przedmeczowy nie wykonuje zewnętrznych odczytów dla sztucznego fixture\./g, 'The pre-match monitor makes no external reads for the synthetic fixture.'],
  [/SKŁADY/g, 'LINEUPS'], [/monitoruję/g, 'monitoring'],
  [/Przed vs po potwierdzeniu składu/g, 'Before vs after lineup confirmation'],
  [/Model nie nadpisuje starej prognozy — pokazuje osobną, audytowalną korektę pre-match\./g, 'The model does not overwrite the previous forecast — it shows a separate, auditable pre-match adjustment.'],
  [/brak wiarygodnego baseline/g, 'no reliable baseline'],
  [/Pogoda • sędzia • podróż \/ odpoczynek/g, 'Weather • referee • travel / rest'],
  [/Brak wiarygodnych danych = wpływ 0\. Sędzia uczy się wyłącznie z rozliczonych meczów\./g, 'No reliable data = zero impact. The referee profile learns only from settled matches.'],
  [/oczekuję na prognozę/g, 'waiting for forecast'],
  [/baza wyjazdowa zbiera się z meczów domowych/g, 'away baseline is built from home matches'],
  [/Zmiany wymagające uwagi/g, 'Changes requiring attention'],
  [/dzisiejsze śledzone mecze/g, 'today’s tracked matches'],
  [/Alerty są zapisywane w aplikacji; po zgodzie przeglądarki dostajesz je też podczas otwartej sesji\./g, 'Alerts are saved in the app; after browser permission, you also receive them during an open session.'],
  [/✓ OBSERWUJĘ/g, '✓ WATCHING'], [/ZAPISZ ANALIZĘ/g, 'SAVE ANALYSIS'], [/ZAPISZ REGUŁY/g, 'SAVE RULES'],
  [/Zaloguj się, aby używać prywatnej watchlisty, reguł alertów i zapisanych analiz\./g, 'Sign in to use the private watchlist, alert rules and saved analyses.'],
  // Production safety copy (mostly has direct EN branches; these are a final UI guard).
  [/Prognoza jest estymacją, nie gwarancją wyniku\./g, 'The forecast is an estimate, not a guarantee.'],
  [/Administrator wyłączył rekomendacje dla tej ligi\. Model może liczyć dane, ale warstwa decyzji nie powinna generować akcji\./g, 'The administrator disabled recommendations for this league. The model may calculate data, but the decision layer should not generate actions.'],
  [/Administrator wyłączył ten rynek w warstwie decyzji\./g, 'The administrator disabled this market in the decision layer.'],
  [/Próbka historyczna jest mała — traktuj wynik jako orientacyjny\./g, 'The historical sample is small — treat the result as indicative.'],
  [/Wiarygodność modelu jest obniżona\. System nie oznacza tego meczu jako pewniaka\./g, 'Model reliability is reduced. The system does not present this match as a certainty.'],
  [/Zaloguj się, aby włączyć Web Push\./g, 'Sign in to enable Web Push.'],
  // Match engine final state copy
  [/Mecz gotowy\. Skład przewidywany z ostatnich realnych XI; formacja i zawodnicy pochodzą z danych API\./g, 'Match ready. The lineup is predicted from recent real XIs; formation and players come from API data.'],
  [/Mecz gotowy\. Silnik wykorzystuje oficjalne składy i formacje z API\./g, 'Match ready. The engine uses official API lineups and formations.'],
  [/Mecz nie spełnia warunków jakości danych\./g, 'The match does not meet data-quality requirements.'],
  [/V320 generuje posiadania, ruch, podania i sytuacje z zamrożonego profilu Bet\+AI\. LIVE AI Coach aktualizuje prawdopodobieństwa wyłącznie z przebiegu tej symulacji; bez kursu live nie potwierdza VALUE\./g, 'V320 generates possession, movement, passes and chances from the frozen Bet+AI profile. LIVE AI Coach updates probabilities only from this simulation; without live odds it does not confirm VALUE.'],
  [/Odśwież API/g, 'Refresh API'],


  // V370 COMPLETE — remaining daily/preparation/live-engine Polish UI.
  // Exact phrases are intentionally listed before the older generic translator.
  [/Tylko 17 wybranych rozgrywek\. Inne ligi są całkowicie pomijane przez Symulację AI\. Skład XI i kursy są opcjonalne\./g, 'Only 17 approved competitions. Every other league is ignored by AI Simulation. Lineups and odds are optional.'],
  [/Wyszukaj mecz, ligę lub kraj/g, 'Search match, league or country'],
  [/Pobieram i kwalifikuję realne mecze dnia…/g, 'Loading and qualifying real fixtures…'],
  [/Brak kolejnych meczów z wystarczającymi realnymi statystykami na dzisiaj\./g, 'No more upcoming fixtures with sufficient real statistics today.'],
  [/Nie udało się pobrać realnych meczów\./g, 'Could not load real fixtures.'],
  [/^Realne kursy$/g, 'Real odds'],
  [/Stadion — dane w przygotowaniu/g, 'Venue data pending'],
  [/Mecz testowy FM AI/g, 'FM AI test match'],
  [/Zakończony/g, 'Finished'], [/Przełożony/g, 'Postponed'], [/Odwołany/g, 'Cancelled'],
  [/Brak rynku/g, 'No market'], [/Typ wskazany przez model/g, 'Pick selected by the model'],
  [/Brak realnego kursu bukmachera — pokazany jest najmocniejszy kierunek modelu\./g, 'No real bookmaker price — the strongest model direction is shown.'],
  [/^Remis$/g, 'Draw'],
  [/nic nie robić/g, 'do nothing'],

  // Preparation screen and full-analysis diagnostics
  [/BET\+AI • PRZYGOTOWANIE SYMULACJI/g, 'BET+AI • SIMULATION PREPARATION'],
  [/Dane gotowe/g, 'Data ready'],
  [/Kursy 1X2/g, '1X2 odds'],
  [/Statystyki drużyn/g, 'Team statistics'],
  [/Realna forma i statystyki obu drużyn spełniają próg Bet\+AI\. Skład XI jest dodatkiem i nie blokuje symulacji\./g, 'Real form and team statistics meet the Bet+AI threshold. The starting XI is additional data and does not block the simulation.'],
  [/Ten mecz nie zostanie dopuszczony do symulacji\. Brakuje wymaganych realnych statystyk sportowych:/g, 'This match will not be admitted to simulation. Required real sports statistics are missing:'],
  [/Symulacja zablokowana/g, 'Simulation blocked'],
  [/Web Intelligence wyłączone — dodaj OPENAI_API_KEY w Netlify\./g, 'Web Intelligence disabled — add OPENAI_API_KEY in Netlify.'],
  [/Pełny model FM AI/g, 'Full FM AI model'],
  [/Rynek no-vig/g, 'No-vig market'],
  [/MASTER CONSENSUS: źródła są zbyt rozbieżne \(([0-9.]+) pp\)\./g, 'MASTER CONSENSUS: sources disagree too strongly ($1 pp).'],
  [/MASTER CONSENSUS: STRONG obniżone do VALUE przez umiarkowaną rozbieżność źródeł \(([0-9.]+) pp\)\./g, 'MASTER CONSENSUS: STRONG downgraded to VALUE because of moderate source disagreement ($1 pp).'],
  [/Końcowa prognoza łączy pełny model FM AI, Daily Scanner i rynek no-vig\. Value jest liczone dopiero po zbudowaniu tego konsensusu\./g, 'The final forecast combines the full FM AI model, Daily Scanner and the no-vig market. Value is calculated only after this consensus is built.'],
  [/ ma wyraźnie lepszą formę ostatnich spotkań/g, ' has clearly better recent form'],
  [/ zdobywa średnio ([0-9.]+) gola na mecz w dostępnej próbce\./g, ' scores an average of $1 goals per match in the available sample.'],
  [/ traci średnio ([0-9.]+) gola — to podnosi profil bramkowy\./g, ' concedes an average of $1 goals — this raises the scoring profile.'],
  [/Consensus: ([0-9]+) źródeł, zgodność ([0-9]+)%\./g, 'Consensus: $1 sources, $2% agreement.'],
  [/Model nie znalazł jednego dominującego czynnika — prognoza jest wynikiem połączenia kilku umiarkowanych sygnałów\./g, 'The model found no single dominant factor — the forecast combines several moderate signals.'],
  [/Forma: ([0-9]+)–([0-9]+)/g, 'Form: $1–$2'],
  [/Gole\/mecz: ([0-9.]+)–([0-9.]+)/g, 'Goals/match: $1–$2'],
  [/Tracone\/mecz: ([0-9.]+)–([0-9.]+)/g, 'Conceded/match: $1–$2'],
  [/H2H: ([0-9]+) meczów • śr\. ([0-9.]+) gola/g, 'H2H: $1 matches • avg. $2 goals'],
  [/Web consensus: ([0-9]+) źródeł • zgodność ([0-9]+)%/g, 'Web consensus: $1 sources • $2% agreement'],
  [/API-Football jest chwilowo zajęte\. Rate Limit Shield spróbuje ponownie automatycznie\./g, 'API-Football is temporarily busy. Rate Limit Shield will retry automatically.'],
  [/Nie udało się pobrać danych symulacji/g, 'Could not load simulation data'],
  [/Nie udało się pobrać meczów/g, 'Could not load matches'],
  [/Błąd pobierania meczu/g, 'Match loading error'],
  [/Błąd danych symulacji/g, 'Simulation data error'],


  // Production / Match Intelligence panels nested inside the FM AI analysis flow
  [/Tryb testowy 0 API/g, '0 API test mode'],
  [/Scheduled Odds, Settlement Cron, Replay i monitoring produkcyjny są pomijane dla sztucznego meczu testowego\./g, 'Scheduled Odds, Settlement Cron, Replay and production monitoring are skipped for the synthetic test match.'],
  [/dzisiejsze realne requesty śledzone przez Budget Guard/g, 'today’s real requests tracked by Budget Guard'],
  [/Monitoring działa z Supabase; dashboard nie wykonuje dodatkowych requestów API-Football\./g, 'Monitoring runs from Supabase; the dashboard makes no additional API-Football requests.'],
  [/Filtry realnej historii modelu/g, 'Real model-history filters'],
  [/Co model wiedział i kiedy\?/g, 'What did the model know and when?'],
  [/^rynków$/g, 'markets'],
  [/Timeline kursów dla tego rynku pojawi się automatycznie, gdy mecz przejdzie przez zaplanowane okna przed kickoffem\./g, 'The odds timeline for this market will appear automatically as the match passes the scheduled pre-kickoff windows.'],
  [/Replay korzysta z zapisanych snapshotów\. Nie rekonstruuje danych z przyszłości i nie odpytuje API-Football podczas odtwarzania\./g, 'Replay uses saved snapshots. It does not reconstruct future data or query API-Football during playback.'],

  [/\bTryb testowy\b/g, 'Test mode'],
  [/Context, Scenario i raport działają lokalnie; Similar Match Memory i Command Center są pomijane dla sztucznego fixture\./g, 'Context, Scenario and the report run locally; Similar Match Memory and Command Center are skipped for the synthetic fixture.'],
  [/Jedno miejsce: decyzje, edge, ryzyka, model, API i integralność danych\./g, 'One place for decisions, edge, risks, model, API and data integrity.'],
  [/MECZE W SYSTEMIE/g, 'MATCHES IN SYSTEM'],
  [/ z pełną prognozą/g, ' with a full forecast'],
  [/brak krytycznych sygnałów/g, 'no critical signals'],
  [/XI continuity • absencje ważnościowe • GK • trener • matchup • schedule stress • shock detector/g, 'XI continuity • weighted absences • GK • coach • matchup • schedule stress • shock detector'],
  [/ poprzednich starterów OUT/g, ' previous starters OUT'],
  [/tylko nowe sygnały ponad V180/g, 'only new signals beyond V180'],
  [/bez wpływu na xG/g, 'no xG impact'],
  [/model i rynek idą przeciwnie/g, 'model and market move in opposite directions'],
  [/brak silnego konfliktu/g, 'no strong conflict'],
  [/Timeline będzie rosnąć wraz ze snapshotami T-24h \/ T-6h \/ T-1h \/ T-15m\./g, 'The timeline will grow with T-24h / T-6h / T-1h / T-15m snapshots.'],
  [/Sprawdź scenariusz/g, 'Test scenario'],
  [/Heurystyczne testy wrażliwości — nie udają prawdziwej informacji o nieobecnym zawodniku\./g, 'Heuristic sensitivity tests — they do not pretend to provide real information about an absent player.'],
  [/Wyjaśnienie bez wymyślania danych/g, 'Explanation without inventing data'],
  [/Raport budowany wyłącznie ze strukturalnych wyników modelu, kontekstu i rynku\./g, 'Report built only from structured model, context and market outputs.'],
  [/30 SEKUND/g, '30 SECONDS'],
  [/EKSPERCKA/g, 'EXPERT'],
  [/DLACZEGO/g, 'WHY'],
  [/CO MOŻE ZMIENIĆ PROGNOZĘ/g, 'WHAT COULD CHANGE THE FORECAST'],
  [/Historycznie podobne sytuacje/g, 'Historically similar situations'],
  [/Wyłącznie wcześniejsze, rozliczone mecze; bieżący fixture nie może wejść do własnej pamięci\./g, 'Only earlier settled matches; the current fixture cannot enter its own memory.'],
  [/wynik podobnych przypadków/g, 'outcome of similar cases'],
  [/historyczna częstość/g, 'historical frequency'],
  [/średni realny wynik/g, 'average real score'],
  [/różnica current vs memory/g, 'current vs memory difference'],

  // Production Platform nested in the FM AI analysis page
  [/Operations, push i historia produkcyjna są pomijane dla sztucznego fixture\./g, 'Operations, push and production history are skipped for the synthetic fixture.'],
  [/Prawdziwe alerty przy zamkniętej karcie/g, 'Real alerts with the tab closed'],
  [/Web Push działa po konfiguracji VAPID w Netlify\. Alerty są deduplikowane per użytkownik i zdarzenie\./g, 'Web Push works after VAPID is configured in Netlify. Alerts are deduplicated per user and event.'],
  [/ŁĄCZĘ…/g, 'CONNECTING…'], [/WŁĄCZ WEB PUSH/g, 'ENABLE WEB PUSH'],
  [/Wszystkie rozliczone analizy/g, 'All settled analyses'],
  [/Filtry po jakości, meczu i wersji modelu\./g, 'Filters by quality, match and model version.'],
  [/^DATA$/g, 'DATE'], [/^MECZ$/g, 'MATCH'], [/^LIGA$/g, 'LEAGUE'], [/^DECYZJA$/g, 'DECISION'], [/^WYNIK$/g, 'RESULT'],
  [/ŁADUJĘ…/g, 'LOADING…'], [/^ODŚWIEŻ$/g, 'REFRESH'],
  [/Timeline zostanie pobrany po otwarciu tej zakładki\./g, 'The timeline will be loaded after opening this tab.'],
  [/Ta sama historia • różne wersje/g, 'Same history • different versions'],
  [/Porównanie 1X2 na realnie rozliczonych eksperymentach\./g, '1X2 comparison on real settled experiments.'],
  [/Co naprawdę mamy w danych\?/g, 'What data do we actually have?'],
  [/^Ostatnie$/g, 'Last'], [/ dni • /g, ' days • '], [/ śledzonych fixture/g, ' tracked fixtures'],
  [/Match-specific automations są zatrzymane\. Dane historyczne pozostają dostępne\./g, 'Match-specific automations are stopped. Historical data remains available.'],
  [/Jednym przyciskiem możesz zatrzymać match-specific jobs i zapisy użytkowników\./g, 'One button can stop match-specific jobs and user writes.'],
  [/WYŁĄCZ SAFE MODE/g, 'DISABLE SAFE MODE'], [/AKTYWUJ SAFE MODE/g, 'ENABLE SAFE MODE'],
  [/ZAPISZ HEALTH SNAPSHOT/g, 'SAVE HEALTH SNAPSHOT'], [/UTWÓRZ BACKUP CONFIG/g, 'CREATE CONFIG BACKUP'],
  [/Brak lig w historii\./g, 'No leagues in history.'], [/Brak eksperymentów\./g, 'No experiments.'], [/Brak backupów\./g, 'No backups.'],
  [/Engine jest domyślnie OFF\. Po włączeniu uzupełnia najpierw dane z istniejącej historii bez API\./g, 'The engine is OFF by default. When enabled, it first backfills data from existing history without API calls.'],

  // Small split text nodes used throughout advanced panels
  [/HISTORIA AKTYWNA/g, 'HISTORY ACTIVE'],
  [/Wagi zmieniają się zależnie od dostępności danych, zgodności źródeł i historycznej jakości modelu\. Kurs bukmachera nie jest używany do sztucznego podbijania prognozy — służy do niezależnej oceny VALUE\./g, 'Weights change with data availability, source agreement and historical model quality. Bookmaker odds are not used to artificially boost the forecast — they are used independently to assess VALUE.'],
  [/NO BET — BLOKADA JAKOŚCIOWA/g, 'NO BET — QUALITY BLOCK'],
  [/VALUE Z OSTRZEŻENIAMI/g, 'VALUE WITH WARNINGS'],
  [/CLEAR — BRAK CZERWONYCH FLAG/g, 'CLEAR — NO RED FLAGS'],
  [/✓ Kalibracja, model agreement, drift i League \/ Market Trust nie uruchomiły blokady\./g, '✓ Calibration, model agreement, drift and League / Market Trust triggered no block.'],
  [/0 DODATKOWYCH REQUESTÓW API/g, '0 ADDITIONAL API REQUESTS'],
  [/CLV po kursie blisko kickoffu •/g, 'CLV after near-kickoff odds •'],
  [/TOP 3 przewagi cenowe/g, 'TOP 3 pricing edges'],
  [/MARŻA USUNIĘTA ✓/g, 'MARGIN REMOVED ✓'], [/NO-VIG NIEDOSTĘPNE/g, 'NO-VIG UNAVAILABLE'],
  [/^KURS$/g, 'ODDS'], [/RYNEK NO-VIG/g, 'NO-VIG MARKET'],
  [/ marża /g, ' margin '],
  [/^Kalibracja$/g, 'Calibration'],
  [/Prawdopodobieństwa są estymacją modelu, nie gwarancją wyniku\. Value V347 porównuje model z ceną rynku po usunięciu marży oraz stosuje Red Flag Guard: kalibrację, model agreement, drift i League \/ Market Trust\./g, 'Probabilities are model estimates, not a guarantee of the result. Value V347 compares the model with the market price after margin removal and applies Red Flag Guard: calibration, model agreement, drift and League / Market Trust.'],
  [/Jedna końcowa prognoza z kilku źródeł/g, 'One final forecast from multiple sources'],
  [/Pełny model, Daily Scanner i rynek no-vig są ważone razem\. Value nie jest już traktowane jako główna predykcja meczu\./g, 'The full model, Daily Scanner and no-vig market are weighted together. Value is no longer treated as the main match prediction.'],
  [/ZGODNOŚĆ ŹRÓDEŁ/g, 'SOURCE AGREEMENT'],
  [/Symulacja korzysta z tej samej prognozy MASTER CONSENSUS V353, którą widzisz w analizie\./g, 'The simulation uses the same MASTER CONSENSUS V353 forecast shown in the analysis.'],
  [/GOLE 2\.5/g, 'GOALS 2.5'],
  [/Bet\+AI pokaże rekomendację dopiero po min\./g, 'Bet+AI will show a recommendation only after at least'],
  [/ rozliczonych próbach danego rynku\./g, ' settled samples for this market.'],
  [/Przewaga \+/g, 'Edge +'], [/ pp jest poniżej wymaganego progu /g, ' pp is below the required threshold '],
  [/Decision Card używa konserwatywnego prawdopodobieństwa\. Symulator nie gwarantuje zysku ani wyniku meczu\./g, 'Decision Card uses a conservative probability. The simulator does not guarantee profit or a match result.'],
  [/bez rynku no-vig/g, 'without no-vig market'],
  [/automatyczne wagi i governance/g, 'automatic weights and governance'],
  [/profile audit w Supabase/g, 'profile audit in Supabase'], [/zbieranie profilu/g, 'collecting profile'],
  [/XI • absencje • fatigue • matchup adjustment/g, 'XI • absences • fatigue • matchup adjustment'],
  [/^absencje\s*$/g, 'absences'], [/^mecze$/g, 'matches'],
  [/kontrola jakości/g, 'quality control'], [/shrinkage aktywny/g, 'shrinkage active'], [/zbieranie out-of-sample historii/g, 'collecting out-of-sample history'],
  [/Mecz odrzucony przez filtr jakości:/g, 'Match rejected by the quality filter:'],
  [/Model ma mocne podstawy do wspierania decyzji\./g, 'The model has strong grounds for supporting the decision.'],
  [/Model jest użyteczny, ale wymaga ostrożniejszego progu value\./g, 'The model is useful, but requires a more conservative value threshold.'],
  [/Nie traktuj tego meczu jako mocnej rekomendacji\./g, 'Do not treat this match as a strong recommendation.'],
  [/Kalibracja historyczna ma ([0-9]+)\/30 wymaganych prób\./g, 'Historical calibration has $1/30 required samples.'],
  [/Historyczna kalibracja tego rynku jest zbyt słaba dla mocnej rekomendacji\./g, 'Historical calibration for this market is too weak for a strong recommendation.'],
  [/TRYB TESTOWY — dane kontrolne, nie używać jako realnej rekomendacji\./g, 'TEST MODE — control data, do not use as a real recommendation.'],
  [/TRYB TESTOWY V152 • 0 requestów API • dane kontrolne nie trafiają do backtestu\./g, 'V152 TEST MODE • 0 API requests • control data is excluded from the backtest.'],
  [/Źródła były rozbieżne/g, 'Sources disagreed'],
  [/Model był zbyt pewny/g, 'The model was overconfident'],
  [/Rynek ma status DRIFT WATCH\./g, 'The market is on DRIFT WATCH.'],
  [/TEST: Challenger ma niższy Brier w ([0-9]+) sparowanych prognozach\./g, 'TEST: Challenger has a lower Brier score across $1 paired forecasts.'],
  [/TEST: V180 przeszedł próg ([0-9]+) par\./g, 'TEST: V180 passed the $1-pair threshold.'],
  [/TEST: OOS log loss potwierdza kalibrację i stacking\./g, 'TEST: OOS log loss confirms calibration and stacking.'],
  [/TEST: Challenger został promowany po paired validation\./g, 'TEST: Challenger was promoted after paired validation.'],
  [/TEST consensus • dane kontrolne offline\./g, 'TEST consensus • offline control data.'],
  [/Forma \+ home\/away/g, 'Form + home/away'],
  [/Ostatnie realne mecze/g, 'Recent real matches'],
  [/BRAK RYNKU/g, 'NO MARKET'],
  [/Brak pełnych kursów potrzebnych do obliczenia rynku no-vig\./g, 'Complete odds required to calculate the no-vig market are missing.'],
  [/NO BET: AUTO-GATE zablokował rynek —/g, 'NO BET: AUTO-GATE blocked the market —'],
  [/NO BET: zbyt niska wiarygodność analizy\./g, 'NO BET: analysis reliability is too low.'],
  [/BET: przewaga pozostaje dodatnia nawet po odjęciu ±([0-9.]+) pp niepewności\./g, 'BET: the edge remains positive even after subtracting ±$1 pp uncertainty.'],
  [/PAPER BETTING \/ SHADOW PORTFOLIO/g, 'PAPER BETTING / SHADOW PORTFOLIO'],
  [/Test rekomendacji bez stawiania pieniędzy/g, 'Recommendation test without staking real money'],
  [/1\.00u \/ typ/g, '1.00u / pick'],
  [/TRYB TESTOWY: wszystkie dane tego jednego meczu są kontrolne\/offline i NIE są zapisywane do realnego backtestu, portfolio ani Supabase\./g, 'TEST MODE: all data for this single match is control/offline data and is NOT written to the real backtest, portfolio or Supabase.'],
  [/niezależnych modeli/g, 'independent models'],
  [/market nie jest wejściem modelu/g, 'the market is not a model input'],
  [/ekspozycja ×/g, 'exposure ×'],
  [/korekta 0:0 • 1:0 • 0:1 • 1:1/g, 'correction 0:0 • 1:0 • 0:1 • 1:1'],
  [/brak wystarczającej próby/g, 'insufficient sample'],

  // Full live Match Engine
  [/Reprezentatywny przebieg wizualny zgodny z głównym sygnałem FM AI\. Monte Carlo pozostaje probabilistyczne\./g, 'Representative visual scenario aligned with the main FM AI signal. Monte Carlo remains probabilistic.'],
  [/🎯 Rzut wolny/g, '🎯 Free kick'],
  [/zawodnika/g, 'player'],
  [/Pełny mecz: 2 minuty przy prędkości x1/g, 'Full match: 2 minutes at x1 speed'],
  [/Brak pełnych oficjalnych XI z pozycjami/g, 'No complete official XIs with positions'],
  [/Boisko nie pokazuje fikcyjnych zawodników\./g, 'The pitch does not show fictional players.'],
  [/Oczekiwanie na oficjalny skład/g, 'Waiting for the official lineup'],
  [/Bet\+AI nie tworzy fikcyjnych nazwisk\. Skład pojawi się automatycznie, gdy API-Football opublikuje startową XI\./g, 'Bet+AI does not create fictional player names. The lineup will appear automatically when API-Football publishes the starting XI.'],
  [/Brak pozycji boiskowych w API/g, 'No pitch positions in API data'],
  [/Brak składu do symulacji/g, 'No lineup available for simulation'],
  [/XI przewidywana z ostatnich realnych składów\./g, 'Predicted XI based on recent real lineups.'],
  [/Bet\+AI nie generuje przypadkowych nazwisk ani ustawienia\./g, 'Bet+AI does not generate random player names or formations.'],
  [/Pobieram realne dane meczu…/g, 'Loading real match data…'],
  [/XI oficjalne\/przewidywane • formacje • H2H • forma • tabela • model Bet\+AI/g, 'official/predicted XI • formations • H2H • form • standings • Bet+AI model'],
  [/reprezentatywny scenariusz zgodny z głównym typem FM AI/g, 'representative scenario aligned with the main FM AI pick'],
  [/snapshot FM AI przekazany bez wymuszania wyniku/g, 'FM AI snapshot passed through without forcing the result'],
  [/Symulacja rozpoczyna się od 00:00\./g, 'Simulation starts at 00:00.'],
  [/Kliknij, aby aktywować prawdziwe audio stadionu/g, 'Click to enable real stadium audio'],
  [/Wycisz dźwięki meczu/g, 'Mute match audio'],
  [/Włącz dźwięki meczu/g, 'Enable match audio'],
  [/Aktywuj prawdziwe audio stadionu/g, 'Enable real stadium audio'],
  [/AKTYWUJ AUDIO/g, 'ENABLE AUDIO'],
  [/DŹWIĘK MECZU/g, 'MATCH AUDIO'],
  [/1 klik • wymóg przeglądarki/g, '1 click • browser requirement'],
  [/Przyśpiewki • reakcje • gwizdek • gol/g, 'Chants • reactions • whistle • goal'],
  [/Głośność dźwięków meczu/g, 'Match audio volume'],
  [/Raport końcowy symulacji/g, 'Final simulation report'],
  [/^\s*czerwone\s*$/g, 'red cards'],
  [/Błąd danych symulacji/g, 'Simulation data error'],

  // FM AI main command center
  [/PREDYKCJE SPORTOWE NOWEJ GENERACJI/g, 'NEXT-GENERATION SPORTS PREDICTIONS'],
  [/Jeden mecz\./g, 'One match.'],
  [/Wszystkie dane\./g, 'All the data.'],
  [/Jasny werdykt\./g, 'Clear verdict.'],
  [/Analizujemy statystyki, formę, kursy i value, aby pokazać tylko najlepsze okazje\./g, 'We analyse statistics, form, odds and value to show only the best opportunities.'],
  [/Uruchom od nowa/g, 'Run again'],
  [/Odśwież analizę/g, 'Refresh analysis'],
  [/Ostatnia analiza:/g, 'Last analysis:'],
  [/Analiza działa automatycznie/g, 'Analysis runs automatically'],
  [/Przygotowuję pełną analizę wszystkich meczów…/g, 'Preparing full analysis of all matches…'],
  [/^sprawdzonych$/g, 'checked'],

  // Forward tracker strip + modal
  [/10 zł flat \/ każdy DOBRY TYP/g, '10 PLN flat / every GOOD PICK'],
  [/Prawdziwy forward tracking • pierwszy opublikowany VALUE\/STRONG VALUE jest zamrażany przed kickoffem/g, 'Real forward tracking • the first published VALUE/STRONG VALUE pick is frozen before kick-off'],
  [/Pełne statystyki →/g, 'Full statistics →'],
  [/BILANS ALL-TIME/g, 'ALL-TIME PROFIT'],
  [/^BILANS$/g, 'PROFIT'],
  [/stawka 10 zł \/ typ/g, '10 PLN stake / pick'],
  [/flat stake 10 zł/g, 'flat stake 10 PLN'],
  [/TRAFNOŚĆ/g, 'HIT RATE'],
  [/próg rynku/g, 'market break-even'],
  [/^oczekuje$/g, 'pending'],
  [/ŚR\. KURS/g, 'AVG. ODDS'],
  [/edge trafności/g, 'hit-rate edge'],
  [/DZISIAJ/g, 'TODAY'],
  [/^typów$/g, 'picks'],
  [/OCENA PRÓBY/g, 'SAMPLE QUALITY'],
  [/ZA MAŁA PRÓBA/g, 'SAMPLE TOO SMALL'],
  [/Dodatni sygnał rentowności/g, 'Positive profitability signal'],
  [/Lekko dodatni wynik — potrzeba większej próby/g, 'Slightly positive result — a larger sample is needed'],
  [/Na razie system jest pod kreską/g, 'The system is currently negative'],
  [/Zbieramy dane — nie wyciągamy wniosków za wcześnie/g, 'Collecting data — no premature conclusions'],
  [/Ładuję statystyki systemu…/g, 'Loading system statistics…'],
  [/Tracker gotowy do uruchomienia/g, 'Tracker ready to start'],
  [/Uruchom jednorazowo plik SUPABASE_RUN_ONCE_WERSJA_368_FM_AI_SYSTEM_TRACKER\.sql\./g, 'Run SUPABASE_RUN_ONCE_WERSJA_368_FM_AI_SYSTEM_TRACKER.sql once.'],
  [/Po pierwszych rozliczonych typach pojawi się bilans, yield i skuteczność\./g, 'Profit, yield and hit rate will appear after the first settled picks.'],
  [/Czy typy naprawdę zarabiają\?/g, 'Do the picks actually make money?'],
  [/10 zł flat na każdy VALUE \/ STRONG VALUE • wynik zamrażany przed kickoffem • bez testowych meczów/g, '10 PLN flat on every VALUE / STRONG VALUE • pick frozen before kick-off • test matches excluded'],
  [/największe obsunięcie/g, 'largest drawdown'],
  [/^PRÓBA$/g, 'SAMPLE'],
  [/DODATNI SYGNAŁ/g, 'POSITIVE SIGNAL'],
  [/LEKKO \+/g, 'SLIGHT +'],
  [/UJEMNY WYNIK/g, 'NEGATIVE RESULT'],
  [/Statystyki według lig/g, 'Statistics by league'],
  [/Statystyki według rynku/g, 'Statistics by market'],
  [/^Liga$/g, 'League'],
  [/^Rynek$/g, 'Market'],
  [/^Typy$/g, 'Picks'],
  [/Ostatnie typy systemu/g, 'Latest system picks'],
  [/^Odśwież$/g, 'Refresh'],
  [/Jak czytać\?/g, 'How to read this?'],
  [/Dodatni bilans i yield mówią, czy płaska stawka 10 zł faktycznie zarabia\. Trafność porównujemy z break-even wynikającym z realnych kursów\. Przy małej próbie wynik może być przypadkowy — sensowne wnioski zaczynają się dopiero po dziesiątkach i setkach rozliczonych typów\./g, 'Positive profit and yield show whether a flat 10 PLN stake is actually profitable. Hit rate is compared with the break-even rate implied by real odds. Small samples can be random — meaningful conclusions begin only after dozens or hundreds of settled picks.'],
  [/Sprawdzam połączenie trackera…/g, 'Checking tracker connection…'],
  [/Tabela trackera nie jest jeszcze widoczna dla API/g, 'The tracker table is not visible to the API yet'],
  [/Brakuje konfiguracji Supabase w Netlify/g, 'Supabase configuration is missing in Netlify'],
  [/Funkcja trackera nie została wdrożona/g, 'The tracker function has not been deployed'],
  [/Tracker chwilowo nie może odczytać danych/g, 'The tracker cannot read data right now'],
  [/Łączę Netlify Functions z Supabase i odświeżam schemat…/g, 'Connecting Netlify Functions to Supabase and refreshing the schema…'],
  [/SQL został uruchomiony\? Odświeżam automatycznie, ale po utworzeniu tabeli Supabase może potrzebować chwili na odświeżenie schematu API\./g, 'Was the SQL run? I am refreshing automatically, but Supabase may need a moment to refresh the API schema after the table is created.'],
  [/Netlify Function nie widzi SUPABASE_URL lub SUPABASE_SERVICE_ROLE_KEY\. Pozostała strona może działać z kluczem publicznym, ale tracker zapisuje dane po stronie serwera\./g, 'The Netlify Function cannot see SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY. The rest of the site may work with the public key, but the tracker writes data server-side.'],
  [/Nowe funkcje get\/record\/settle FM AI V368 nie znalazły się w aktualnym deployu Netlify\./g, 'The new FM AI V368 get/record/settle functions are missing from the current Netlify deploy.'],
  [/Kliknij „Sprawdź ponownie”\. Jeśli problem zostanie, komunikat pokaże konkretną przyczynę zamiast udawać, że brakuje tabeli\./g, 'Click “Check again”. If the issue remains, the message will show the specific cause instead of assuming the table is missing.'],
  [/Sprawdź ponownie/g, 'Check again'],
  [/Statystyki systemu FM AI/g, 'FM AI system statistics'],

  // Remaining FM AI labels and health messages
  [/BRAK KURSÓW/g, 'NO ODDS'],
  [/Trafność/g, 'Hit rate'],
  [/Śr\. kurs/g, 'Avg. odds'],
  [/Bilans/g, 'Profit'],
  [/Warto rozważyć zakład/g, 'Worth considering'],
  [/Przewaga jest mała/g, 'The edge is small'],
  [/Lepiej odpuścić/g, 'Better to skip'],
  [/Czekam na pełne dane rynku/g, 'Waiting for complete market data'],
  [/Model wykrył czerwoną flagę\./g, 'The model detected a red flag.'],
  [/Za mało danych historycznych na mocny werdykt\./g, 'Too little historical data for a strong verdict.'],
  [/Model widzi przewagę nad rynkiem i wysoką zgodność modeli\./g, 'The model sees a market edge and strong model agreement.'],
  [/Model widzi wyraźną przewagę nad rynkiem\./g, 'The model sees a clear edge over the market.'],
  [/Modele są zgodne, ale przewaga kursowa jest ograniczona\./g, 'The models agree, but the pricing edge is limited.'],
  [/Werdykt łączy kurs rynkowy, kalibrację i wiarygodność modelu\./g, 'The verdict combines market price, calibration and model reliability.'],
  [/Za mała próbka: ([0-9]+)\/30/g, 'Sample too small: $1/30'],
  [/Brier ([0-9.]+) jest wysoki/g, 'Brier $1 is high'],
  [/Brier ([0-9.]+) wymaga obserwacji/g, 'Brier $1 needs monitoring'],
  [/Wykryto MODEL DRIFT/g, 'MODEL DRIFT detected'],
  [/Część rynków ma DRIFT WATCH/g, 'Some markets are on DRIFT WATCH'],
  [/Średni CLV ([+\-0-9.]+)%/g, 'Average CLV $1%'],
  [/Kalibracja, Brier i drift są w akceptowalnym zakresie\./g, 'Calibration, Brier and drift are within an acceptable range.'],
  [/Model działa stabilnie, ale większa próbka zwiększy pewność oceny\./g, 'The model is stable, but a larger sample will increase confidence in the assessment.'],
  [/zapisano wcześniej/g, 'saved earlier'],
  [/1 mecz testowy • 0 requestów API/g, '1 test match • 0 API requests'],
  [/Twój limit API może być wyczerpany — ten jeden scenariusz działa lokalnie i pozwala sprawdzić Ensemble, Sharp Disagreement, Audit Trail, Error Analysis, Portfolio Risk, Model Control Center oraz pełną symulację 2D\./g, 'Your API limit may be exhausted — this single scenario runs locally and lets you test Ensemble, Sharp Disagreement, Audit Trail, Error Analysis, Portfolio Risk, Model Control Center and the full 2D simulation.'],
  [/▶ URUCHOM TEST V158/g, '▶ RUN V158 TEST'],

  [/STATYSTYKI/g, 'STATISTICS'],
  [/OSTROŻNIE/g, 'CAUTION'],
  [/GOLE •/g, 'GOALS •'],
  // Hero top pick + KPI area
  [/Top typ dnia/g, 'Top pick of the day'],
  [/MECZ TESTOWY/g, 'TEST MATCH'],
  [/(?<!\p{L})TYP(?!\p{L})/gu, 'PICK'],
  [/(?<!\p{L})KURS(?!\p{L})/gu, 'ODDS'],
  [/SZANSA AI/g, 'AI CHANCE'],
  [/\bOCENA\b/g, 'RATING'],
  [/Pewność/g, 'Confidence'],
  [/Ryzyko/g, 'Risk'],
  [/Dlaczego\?/g, 'Why?'],
  [/Więcej/g, 'More'],
  [/Sprawdzone mecze/g, 'Checked matches'],
  [/Dobre typy/g, 'Good picks'],
  [/Ostrożnie/g, 'Caution'],
  [/Kondycja modelu/g, 'Model health'],
  [/STABILNY/g, 'STABLE'],
  [/Model działa poprawnie • tryb testowy UI\./g, 'Model is operating correctly • UI test mode.'],
  [/Zbieranie historii modelu\./g, 'Collecting model history.'],
  [/Szczegóły PRO/g, 'PRO details'],
  [/Szybciej\. Prościej\. Skuteczniej\./g, 'Faster. Simpler. More effective.'],
  [/Tylko najlepsze okazje\. Zero szumu\./g, 'Only the best opportunities. Zero noise.'],

  // Filters + daily cache
  [/\bWszystkie ligi\b/g, 'All leagues'],
  [/\bWszystkie\b/g, 'All'],
  [/Piłka nożna/g, 'Football'],
  [/\bTenis\b/g, 'Tennis'],
  [/Koszykówka/g, 'Basketball'],
  [/\bHokej\b/g, 'Hockey'],
  [/\bDzisiaj\b/g, 'Today'],
  [/\bJutro\b/g, 'Tomorrow'],
  [/FM AI • PAMIĘĆ DNIA/g, 'FM AI • DAILY MEMORY'],
  [/Wczytano zapisaną analizę/g, 'Loaded saved analysis'],
  [/Dzisiejsza analiza jest zapisana/g, 'Today’s analysis is saved'],
  [/Zapisuję analizę automatycznie/g, 'Saving analysis automatically'],
  [/Zapis z ([^•]+) • bez pełnego skanu od zera\./g, 'Saved at $1 • no full rescan from scratch.'],
  [/Cache ogranicza ponowne skany i zbędne requesty\./g, 'Cache reduces repeat scans and unnecessary requests.'],
  [/⚡ WCZYTANO ZAPIS FM AI/g, '⚡ LOADED FM AI SNAPSHOT'],
  [/bez ponownego pełnego skanu/g, 'without another full scan'],

  // Scan/loading progress
  [/Pobieram mecze dnia/g, 'Loading today’s matches'],
  [/Łączę listę spotkań z API-Football…/g, 'Loading the fixture list from API-Football…'],
  [/Sprawdzam statystyki drużyn/g, 'Checking team statistics'],
  [/Forma, gole, jakość danych i gotowość meczu do analizy\./g, 'Form, goals, data quality and match readiness for analysis.'],
  [/AI liczy kursy, value i ryzyko/g, 'AI calculates odds, value and risk'],
  [/Porównuję model z rynkiem, kalibracją i Red Flag Guard\./g, 'Comparing the model with the market, calibration and Red Flag Guard.'],
  [/Przygotowuję ranking typów/g, 'Preparing pick rankings'],
  [/Pierwsze wyniki pojawią się automatycznie za chwilę\./g, 'The first results will appear automatically shortly.'],
  [/Analiza gotowa/g, 'Analysis complete'],
  [/FM AI zakończył skan dostępnych meczów\./g, 'FM AI has finished scanning available matches.'],
  [/FM AI • ANALIZA W TOKU/g, 'FM AI • ANALYSIS IN PROGRESS'],
  [/ŁADOWANIE/g, 'LOADING'],
  [/\bMecze\b/g, 'Matches'],
  [/lista dnia/g, 'today’s list'],
  [/\bStatystyki\b/g, 'Statistics'],
  [/forma \+ dane/g, 'form + data'],
  [/kurs \+ ryzyko/g, 'odds + risk'],
  [/\bRanking\b/g, 'Ranking'],
  [/top typy/g, 'top picks'],
  [/FM AI pracuje w tle\. W zależności od liczby meczów i API pierwsze pełne statystyki mogą pojawić się po kilkunastu–kilkudziesięciu sekundach\./g, 'FM AI is working in the background. Depending on the number of matches and API response times, the first complete statistics may appear after several to several dozen seconds.'],
  [/Postęp analizy FM AI/g, 'FM AI analysis progress'],

  // Model Intelligence Center
  [/Kontrola jakości modelu na rozliczonych, zamrożonych prognozach pre-match\. Wyniki nie są gwarancją przyszłego zysku\./g, 'Model quality control based on settled, frozen pre-match predictions. Results do not guarantee future profit.'],
  [/PRÓBKA/g, 'SAMPLE'],
  [/śledzone top picks/g, 'tracked top picks'],
  [/niżej = lepiej/g, 'lower = better'],
  [/średnia luka/g, 'average gap'],
  [/([0-9]+) prób/g, '$1 samples'],
  [/Zbieranie historii modelu/g, 'Collecting model history'],
  [/PEŁNY PERFORMANCE BREAKDOWN — kurs \/ confidence \/ edge/g, 'FULL PERFORMANCE BREAKDOWN — odds / confidence / edge'],

  // Best opportunities / Top Picks
  [/Najlepsze okazje dnia/g, 'Best opportunities of the day'],
  [/Wybrane przez FM AI na podstawie value, formy i statystyk\./g, 'Selected by FM AI based on value, form and statistics.'],
  [/SKANOWANIE/g, 'SCANNING'],
  [/1 MECZ TESTOWY/g, '1 TEST MATCH'],
  [/SKAN GOTOWY/g, 'SCAN COMPLETE'],
  [/Szansa AI/g, 'AI chance'],
  [/Dlaczego AI\?/g, 'Why AI?'],
  [/Otwieram…/g, 'Opening…'],
  [/Pełna analiza →/g, 'Full analysis →'],
  [/Najwyższe EV/g, 'Highest EV'],
  [/Najwyższa wiarygodność/g, 'Highest reliability'],
  [/Edge \+ jakość \+ rynek/g, 'Edge + quality + market'],
  [/Ranking uwzględnia teraz EV, Reliability, kalibrację, Market Consensus, drift i League \/ Market Trust\. STRONG VALUE może zostać automatycznie zablokowane przez czerwone flagi\./g, 'The ranking now includes EV, Reliability, calibration, Market Consensus, drift and League / Market Trust. STRONG VALUE can be blocked automatically by red flags.'],
  [/Szukam przewag cenowych i sprawdzam kalibrację…/g, 'Searching for pricing edges and checking calibration…'],
  [/bez kursu/g, 'no odds'],
  [/([0-9]+) prób • model agreement/g, '$1 samples • model agreement'],
  [/OTWIERAM…/g, 'OPENING…'],
  [/PEŁNA ANALIZA →/g, 'FULL ANALYSIS →'],

  // Match cards
  [/ZGODNE/g, 'ALIGNED'],
  [/UMIARKOWANE/g, 'MODERATE'],
  [/ROZBIEŻNE/g, 'DIVERGENT'],
  [/brak sygnału/g, 'no signal'],
  [/KURSY 1X2/g, '1X2 ODDS'],
  [/ BUK\./g, ' BOOKMAKERS'],
  [/1 • DOM/g, '1 • HOME'],
  [/X • REMIS/g, 'X • DRAW'],
  [/2 • GOŚCIE/g, '2 • AWAY'],
  [/Analizuję rynek…/g, 'Analysing market…'],
  [/statystyki \+ model Bet\+AI/g, 'statistics + Bet+AI model'],
  [/Analizuję…/g, 'Analysing…'],
  [/kończę pełny skan meczu/g, 'finishing full match scan'],
  [/analiza \+ live coach/g, 'analysis + live coach'],
  [/ kontra /g, ' vs '],

  // Why AI / prediction timeline / CLV
  [/WHY AI — CO WSPIERA (?:TYP|PICK)/g, 'WHY AI — WHAT SUPPORTS THE PICK'],
  [/RED FLAGS \/ RYZYKA/g, 'RED FLAGS / RISKS'],
  [/Brak istotnych czerwonych flag dla tego typu\./g, 'No significant red flags for this pick.'],
  [/([0-9]+) bukmacherów/g, '$1 bookmakers'],
  [/Sygnał → T24H → T6H → T1H → T15M/g, 'Signal → T24H → T6H → T1H → T15M'],
  [/ŁADOWANIE…/g, 'LOADING…'],
  [/([0-9]+) snapshotów/g, '$1 snapshots'],
  [/Ładuję historię modelu i kursu…/g, 'Loading model and odds history…'],
  [/Snapshoty będą zbierane automatycznie w oknach T24H \/ T6H \/ T1H \/ T15M przed kickoffem\./g, 'Snapshots will be collected automatically at T24H / T6H / T1H / T15M before kick-off.'],
  [/OCZEKUJE NA CLOSING LINE/g, 'WAITING FOR CLOSING LINE'],
  [/FM AI zapisuje kurs sygnału i porówna go z kursem blisko rozpoczęcia meczu\. Dodatni CLV oznacza, że cena wejścia była lepsza od closing line\./g, 'FM AI stores the signal odds and compares them with the price near kick-off. Positive CLV means the entry price was better than the closing line.'],
  [/OTWÓRZ PEŁNĄ ANALIZĘ →/g, 'OPEN FULL ANALYSIS →'],
  [/Value i CLV są narzędziami oceny modelu, nie gwarancją wygranej\./g, 'Value and CLV are model-evaluation tools, not a guarantee of winning.'],
  [/Zamknij/g, 'Close'],
  [/kurs —/g, 'odds —'],

  // Dynamic Why AI explanations + red flags generated by the policy layer
  [/ ma lepszy trend formy/g, ' has the better form trend'],
  [/ zdobywa średnio ([0-9.]+) gola w próbce skanera\./g, ' scores an average of $1 goals in the scanner sample.'],
  [/ traci średnio ([0-9.]+) gola — ryzyko dla typu na gospodarzy\./g, ' concedes an average of $1 goals — a risk for the home-win pick.'],
  [/ traci średnio ([0-9.]+) gola — ryzyko dla typu na gości\./g, ' concedes an average of $1 goals — a risk for the away-win pick.'],
  [/Forma drużyn jest zbliżona/g, 'The teams have similar form'],
  [/co wspiera scenariusz wyrównanego meczu\./g, 'which supports a balanced-match scenario.'],
  [/Różnica formy wynosi ([0-9]+) pkt — to osłabia scenariusz remisu\./g, 'The form gap is $1 points — this weakens the draw scenario.'],
  [/ zdobywa średnio ([0-9.]+) gola\./g, ' scores an average of $1 goals.'],
  [/ traci średnio ([0-9.]+) gola\./g, ' concedes an average of $1 goals.'],
  [/Obie drużyny mają niski profil strzelecki w próbce skanera\./g, 'Both teams have a low scoring profile in the scanner sample.'],
  [/ zdobywa tylko ([0-9.]+) gola średnio — wspiera niższy total\./g, ' scores only $1 goals on average — supporting a lower total.'],
  [/ traci tylko ([0-9.]+) gola średnio\./g, ' concedes only $1 goals on average.'],
  [/Co najmniej jedna drużyna ma wysoki profil strzelecki — ryzyko dla Under\./g, 'At least one team has a high scoring profile — a risk for the Under.'],
  [/Co najmniej jedna defensywa regularnie dopuszcza gole — ryzyko dla Under\./g, 'At least one defence regularly allows goals — a risk for the Under.'],
  [/Obie drużyny zdobywają średnio co najmniej 1\.20 gola/g, 'Both teams score at least 1.20 goals on average'],
  [/Obie defensywy tracą ponad 1 gola średnio/g, 'Both defences concede more than 1 goal on average'],
  [/Jedna z drużyn ma niski profil strzelecki — ryzyko dla BTTS TAK\./g, 'One team has a low scoring profile — a risk for BTTS YES.'],
  [/Jedna z drużyn ma niski profil strzelecki, co wspiera BTTS NIE\./g, 'One team has a low scoring profile, supporting BTTS NO.'],
  [/Co najmniej jedna defensywa ma niski profil straconych goli\./g, 'At least one defence has a low goals-conceded profile.'],
  [/Obie drużyny mają wysoki profil strzelecki — ryzyko dla BTTS NIE\./g, 'Both teams have a high scoring profile — a risk for BTTS NO.'],
  [/Model agreement ([0-9]+)% — źródła modelowe są zgodne\./g, 'Model agreement $1% — model sources are aligned.'],
  [/Model agreement tylko ([0-9]+)% — źródła są rozbieżne\./g, 'Model agreement only $1% — model sources disagree.'],
  [/Market consensus: ([0-9]+) bukmacherów, zgodność ([0-9]+)%\./g, 'Market consensus: $1 bookmakers, $2% agreement.'],
  // V370 hard-complete pack: exact phrases that were still able to appear in Polish
  // because older modules render legacy labels dynamically.
  [/NAJBLIŻSZY MECZ/g, 'NEXT MATCH'],
  [/BRAK KURSÓW/g, 'NO ODDS'], [/BRAK RYNKU/g, 'NO MARKET'], [/^BRAK$/g, 'NONE'],
  [/ŚR\. KURS/g, 'AVG. ODDS'],
  [/STATYSTYKI MECZU/g, 'MATCH STATISTICS'],
  [/MECZ ODRZUCONY — ZA MAŁO DANYCH/g, 'MATCH REJECTED — INSUFFICIENT DATA'],
  [/Realne kursy dostępne/g, 'Real odds available'],
  [/Część źródeł chwilowo nie odpowiedziała\. Model użyje wyłącznie dostępnych danych\./g, 'Some sources did not respond. The model will use available data only.'],
  [/źródeł znalezionych/g, 'sources found'],
  [/Historyczna pewność jest dobrze skalibrowana/g, 'Historical confidence is well calibrated'],
  [/Ostatnie realne mecze/g, 'Recent real matches'],
  [/Błąd Web Intelligence/g, 'Web Intelligence error'], [/Brak fixture ID/g, 'No fixture ID'],
  [/Powyżej 1\.5/g, 'Over 1.5'], [/Powyżej 2\.5/g, 'Over 2.5'], [/Powyżej 3\.5/g, 'Over 3.5'],
  [/Poniżej 1\.5/g, 'Under 1.5'], [/Poniżej 2\.5/g, 'Under 2.5'], [/Poniżej 3\.5/g, 'Under 3.5'],
  [/Model nie znajduje wystarczająco mocnego sygnału do rekomendacji\./g, 'The model does not find a strong enough signal for a recommendation.'],
  [/ ma wyższe xG w modelu: ([0-9.]+) – ([0-9.]+)\./g, ' has higher model xG: $1 – $2.'],
  [/Model daje równe xG: ([0-9.]+) – ([0-9.]+)\./g, 'The model gives equal xG: $1 – $2.'],
  [/Najwyższy kierunek 1X2: ([^—]+) — ([0-9.]+)%\./g, 'Strongest 1X2 direction: $1 — $2%.'],
  [/Profil bramkowy:/g, 'Goals profile:'],
  [/Dostępne kursy: ([0-9]+) źródeł bukmacherskich; Value Engine pozostaje niezależny od modelu\./g, 'Available odds: $1 bookmaker sources; Value Engine remains independent from the model.'],
  [/Brak pełnego rynku no-vig — kurs nie wpływa na samą prognozę modelu\./g, 'No complete no-vig market — odds do not affect the model forecast itself.'],
  [/Kierunki poniżej pozostają informacyjne — model nie rekomenduje obecnie stawki\./g, 'The directions below remain informational — the model currently does not recommend a stake.'],
  [/RYNEK BRAMKOWY/g, 'GOALS MARKET'],
  [/◐ UMIARKOWANA ZGODNOŚĆ/g, '◐ MODERATE AGREEMENT'],
  [/API zajęte • używam ostatnich poprawnych danych z cache/g, 'API busy • using the latest valid cached data'],
  [/Nie znaleziono wystarczającej liczby niezależnych prognoz dla tego meczu\./g, 'Not enough independent forecasts were found for this match.'],
  [/RYNEK \/ KURSY/g, 'MARKET / ODDS'],
  [/zbieranie historii/g, 'collecting history'],
  [/Rynek jest tylko warstwą wyceny\./g, 'The market is only a pricing layer.'],
  [/Źródła consensus:/g, 'Consensus sources:'], [/używane do decyzji/g, 'used for the decision'], [/bez marży/g, 'no margin'],
  [/BET: przewaga pozostaje dodatnia nawet po odjęciu ±([0-9.]+) pp niepewności\./g, 'BET: the edge remains positive even after subtracting ±$1 pp of uncertainty.'],
  [/WATCH: dodatnia przewaga istnieje, ale nie przechodzi konserwatywnego progu wejścia\./g, 'WATCH: a positive edge exists, but it does not pass the conservative entry threshold.'],
  [/WATCH: modele składowe mają średnią rozbieżność \(([0-9.]+) pp\)\./g, 'WATCH: component models show moderate disagreement ($1 pp).'],
  [/Brak wystarczającej przewagi po konserwatywnej korekcie\./g, 'Insufficient edge after the conservative adjustment.'],
  [/NAJWAŻNIEJSZE POWODY/g, 'KEY REASONS'],
  [/Co naprawdę wpływa na ocenę tego meczu/g, 'What really drives this match rating'],
  // League/country metadata shown in the left selector and cards.
  [/Najwyższa liga w Anglii/g, 'Top league in England'], [/Najwyższa liga w Niemczech/g, 'Top league in Germany'],
  [/Najwyższa liga w Portugalii/g, 'Top league in Portugal'], [/Najwyższa liga piłkarska w Polsce/g, 'Top football league in Poland'],
  [/Najwyższa liga w Hiszpanii/g, 'Top league in Spain'], [/Najwyższa liga we Włoszech/g, 'Top league in Italy'],
  [/Druga liga we Włoszech/g, 'Second division in Italy'], [/Najwyższa liga w Holandii/g, 'Top league in the Netherlands'],
  [/Najwyższa liga we Francji/g, 'Top league in France'],
  [/^Włochy$/g, 'Italy'], [/^Świat$/g, 'World'],
  // Match Operations / Intelligence / Live Pre-Match text nodes
  [/([0-9]+) MECZÓW/g, '$1 MATCHES'], [/brak freeze/g, 'no freeze'],
  [/Freeze Ledger \+ kursy T-24h \/ T-6h \/ T-1h \/ T-15m/g, 'Freeze Ledger + odds T-24h / T-6h / T-1h / T-15m'],
  [/brak danych/g, 'no data'], [/zbieranie poprzednich XI/g, 'collecting previous XIs'],
  [/rynek ([0-9.]+)/g, 'market $1'], [/czekam na kursy/g, 'waiting for odds'],
  [/Skład potwierdzony/g, 'Lineup confirmed'], [/Rotacja XI/g, 'XI rotation'],
  [/Zmiana bramkarza/g, 'Goalkeeper change'], [/Zmiana ustawienia/g, 'Formation change'],
  [/Nowa absencja startera/g, 'New starter absence'], [/Zmiana decyzji/g, 'Decision change'],
  [/Spadek confidence/g, 'Confidence drop'], [/Zmiana probability/g, 'Probability change'],
  [/Ruch rynku/g, 'Market move'], [/^Pogoda$/g, 'Weather'],
  [/Nowa zmiana przed meczem/g, 'New pre-match change'],
  [/Zaloguj się, aby używać tej funkcji\./g, 'Sign in to use this feature.'],
  [/Monitor przedmeczowy nie wykonuje zewnętrznych odczytów dla sztucznego fixture\./g, 'The pre-match monitor makes no external reads for the synthetic fixture.'],
  [/SKŁADY/g, 'LINEUPS'], [/monitoruję/g, 'monitoring'],
  [/Przed vs po potwierdzeniu składu/g, 'Before vs after lineup confirmation'],
  [/Model nie nadpisuje starej prognozy — pokazuje osobną, audytowalną korektę pre-match\./g, 'The model does not overwrite the previous forecast — it shows a separate, auditable pre-match adjustment.'],
  [/brak wiarygodnego baseline/g, 'no reliable baseline'],
  [/Pogoda • sędzia • podróż \/ odpoczynek/g, 'Weather • referee • travel / rest'],
  [/Brak wiarygodnych danych = wpływ 0\. Sędzia uczy się wyłącznie z rozliczonych meczów\./g, 'No reliable data = zero impact. The referee profile learns only from settled matches.'],
  [/oczekuję na prognozę/g, 'waiting for forecast'],
  [/baza wyjazdowa zbiera się z meczów domowych/g, 'away baseline is built from home matches'],
  [/Zmiany wymagające uwagi/g, 'Changes requiring attention'],
  [/dzisiejsze śledzone mecze/g, 'today’s tracked matches'],
  [/Alerty są zapisywane w aplikacji; po zgodzie przeglądarki dostajesz je też podczas otwartej sesji\./g, 'Alerts are saved in the app; after browser permission, you also receive them during an open session.'],
  [/✓ OBSERWUJĘ/g, '✓ WATCHING'], [/ZAPISZ ANALIZĘ/g, 'SAVE ANALYSIS'], [/ZAPISZ REGUŁY/g, 'SAVE RULES'],
  [/Zaloguj się, aby używać prywatnej watchlisty, reguł alertów i zapisanych analiz\./g, 'Sign in to use the private watchlist, alert rules and saved analyses.'],
  // Production safety copy (mostly has direct EN branches; these are a final UI guard).
  [/Prognoza jest estymacją, nie gwarancją wyniku\./g, 'The forecast is an estimate, not a guarantee.'],
  [/Administrator wyłączył rekomendacje dla tej ligi\. Model może liczyć dane, ale warstwa decyzji nie powinna generować akcji\./g, 'The administrator disabled recommendations for this league. The model may calculate data, but the decision layer should not generate actions.'],
  [/Administrator wyłączył ten rynek w warstwie decyzji\./g, 'The administrator disabled this market in the decision layer.'],
  [/Próbka historyczna jest mała — traktuj wynik jako orientacyjny\./g, 'The historical sample is small — treat the result as indicative.'],
  [/Wiarygodność modelu jest obniżona\. System nie oznacza tego meczu jako pewniaka\./g, 'Model reliability is reduced. The system does not present this match as a certainty.'],
  [/Zaloguj się, aby włączyć Web Push\./g, 'Sign in to enable Web Push.'],
  // Match engine final state copy
  [/Mecz gotowy\. Skład przewidywany z ostatnich realnych XI; formacja i zawodnicy pochodzą z danych API\./g, 'Match ready. The lineup is predicted from recent real XIs; formation and players come from API data.'],
  [/Mecz gotowy\. Silnik wykorzystuje oficjalne składy i formacje z API\./g, 'Match ready. The engine uses official API lineups and formations.'],
  [/Mecz nie spełnia warunków jakości danych\./g, 'The match does not meet data-quality requirements.'],
  [/V320 generuje posiadania, ruch, podania i sytuacje z zamrożonego profilu Bet\+AI\. LIVE AI Coach aktualizuje prawdopodobieństwa wyłącznie z przebiegu tej symulacji; bez kursu live nie potwierdza VALUE\./g, 'V320 generates possession, movement, passes and chances from the frozen Bet+AI profile. LIVE AI Coach updates probabilities only from this simulation; without live odds it does not confirm VALUE.'],
  [/Odśwież API/g, 'Refresh API'],
  [/Cena daje \+([0-9.]+) pp edge po usunięciu marży; EV ([+\-0-9.]+)%\./g, 'Price gives a +$1 pp edge after removing the margin; EV $2%.'],
  [/Przewaga wynika z połączenia modelu prawdopodobieństwa, ceny no-vig i kalibracji historycznej\./g, 'The edge comes from combining the probability model, no-vig price and historical calibration.'],
  [/Data Quality ([0-9]+)\/100 poniżej progu STRONG/g, 'Data Quality $1/100 below the STRONG threshold'],
  [/Kalibracja ([0-9]+)\/([0-9]+) prób/g, 'Calibration $1/$2 samples'],
  [/STRONG wymaga ([0-9]+) prób \(([0-9]+)\/([0-9]+)\)/g, 'STRONG requires $1 samples ($2/$3)'],
  [/Słaba kalibracja historyczna rynku/g, 'Poor historical market calibration'],
  [/Model agreement ([0-9]+)% poniżej progu STRONG/g, 'Model agreement $1% below the STRONG threshold'],
  [/Market consensus tylko ([0-9]+)%/g, 'Market consensus only $1%'],
  [/Wykryto drift dla tego rynku/g, 'Drift detected for this market'],
  [/Rynek jest pod obserwacją driftu/g, 'This market is under drift watch'],
  [/Rynek przesunął się przeciw modelowi o ([0-9.]+) pp/g, 'The market moved $1 pp against the model'],
  [/Nietypowo duża przewaga — wymaga dodatkowej weryfikacji ceny/g, 'Unusually large edge — additional price verification required'],

  // Status / source messages from the daily scan
  [/Brak kolejnych nierozpoczętych meczów na dzisiaj\./g, 'No more upcoming matches today.'],
  [/PEŁNA ANALIZA FM AI • 0\/([0-9]+) meczów • każdy mecz zostanie sprawdzony/g, 'FULL FM AI ANALYSIS • 0/$1 matches • every match will be checked'],
  [/PEŁNA ANALIZA FM AI ZAKOŃCZONA • ([0-9]+)\/([0-9]+) meczów sprawdzonych/g, 'FULL FM AI ANALYSIS COMPLETE • $1/$2 matches checked'],
  [/Zapisana analiza jest dostępna\. Nie udało się odświeżyć danych w tle\./g, 'Saved analysis is available. Background refresh failed.'],
  [/ODŚWIEŻAM FM AI • pobieram świeże mecze i uruchamiam pełną analizę…/g, 'REFRESHING FM AI • loading fresh matches and starting full analysis…'],
  [/Pełna analiza została podjęta, ale źródło danych chwilowo nie odpowiedziało\./g, 'Full analysis was attempted, but the data source did not respond.'],
  [/Błąd analizy meczu/g, 'Match-analysis error'],
  [/Błąd połączenia z trackerem/g, 'Tracker connection error'],
  [/Nie udało się ukończyć analizy wybranego meczu\./g, 'Could not complete analysis of the selected match.'],
  [/FM AI • kończę pełną analizę:/g, 'FM AI • finishing full analysis:'],
  [/Nie udało się ukończyć analizy/g, 'Could not complete analysis'],
  [/błąd danych/g, 'data error'],

  // Market labels that can come back from saved tracker rows
  [/Powyżej ([0-9.]+) gola/g, 'Over $1 goals'],
  [/Poniżej ([0-9.]+) gola/g, 'Under $1 goals'],
  [/BTTS • TAK/g, 'BTTS • YES'],
  [/BTTS • NIE/g, 'BTTS • NO'],
  [/Obie drużyny strzelą/g, 'Both teams to score'],
  [/Nie obie strzelą/g, 'Both teams not to score'],

  // Exact translations end here. Broad token fallbacks are applied only after
  // V335/V336 so they can never split a longer phrase into a Polish/English hybrid.
]

const SIMULATOR_EN_REPLACEMENTS_V370_FALLBACK = [
  [/(?<!\p{L})TAK(?!\p{L})/gu, 'YES'], [/(?<!\p{L})NIE(?!\p{L})/gu, 'NO'],
  [/(?<!\p{L})GOSPODARZE(?!\p{L})/gu, 'HOME'], [/(?<!\p{L})GOŚCIE(?!\p{L})/gu, 'AWAY'],
  [/(?<!\p{L})Gospodarze(?!\p{L})/gu, 'Home'], [/(?<!\p{L})Goście(?!\p{L})/gu, 'Away'],
  [/(?<!\p{L})Drużyna(?!\p{L})/gu, 'Team'], [/(?<!\p{L})Piłka(?!\p{L})/gu, 'Ball'],
  [/(?<!\p{L})liga(?!\p{L})/gu, 'league'], [/(?<!\p{L})prób(?!\p{L})/gu, 'samples'],
  [/(?<!\p{L})snapshotów(?!\p{L})/gu, 'snapshots'], [/(?<!\p{L})źródeł(?!\p{L})/gu, 'sources'],
  [/(?<!\p{L})pewność(?!\p{L})/gu, 'confidence'],
  [/(?<!\p{L})mecze(?!\p{L})/gu, 'matches'], [/(?<!\p{L})meczów(?!\p{L})/gu, 'matches'],
  [/(?<!\p{L})sprawdzonych(?!\p{L})/gu, 'checked'], [/(?<!\p{L})oczekuje(?!\p{L})/gu, 'pending'],
  [/(?<!\p{L})typów(?!\p{L})/gu, 'picks'], [/(?<!\p{L})rynków(?!\p{L})/gu, 'markets'],
  [/(?<!\p{L})gole(?!\p{L})/gu, 'goals'],
  [/(?<!\p{L})zgodność(?!\p{L})/gu, 'agreement'],
  [/(?<!\p{L})zł(?!\p{L})/gu, 'PLN'],
]

function translateSimulatorTextV335(value = '') {
  let output = String(value ?? '')
  for (const [pattern, replacement] of [...SIMULATOR_EN_REPLACEMENTS_V370_FM_AI, ...SIMULATOR_EN_REPLACEMENTS_V335, ...SIMULATOR_EN_REPLACEMENTS_V336_EXTRA, ...SIMULATOR_EN_REPLACEMENTS_V370_FALLBACK]) output = output.replace(pattern, replacement)
  return output
}

function translateSimulatorDomV335(root) {
  if (!root || typeof document === 'undefined') return
  const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT)
  const nodes = []
  let node
  while ((node = walker.nextNode())) nodes.push(node)
  nodes.forEach(textNode => {
    const parent = textNode.parentElement
    if (!parent || ['SCRIPT', 'STYLE'].includes(parent.tagName)) return
    const next = translateSimulatorTextV335(textNode.nodeValue)
    if (next !== textNode.nodeValue) textNode.nodeValue = next
  })
  root.querySelectorAll('[title],[aria-label],[placeholder]').forEach(el => {
    ;['title', 'aria-label', 'placeholder'].forEach(attr => {
      const value = el.getAttribute(attr)
      if (!value) return
      const next = translateSimulatorTextV335(value)
      if (next !== value) el.setAttribute(attr, next)
    })
  })
}

export default function MatchSimulatorFlowView({ lang = 'pl' }) {
  const [stage, setStage] = useState(() => SHOW_FM_AI_INTRO_V345 ? 'intro' : 'matches')
  const [selectedMatch, setSelectedMatch] = useState(null)
  const [preparedData, setPreparedData] = useState(null)
  const flowRef = useRef(null)

  useEffect(() => {
    if (lang !== 'en' || !flowRef.current) return undefined
    const root = flowRef.current
    const apply = () => translateSimulatorDomV335(root)
    apply()
    const observer = new MutationObserver(apply)
    observer.observe(root, { childList: true, subtree: true, characterData: true, attributes: true, attributeFilter: ['title', 'aria-label', 'placeholder'] })
    return () => observer.disconnect()
  }, [lang, stage])

  const openDailyMatches = useCallback(() => setStage('matches'), [])
  const openPreparation = useCallback((match) => {
    setSelectedMatch(match || null)
    setPreparedData(null)
    setStage('prep')
    window.scrollTo({ top: 0, behavior: 'smooth' })
  }, [])
  const openMatchEngine = useCallback((match, data) => {
    setSelectedMatch(match || null)
    setPreparedData(data || null)
    setStage('match')
    window.scrollTo({ top: 0, behavior: 'smooth' })
  }, [])
  const backToMatches = useCallback(() => {
    setStage('matches')
    window.scrollTo({ top: 0, behavior: 'smooth' })
  }, [])

  return (
    <div ref={flowRef} className={`match-simulator-flow-v87 is-${stage}`} data-simulator-lang={lang} data-no-translate="true">
      {SHOW_FM_AI_INTRO_V345 && stage === 'intro' && <MatchSimulatorIntroView key={`intro-${lang}`} lang={lang} onComplete={openDailyMatches} />}
      {stage === 'matches' && <MatchSimulatorDailyMatchesView key={`matches-${lang}`} lang={lang} onSelectMatch={openPreparation} />}
      {stage === 'prep' && <MatchSimulatorPreparationView key={`prep-${lang}`} lang={lang} match={selectedMatch} onBack={backToMatches} onStart={openMatchEngine} />}
      {stage === 'match' && <div className="match-simulator-stage-v87"><MatchSimulatorView key={`match-${lang}`} lang={lang} selectedMatch={selectedMatch} preparedData={preparedData} /></div>}
    </div>
  )
}
