import React,{useEffect,useMemo,useRef,useState} from 'react'
import { supabase } from './supabaseClient'

const n=(v,f=0)=>{const x=Number(v);return Number.isFinite(x)?x:f}
const safe=(v,f='—')=>{const s=String(v==null?'':v).trim();return s||f}
const pct=v=>`${n(v).toFixed(1)}%`
const dt=v=>{try{return v?new Date(v).toLocaleString('pl-PL',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}):'—'}catch(_){return'—'}}
async function call(url,options={}){const r=await fetch(url,{cache:'no-store',...options});const p=await r.json().catch(()=>({}));if(!r.ok||p?.ok===false)throw new Error(p?.error||`HTTP ${r.status}`);return p}
function authHeaders(token,extra={}){return token?{...extra,Authorization:`Bearer ${token}`}:{...extra}}
function Kpi({label,value,sub,tone=''}){return <article className={tone}><small>{label}</small><b>{value}</b><span>{sub}</span></article>}
function Toggle({on,label,disabled,onClick}){return <button type="button" disabled={disabled} className={`v300-toggle ${on?'on':'off'}`} onClick={onClick}><i/>{label}<b>{on?'ON':'OFF'}</b></button>}
function HealthRing({score=0,status='PENDING'}){const s=Math.max(0,Math.min(100,n(score)));return <div className={`v300-health-ring h-${String(status).toLowerCase()}`} style={{'--score':`${s*3.6}deg`}}><div><b>{s}</b><span>/100</span><small>{status}</small></div></div>}
function urlBase64ToUint8Array(base64String=''){const padding='='.repeat((4-base64String.length%4)%4);const base64=(base64String+padding).replace(/-/g,'+').replace(/_/g,'/');const raw=atob(base64);return Uint8Array.from([...raw].map(c=>c.charCodeAt(0)))}
function sessionKey(){try{let k=localStorage.getItem('betai-v300-session');if(!k){k=`s_${Date.now()}_${Math.random().toString(36).slice(2)}`;localStorage.setItem('betai-v300-session',k)}return k}catch(_){return `s_${Math.random().toString(36).slice(2)}`}}

export default function ProductionPlatformV300({lang='pl',match={},forecast=null}){
  const pl=lang!=='en',fixtureId=String(match?.apiFixtureId||match?.id||''),isTest=Boolean(match?.isBetAiLabTest||fixtureId.startsWith('betai-lab-test'))
  const [token,setToken]=useState(''),[dash,setDash]=useState(null),[history,setHistory]=useState([]),[timeline,setTimeline]=useState(null),[models,setModels]=useState([]),[coverage,setCoverage]=useState(null),[tab,setTab]=useState('overview'),[error,setError]=useState(''),[busy,setBusy]=useState(''),[search,setSearch]=useState(''),[minQuality,setMinQuality]=useState(0),[pushState,setPushState]=useState('idle'),[abVariant,setAbVariant]=useState('control'),[timelineTarget,setTimelineTarget]=useState(fixtureId),[timelineLabel,setTimelineLabel]=useState(`${safe(match?.home,'HOME')} – ${safe(match?.away,'AWAY')}`)
  const mounted=useRef(true),sid=useMemo(()=>sessionKey(),[])
  const admin=dash?.admin?.admin?dash.admin:null,settings=dash?.health?.settings||dash?.admin?.settings||{},health=dash?.health||{},flags=dash?.flags||[],runtimeControls=dash?.runtimeControls||[]
  const enabled=k=>{const f=flags.find(x=>x.flag_key===k);if(!f)return true;if(f.enabled===false)return false;const pctRoll=Math.max(0,Math.min(100,n(f.rollout_pct,100)));if(pctRoll>=100)return true;let h=0;for(const ch of `${k}|${sid}`)h=((h<<5)-h+ch.charCodeAt(0))|0;return Math.abs(h)%100<pctRoll}
  const controlEnabled=(type,key)=>{if(!key)return true;const c=runtimeControls.find(x=>x.control_type===type&&String(x.control_key)===String(key));return c?c.enabled!==false:true}
  const responsible=useMemo(()=>{const d=forecast?.professionalLab?.decisionCard||{};const sample=n(d.sampleSize),rel=n(d.reliability),conf=n(d.conservativeProbability||d.calibratedProbability||d.rawProbability),market=String(d.marketKey||d.market||forecast?.value?.top?.marketKey||forecast?.value?.top?.market||'');let level='STANDARD',note=pl?'Prognoza jest estymacją, nie gwarancją wyniku.':'Prediction is an estimate, not a guarantee.';if(!controlEnabled('league',match?.league)){level='ADMIN LEAGUE OFF';note=pl?'Administrator wyłączył rekomendacje dla tej ligi. Model może liczyć dane, ale warstwa decyzji nie powinna generować akcji.':'Administrator disabled recommendations for this league.'}else if(market&&!controlEnabled('market',market)){level='ADMIN MARKET OFF';note=pl?'Administrator wyłączył ten rynek w warstwie decyzji.':'Administrator disabled this market in the decision layer.'}else if(sample<30){level='LOW SAMPLE';note=pl?'Próbka historyczna jest mała — traktuj wynik jako orientacyjny.':'Historical sample is small; treat the result as indicative.'}else if(rel<55){level='LOW RELIABILITY';note=pl?'Wiarygodność modelu jest obniżona. System nie oznacza tego meczu jako pewniaka.':'Model reliability is reduced; this match is never presented as a certainty.'}else if(conf>=80){level='HIGH PROBABILITY ≠ CERTAINTY';note=pl?'Wysokie probability nadal nie oznacza pewnego wyniku.':'High probability still does not mean a certain outcome.'}return{level,note,sample,rel,market}},[forecast,pl,match?.league,runtimeControls])

  const loadDash=async(authToken=token)=>{try{const p=await call('/.netlify/functions/match-platform-v300?mode=dashboard',{headers:authHeaders(authToken)});if(mounted.current){setDash(p);setModels(p.models||[]);setCoverage(p.health?.coverage||null);setError('')}}catch(e){if(mounted.current)setError(e.message)}}
  const loadHistory=async()=>{if(isTest)return;setBusy('history');try{const q=new URLSearchParams({mode:'history',limit:'80',minQuality:String(minQuality)});if(search)q.set('search',search);const p=await call(`/.netlify/functions/match-platform-v300?${q}`);setHistory(p.rows||[])}catch(e){setError(e.message)}finally{setBusy('')}}
  const loadTimeline=async(target=timelineTarget||fixtureId)=>{if(isTest||!target)return;setBusy('timeline');try{const p=await call(`/.netlify/functions/match-platform-v300?mode=timeline&fixture=${encodeURIComponent(target)}`);setTimeline(p.timeline||null)}catch(e){setError(e.message)}finally{setBusy('')}}
  const loadCoverage=async()=>{setBusy('coverage');try{const p=await call('/.netlify/functions/match-platform-v300?mode=coverage&days=30');setCoverage(p.coverage)}catch(e){setError(e.message)}finally{setBusy('')}}
  const loadModels=async()=>{setBusy('models');try{const p=await call('/.netlify/functions/match-platform-v300?mode=models');setModels(p.models||[])}catch(e){setError(e.message)}finally{setBusy('')}}
  const post=async(body,authToken=token)=>call('/.netlify/functions/match-platform-v300',{method:'POST',headers:authHeaders(authToken,{'Content-Type':'application/json'}),body:JSON.stringify(body)})
  const analytics=(eventName,detail={})=>{if(settings?.safe_mode||settings?.read_only_mode)return;post({action:'analytics',eventName,sessionKey:sid,fixtureId,league:match?.league||'',featureKey:'production_platform_v300',variant:abVariant,detail}).catch(()=>{})}

  useEffect(()=>{mounted.current=true;setTimelineTarget(fixtureId);setTimelineLabel(`${safe(match?.home,'HOME')} – ${safe(match?.away,'AWAY')}`);setTimeline(null);(async()=>{let t='';try{const {data:s}=await supabase?.auth?.getSession?.()||{};t=s?.session?.access_token||''}catch(_){}if(!mounted.current)return;setToken(t);await loadDash(t);try{const p=await post({action:'ab_assign',experimentKey:'prediction_explanation_layout',subjectKey:sid},t);if(mounted.current)setAbVariant(p.variant||'control')}catch(_){} })();return()=>{mounted.current=false}},[fixtureId])
  useEffect(()=>{if(!dash)return;analytics('v300_platform_view',{tab:'overview',health:dash?.health?.status||''})},[dash?.health?.status])
  useEffect(()=>{if(tab==='history'&&enabled('historical_explorer')&&!history.length)loadHistory();if(tab==='timeline'&&enabled('timeline_viewer')&&!timeline)loadTimeline();if(tab==='models'&&enabled('model_comparison'))loadModels();if(tab==='coverage'&&enabled('data_coverage'))loadCoverage();analytics('v300_tab_open',{tab})},[tab])

  const enablePush=async()=>{if(!token){setError(pl?'Zaloguj się, aby włączyć Web Push.':'Sign in to enable Web Push.');return}if(!('serviceWorker'in navigator)||!('PushManager'in window)||typeof Notification==='undefined'){setPushState('unsupported');return}setBusy('push');try{const cfg=await call('/.netlify/functions/match-platform-v300?mode=push_config');if(!cfg.enabled||!cfg.publicKey){setPushState('needs-vapid');return}const perm=await Notification.requestPermission();if(perm!=='granted'){setPushState(perm);return}const reg=await navigator.serviceWorker.register('/betai-sw-v300.js',{scope:'/'});await navigator.serviceWorker.ready;let sub=await reg.pushManager.getSubscription();if(!sub)sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:urlBase64ToUint8Array(cfg.publicKey)});await post({action:'push_subscribe',subscription:sub.toJSON(),userAgent:navigator.userAgent});setPushState('enabled');analytics('v300_push_enabled',{})}catch(e){setError(e.message);setPushState('error')}finally{setBusy('')}}
  const adminPost=async(body)=>{setBusy(body.action);try{const p=await post(body);await loadDash(token);return p}catch(e){setError(e.message);throw e}finally{setBusy('')}}
  const toggleSafe=()=>adminPost({action:'set_system',safe_mode:!settings.safe_mode,safe_mode_reason:settings.safe_mode?'':`Admin V300 • ${new Date().toISOString()}`})
  const makeBackup=()=>adminPost({action:'create_backup',label:`V300 backup ${new Date().toLocaleString('pl-PL')}`})
  const restoreBackup=async id=>{if(!window.confirm(pl?'Przywrócić konfigurację z tego backupu?':'Restore configuration from this backup?'))return;await adminPost({action:'restore_backup',id})}
  const healthSnapshot=()=>adminPost({action:'health_snapshot'})

  if(isTest)return <section className="v300-shell test"><header><div><small>V281–V300 • PRODUCTION PLATFORM 2.0</small><strong>Tryb testowy</strong><p>Operations, push i historia produkcyjna są pomijane dla sztucznego fixture.</p></div><span>OFFLINE</span></header></section>

  return <section className={`v300-shell health-${String(health.status||'pending').toLowerCase()} ${settings.safe_mode?'safe-mode':''} ${abVariant==='compact'?'ab-compact':''}`}>
    <header className="v300-master-head"><div><small>BET+AI • V281–V300 PRODUCTION PLATFORM 2.0</small><strong>Master Operations Dashboard</strong><p>Push • Explorer • Timeline • Model Studio • Coverage • Recovery • Admin • Export • Backup • Health</p></div><div className="v300-head-actions"><span className={settings.safe_mode?'danger':'ok'}>{settings.safe_mode?'SYSTEM SAFE MODE':'SYSTEM ONLINE'}</span><button onClick={()=>loadDash(token)}>↻</button></div></header>

    <div className="v300-master-grid">
      <HealthRing score={health.score} status={health.status}/>
      <div className="v300-master-kpis">
        <Kpi label="DATA COVERAGE" value={`${health.components?.coverage??'—'}/100`} sub={`XI ${pct(coverage?.lineups)} • closing ${pct(coverage?.closingLine)}`} tone={n(health.components?.coverage)<60?'watch':''}/>
        <Kpi label="AUTOMATION" value={`${health.components?.jobs??'—'}/100`} sub={`pending settlement ${health.counters?.pendingSettlement??'—'}`} tone={n(health.components?.jobs)<75?'watch':''}/>
        <Kpi label="DATA INTEGRITY" value={`${health.components?.integrity??'—'}/100`} sub={`critical ${health.counters?.criticalAnomalies||0} • warn ${health.counters?.warnings||0}`} tone={n(health.components?.integrity)<80?'bad':''}/>
        <Kpi label="API HEALTH" value={`${health.components?.api??'—'}/100`} sub={`24h errors ${health.counters?.apiErrors24h||0}`} tone={n(health.components?.api)<80?'watch':''}/>
        <Kpi label="FROZEN PREDICTIONS" value={health.counters?.frozenPredictions??'—'} sub="immutable history"/>
        <Kpi label="ACTIVE MODEL" value={safe(models?.[0]?.version,'COLLECTING')} sub={models?.[0]?.brier!=null?`Brier ${n(models[0].brier).toFixed(4)} • ${models[0].samples} samples`:'waiting for settled samples'}/>
      </div>
    </div>
    {(health.alerts||[]).length>0&&<div className="v300-alert-strip">{health.alerts.slice(0,5).map((a,i)=><span key={i}>⚠ {a}</span>)}</div>}

    <nav className="v300-tabs">{[['overview','OVERVIEW'],['history','HISTORY'],['timeline','TIMELINE'],['models','MODELS'],['coverage','COVERAGE']].map(([k,l])=><button key={k} onClick={()=>setTab(k)} className={tab===k?'active':''}>{l}</button>)}{admin&&<button onClick={()=>setTab('admin')} className={tab==='admin'?'active admin':''}>ADMIN</button>}</nav>

    {tab==='overview'&&<div className="v300-panel">
      <div className="v300-section-head"><div><small>V281–V284 • WEB PUSH / NOTIFICATIONS 2.0</small><strong>Prawdziwe alerty przy zamkniętej karcie</strong><p>Web Push działa po konfiguracji VAPID w Netlify. Alerty są deduplikowane per użytkownik i zdarzenie.</p></div><button disabled={busy==='push'||settings.safe_mode} onClick={enablePush}>{pushState==='enabled'?'✓ PUSH ON':busy==='push'?'ŁĄCZĘ…':'WŁĄCZ WEB PUSH'}</button></div>
      {pushState==='needs-vapid'&&<p className="v300-note warn">VAPID nie jest jeszcze skonfigurowany w Netlify: VAPID_PUBLIC_KEY / VAPID_PRIVATE_KEY / VAPID_SUBJECT.</p>}
      <div className="v300-grid four"><Kpi label="PUSH" value={settings.push_enabled===false?'ADMIN OFF':pushState==='enabled'?'ACTIVE':'READY'} sub="XI • probability • decision • API alerts"/><Kpi label="A/B VARIANT" value={abVariant.toUpperCase()} sub="sticky assignment per session"/><Kpi label="FEATURE FLAGS" value={flags.filter(f=>f.enabled).length} sub={`${flags.length} public flags loaded`}/><Kpi label="SAFE MODE" value={settings.safe_mode?'ACTIVE':'OFF'} sub={settings.safe_mode_reason||'automatic jobs protected'} tone={settings.safe_mode?'bad':'ok'}/></div>

      <div className="v300-responsible"><div><small>V296 • RESPONSIBLE DECISION LAYER</small><strong>{responsible.level}</strong><p>{responsible.note}</p></div><span>sample {responsible.sample||0} • reliability {responsible.rel||0}/100</span></div>

      <div className="v300-section-head compact"><div><small>V297 • EXPORT CENTER</small><strong>Eksport historii analiz</strong><p>CSV lub JSON, bez modyfikacji historii w Supabase.</p></div><div className="v300-inline-actions"><a href="/.netlify/functions/match-platform-v300?mode=export&format=csv&limit=1000">CSV</a><a href="/.netlify/functions/match-platform-v300?mode=export&format=json&limit=1000">JSON</a><a href="/.netlify/functions/match-platform-v300?mode=export&format=pdf&limit=160">PDF</a></div></div>
    </div>}

    {tab==='history'&&enabled('historical_explorer')&&<div className="v300-panel">
      <div className="v300-section-head"><div><small>V285 • HISTORICAL MATCH EXPLORER</small><strong>Wszystkie rozliczone analizy</strong><p>Filtry po jakości, meczu i wersji modelu.</p></div><span>{history.length} ROWS</span></div>
      <div className="v300-filters"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Arsenal, liga…"/><select value={minQuality} onChange={e=>setMinQuality(Number(e.target.value))}><option value="0">Quality: all</option><option value="60">≥60</option><option value="70">≥70</option><option value="80">≥80</option></select><button onClick={loadHistory}>{busy==='history'?'SZUKAM…':'SZUKAJ'}</button></div>
      <div className="v300-table-wrap"><table><thead><tr><th>DATA</th><th>MECZ</th><th>LIGA</th><th>MODEL</th><th>Q</th><th>DECYZJA</th><th>WYNIK</th><th>BRIER</th></tr></thead><tbody>{history.map(r=><tr key={r.fixtureId} className="clickable" onClick={()=>{setTimelineTarget(r.fixtureId);setTimelineLabel(`${r.home} – ${r.away}`);setTimeline(null);setTab('timeline')}}><td>{dt(r.date)}</td><td><b>{r.home}</b> – {r.away}</td><td>{r.league}</td><td>{r.model}</td><td>{r.dataQuality}</td><td>{r.decision||'—'}</td><td>{r.actual}</td><td>{r.brier==null?'—':n(r.brier).toFixed(4)}</td></tr>)}</tbody></table></div>
    </div>}

    {tab==='timeline'&&enabled('timeline_viewer')&&<div className="v300-panel">
      <div className="v300-section-head"><div><small>V286 • PREDICTION TIMELINE VIEWER</small><strong>{timelineLabel}</strong><p>Freeze → odds → lineup events → decision history.</p></div><button onClick={loadTimeline}>{busy==='timeline'?'ŁADUJĘ…':'ODŚWIEŻ'}</button></div>
      <div className="v300-timeline">
        {[...(timeline?.freezes||[]).map(x=>({t:x.captured_at,type:'FREEZE',title:x.model_version,sub:`quality ${x.data_quality} • ${x.selected_for_backtest?'BACKTEST':'CAPTURE'}`})),...(timeline?.odds||[]).map(x=>({t:x.captured_at,type:x.snapshot_window,title:`${x.market_key} @ ${n(x.odds).toFixed(2)}`,sub:`${x.bookmaker} • edge ${n(x.edge_pp).toFixed(1)} pp`})),...(timeline?.events||[]).map(x=>({t:x.created_at,type:x.event_type,title:x.event_type,sub:safe(x?.detail?.summary||x.source_window,'')})),...(timeline?.decisions||[]).map(x=>({t:x.captured_at,type:'DECISION',title:x.decision,sub:`${x.market_key||''} • ${pct(x.probability)} • conf ${x.confidence??'—'}`}))].sort((a,b)=>Date.parse(a.t)-Date.parse(b.t)).slice(-80).map((x,i)=><span key={`${x.t}-${i}`}><time>{dt(x.t)}</time><b>{x.type}</b><strong>{x.title}</strong><em>{x.sub}</em></span>)}
        {!timeline&&<p>Timeline zostanie pobrany po otwarciu tej zakładki.</p>}
      </div>
    </div>}

    {tab==='models'&&enabled('model_comparison')&&<div className="v300-panel">
      <div className="v300-section-head"><div><small>V287 • MODEL COMPARISON STUDIO</small><strong>Ta sama historia • różne wersje</strong><p>Porównanie 1X2 na realnie rozliczonych eksperymentach.</p></div><button onClick={loadModels}>↻</button></div>
      <div className="v300-model-list">{models.length?models.map((m,i)=><article key={m.version} className={i===0?'leader':''}><small>#{i+1} • {m.role||'MODEL'}</small><strong>{m.version}</strong><div><span>SAMPLES <b>{m.samples}</b></span><span>BRIER <b>{m.brier==null?'—':n(m.brier).toFixed(4)}</b></span><span>ACC <b>{m.accuracy==null?'—':pct(m.accuracy)}</b></span></div></article>):<p>COLLECTING</p>}</div>
    </div>}

    {tab==='coverage'&&enabled('data_coverage')&&<div className="v300-panel">
      <div className="v300-section-head"><div><small>V288 • DATA COVERAGE DASHBOARD</small><strong>Co naprawdę mamy w danych?</strong><p>Ostatnie {coverage?.days||30} dni • {coverage?.fixtures||0} śledzonych fixture.</p></div><button onClick={loadCoverage}>↻</button></div>
      <div className="v300-coverage">{[['OFFICIAL XI','lineups'],['INJURIES','injuries'],['WEATHER','weather'],['REFEREE','referee'],['TRAVEL','travel'],['CLOSING LINE','closingLine'],['CONTEXT','context'],['QUALITY ≥70','highQuality']].map(([l,k])=><article key={k}><header><small>{l}</small><b>{pct(coverage?.[k])}</b></header><div><i style={{width:`${Math.max(0,Math.min(100,n(coverage?.[k])))}%`}}/></div></article>)}</div>
    </div>}

    {tab==='admin'&&admin&&<div className="v300-panel admin-panel">
      <div className="v300-section-head"><div><small>V292–V300 • ADMIN CONTROL CENTER</small><strong>Production controls</strong><p>{admin.identity?.email||'ADMIN'} • {admin.identity?.via}</p></div><span>ADMIN VERIFIED</span></div>
      <div className="v300-safe-card"><div><small>SYSTEM SAFE MODE</small><strong>{settings.safe_mode?'ACTIVE — READ ONLY':'OFF — AUTOMATION ACTIVE'}</strong><p>{settings.safe_mode?'Match-specific automations są zatrzymane. Dane historyczne pozostają dostępne.':'Jednym przyciskiem możesz zatrzymać match-specific jobs i zapisy użytkowników.'}</p></div><button className={settings.safe_mode?'recover':'danger'} disabled={busy==='set_system'} onClick={toggleSafe}>{settings.safe_mode?'WYŁĄCZ SAFE MODE':'AKTYWUJ SAFE MODE'}</button></div>
      <div className="v300-admin-toggles"><Toggle on={settings.auto_jobs_enabled!==false} label="AUTO JOBS" disabled={settings.safe_mode||busy==='set_system'} onClick={()=>adminPost({action:'set_system',auto_jobs_enabled:!(settings.auto_jobs_enabled!==false),restoreAutoJobs:false})}/><Toggle on={Boolean(settings.backfill_enabled)} label="BACKFILL" disabled={settings.safe_mode||busy==='set_system'} onClick={()=>adminPost({action:'set_system',backfill_enabled:!settings.backfill_enabled,restoreAutoJobs:false})}/><Toggle on={settings.analytics_enabled!==false} label="ANALYTICS" disabled={busy==='set_system'} onClick={()=>adminPost({action:'set_system',analytics_enabled:!(settings.analytics_enabled!==false),restoreAutoJobs:false})}/><Toggle on={settings.push_enabled!==false} label="WEB PUSH" disabled={busy==='set_system'} onClick={()=>adminPost({action:'set_system',push_enabled:!(settings.push_enabled!==false),restoreAutoJobs:false})}/></div>
      <div className="v300-admin-actions"><button onClick={healthSnapshot} disabled={busy}>ZAPISZ HEALTH SNAPSHOT</button><button onClick={makeBackup} disabled={busy}>UTWÓRZ BACKUP CONFIG</button></div>
      <div className="v300-admin-cols"><section><small>V292 • JOB CONTROLS</small>{(admin.runtimeControls||[]).filter(x=>x.control_type==='job').map(c=><button key={`job-${c.control_key}`} onClick={()=>adminPost({action:'set_runtime_control',controlType:'job',controlKey:c.control_key,enabled:!c.enabled,config:c.config||{}})}><span>{c.control_key}</span><b>{c.enabled?'ON':'OFF'}</b></button>)}</section><section><small>V292 • MARKET CONTROLS</small>{(admin.runtimeControls||[]).filter(x=>x.control_type==='market').map(c=><button key={`market-${c.control_key}`} onClick={()=>adminPost({action:'set_runtime_control',controlType:'market',controlKey:c.control_key,enabled:!c.enabled,config:c.config||{}})}><span>{c.control_key}</span><b>{c.enabled?'ON':'OFF'}</b></button>)}</section></div>
      <div className="v300-admin-cols"><section><small>V292 • LEAGUE CONTROLS</small>{(admin.leagueOptions||[]).slice(0,20).map(l=>{const c=(admin.runtimeControls||[]).find(x=>x.control_type==='league'&&x.control_key===l),on=c?c.enabled!==false:true;return <button key={`league-${l}`} onClick={()=>adminPost({action:'set_runtime_control',controlType:'league',controlKey:l,enabled:!on})}><span>{l}</span><b>{on?'ON':'OFF'}</b></button>})}{!(admin.leagueOptions||[]).length&&<p>Brak lig w historii.</p>}</section><section><small>V294 • A/B TESTING</small>{(admin.experiments||[]).map(e=><button key={e.experiment_key} onClick={()=>adminPost({action:'set_experiment',experimentKey:e.experiment_key,enabled:!e.enabled,variants:e.variants,allocation:e.allocation,description:e.description})}><span>{e.experiment_key}</span><b>{e.enabled?'ACTIVE':'SHADOW/OFF'}</b></button>)}{!(admin.experiments||[]).length&&<p>Brak eksperymentów.</p>}</section></div>
      <div className="v300-admin-cols"><section><small>V293 • FEATURE FLAGS</small>{(admin.flags||[]).map(f=><button key={f.flag_key} onClick={()=>adminPost({action:'set_flag',flagKey:f.flag_key,enabled:!f.enabled,rolloutPct:f.rollout_pct})}><span>{f.flag_key}</span><b>{f.enabled?'ON':'OFF'} • {f.rollout_pct}%</b></button>)}</section><section><small>V298 • CONFIG BACKUPS</small>{(admin.backups||[]).map(b=><button key={b.id} onClick={()=>restoreBackup(b.id)}><span>{b.label}</span><b>{dt(b.created_at)}</b></button>)}{!(admin.backups||[]).length&&<p>Brak backupów.</p>}</section></div>
      <div className="v300-admin-cols"><section><small>V291 • RETRY QUEUE</small>{(admin.retry||[]).slice(0,12).map(r=><button key={r.id} onClick={()=>adminPost({action:'retry_job',id:r.id})}><span>{r.target_function}</span><b>{r.status} • {r.attempts}/{r.max_attempts}</b></button>)}{!(admin.retry||[]).length&&<p>Queue empty ✓</p>}</section><section><small>V289 • BACKFILL</small><p>Engine jest domyślnie OFF. Po włączeniu uzupełnia najpierw dane z istniejącej historii bez API.</p><b>{(admin.backfill||[]).length} queue items</b><em>active push subscriptions: {admin.activePushSubscriptions||0}</em></section></div>
    </div>}
    {error&&<p className="v300-error">⚠ {error}</p>}
  </section>
}
